/**
 * Deprecation & removal mechanism tests.
 *
 * Tests the Schema_Compiler deprecation/removal logic and runtime patterns:
 * 1. Deprecated tool description prefix injection
 * 2. Runtime deprecation warning injection into responses
 * 3. Removed tool migration guidance error responses
 * 4. Registry structure (GENERATED_DEPRECATED_TOOLS, GENERATED_REMOVED_TOOLS)
 * 5. Schema_Compiler removed tools detection logic
 *
 * Validates: Requirements 12.1
 */
import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import {
  GENERATED_DEPRECATED_TOOLS,
  GENERATED_REMOVED_TOOLS,
  GENERATED_ENDPOINT_REPLACES,
  GENERATED_ENDPOINT_METHOD_ACCESS,
} from '../packages/core-mcp/src/tools/_registry.js';

// ─── Helpers: simulate the patterns generated by compile-schema.ts ───

/**
 * Simulates the Schema_Compiler's deprecated description prefix logic.
 * When a tool has `deprecated: true` and `replaced_by`, the compiler prepends
 * `[DEPRECATED] Use {replaced_by} instead.` to the description.
 */
function applyDeprecatedPrefix(description: string, deprecated: boolean, replacedBy?: string): string {
  if (deprecated && replacedBy) {
    return `[DEPRECATED] Use ${replacedBy} instead. ${description}`;
  }
  return description;
}

/**
 * Simulates the runtime deprecation warning injection pattern.
 * The Schema_Compiler generates this code in bridge tool handlers for deprecated tools.
 */
function injectDeprecation(result: unknown, replacedBy: string): unknown {
  if (typeof result === 'object' && result !== null) {
    (result as Record<string, unknown>)._deprecation = {
      warning: `This tool is deprecated. Use ${replacedBy} instead.`,
      replacement: replacedBy,
    };
  }
  return result;
}

/**
 * Simulates the migration guidance error response for Phase 3 removed tools.
 */
function buildMigrationError(toolName: string, info: { endpoint: string; method: string }): object {
  return {
    ok: false,
    error: `Tool "${toolName}" has been removed. Use ${info.endpoint}(method: "${info.method}") instead.`,
    migration: { endpoint: info.endpoint, method: info.method },
  };
}

// ─── 1. Schema_Compiler deprecated tool description prefix ───

describe('Schema_Compiler deprecated description prefix', () => {
  it('prepends [DEPRECATED] prefix when deprecated=true and replaced_by is set', () => {
    const original = 'Get detailed node info by ID.';
    const result = applyDeprecatedPrefix(original, true, 'nodes.get');
    expect(result).toBe('[DEPRECATED] Use nodes.get instead. Get detailed node info by ID.');
  });

  it('starts with [DEPRECATED]', () => {
    const result = applyDeprecatedPrefix('Some description', true, 'text.create');
    expect(result.startsWith('[DEPRECATED]')).toBe(true);
  });

  it('contains the replaced_by value in the prefix', () => {
    const result = applyDeprecatedPrefix('Original desc', true, 'shapes.create_frame');
    expect(result).toContain('shapes.create_frame');
  });

  it('does not modify description when deprecated=false', () => {
    const original = 'Normal tool description.';
    const result = applyDeprecatedPrefix(original, false, 'nodes.get');
    expect(result).toBe(original);
  });

  it('does not modify description when replaced_by is undefined', () => {
    const original = 'Normal tool description.';
    const result = applyDeprecatedPrefix(original, true, undefined);
    expect(result).toBe(original);
  });
});

// ─── 2. Deprecation warning injection logic ───

describe('runtime deprecation warning injection', () => {
  it('injects _deprecation field into object results', () => {
    const result = { ok: true, data: 'some data' };
    injectDeprecation(result, 'nodes.get');
    expect(result).toHaveProperty('_deprecation');
  });

  it('_deprecation.warning contains the replacement info', () => {
    const result = { ok: true } as Record<string, unknown>;
    injectDeprecation(result, 'nodes.get');
    const dep = result._deprecation as { warning: string; replacement: string };
    expect(dep.warning).toBe('This tool is deprecated. Use nodes.get instead.');
  });

  it('_deprecation.replacement matches the replaced_by value', () => {
    const result = {} as Record<string, unknown>;
    injectDeprecation(result, 'components.list');
    const dep = result._deprecation as { warning: string; replacement: string };
    expect(dep.replacement).toBe('components.list');
  });

  it('does not modify null result', () => {
    const result = injectDeprecation(null, 'nodes.get');
    expect(result).toBeNull();
  });

  it('does not modify non-object result (string)', () => {
    const result = injectDeprecation('plain string', 'nodes.get');
    expect(result).toBe('plain string');
  });

  it('does not modify non-object result (number)', () => {
    const result = injectDeprecation(42, 'nodes.get');
    expect(result).toBe(42);
  });

  it('does not modify undefined result', () => {
    const result = injectDeprecation(undefined, 'nodes.get');
    expect(result).toBeUndefined();
  });
});

// ─── 3. Removed tools migration guidance ───

describe('removed tools migration guidance', () => {
  it('error message contains the tool name', () => {
    const err = buildMigrationError('get_node_info', { endpoint: 'nodes', method: 'get' });
    expect((err as Record<string, unknown>).error).toContain('get_node_info');
  });

  it('error message contains the endpoint name and method', () => {
    const err = buildMigrationError('get_node_info', { endpoint: 'nodes', method: 'get' });
    const error = (err as Record<string, unknown>).error as string;
    expect(error).toContain('nodes');
    expect(error).toContain('"get"');
  });

  it('migration object has correct endpoint and method', () => {
    const err = buildMigrationError('patch_nodes', { endpoint: 'nodes', method: 'update' }) as Record<string, unknown>;
    const migration = err.migration as { endpoint: string; method: string };
    expect(migration.endpoint).toBe('nodes');
    expect(migration.method).toBe('update');
  });

  it('ok field is false', () => {
    const err = buildMigrationError('delete_nodes', { endpoint: 'nodes', method: 'delete' }) as Record<string, unknown>;
    expect(err.ok).toBe(false);
  });

  it('produces correct output for various tool/endpoint/method combinations', () => {
    const cases = [
      { tool: 'create_text', endpoint: 'text', method: 'create' },
      { tool: 'set_text_content', endpoint: 'text', method: 'set_content' },
      { tool: 'create_frame', endpoint: 'shapes', method: 'create_frame' },
      { tool: 'list_components', endpoint: 'components', method: 'list' },
    ];
    for (const { tool, endpoint, method } of cases) {
      const err = buildMigrationError(tool, { endpoint, method }) as Record<string, unknown>;
      expect(err.ok).toBe(false);
      expect((err.error as string)).toContain(tool);
      expect((err.error as string)).toContain(endpoint);
      expect((err.error as string)).toContain(`"${method}"`);
      const migration = err.migration as { endpoint: string; method: string };
      expect(migration.endpoint).toBe(endpoint);
      expect(migration.method).toBe(method);
    }
  });
});

// ─── 4. Registry structure tests ───

describe('registry structure', () => {
  it('GENERATED_DEPRECATED_TOOLS is a valid Record<string, { replacedBy: string }>', () => {
    expect(typeof GENERATED_DEPRECATED_TOOLS).toBe('object');
    expect(GENERATED_DEPRECATED_TOOLS).not.toBeNull();
    for (const [key, value] of Object.entries(GENERATED_DEPRECATED_TOOLS)) {
      expect(typeof key).toBe('string');
      expect(value).toHaveProperty('replacedBy');
      expect(typeof value.replacedBy).toBe('string');
    }
  });

  it('GENERATED_REMOVED_TOOLS is a valid Record<string, { endpoint: string; method: string }>', () => {
    expect(typeof GENERATED_REMOVED_TOOLS).toBe('object');
    expect(GENERATED_REMOVED_TOOLS).not.toBeNull();
    for (const [key, value] of Object.entries(GENERATED_REMOVED_TOOLS)) {
      expect(typeof key).toBe('string');
      expect(value).toHaveProperty('endpoint');
      expect(value).toHaveProperty('method');
      expect(typeof value.endpoint).toBe('string');
      expect(typeof value.method).toBe('string');
    }
  });

  it('GENERATED_DEPRECATED_TOOLS is empty after Phase 3 (tools moved to removed)', () => {
    expect(Object.keys(GENERATED_DEPRECATED_TOOLS).length).toBe(0);
  });

  it('GENERATED_REMOVED_TOOLS contains 29 removed flat tools (Phase 3)', () => {
    expect(Object.keys(GENERATED_REMOVED_TOOLS).length).toBe(29);
  });
});

// ─── 5. Schema_Compiler removed tools detection logic ───

describe('Schema_Compiler removed tools detection logic', () => {
  it('GENERATED_ENDPOINT_REPLACES maps endpoints to flat tool names', () => {
    // Verify the mapping structure is correct — these are the tools that WOULD
    // populate GENERATED_REMOVED_TOOLS if they were removed from toolDefs
    for (const [endpoint, flatTools] of Object.entries(GENERATED_ENDPOINT_REPLACES)) {
      expect(Array.isArray(flatTools)).toBe(true);
      expect(flatTools.length).toBeGreaterThan(0);
      // Each flat tool name should be a non-empty string
      for (const tool of flatTools) {
        expect(typeof tool).toBe('string');
        expect(tool.length).toBeGreaterThan(0);
      }
    }
  });

  it('ENDPOINT_REPLACES flat tools have corresponding methods in ENDPOINT_METHOD_ACCESS', () => {
    // For each endpoint, verify that the number of replaced flat tools matches
    // the number of methods in ENDPOINT_METHOD_ACCESS
    for (const [endpoint, flatTools] of Object.entries(GENERATED_ENDPOINT_REPLACES)) {
      const methodAccess = GENERATED_ENDPOINT_METHOD_ACCESS[endpoint];
      expect(methodAccess).toBeDefined();
      const methodCount = Object.keys(methodAccess).length;
      // The number of replaced flat tools should equal the number of methods
      expect(flatTools.length).toBe(methodCount);
    }
  });

  it('simulated removal: if a flat tool is removed, it would appear in REMOVED_TOOLS with correct endpoint/method', () => {
    // Simulate the Schema_Compiler logic: for each endpoint, if a maps_to tool
    // is NOT in toolDefs, it should appear in GENERATED_REMOVED_TOOLS
    // We verify the mapping would be correct by checking ENDPOINT_REPLACES against ENDPOINT_METHOD_ACCESS
    for (const [endpoint, flatTools] of Object.entries(GENERATED_ENDPOINT_REPLACES)) {
      const methods = GENERATED_ENDPOINT_METHOD_ACCESS[endpoint];
      // Build a reverse map: flat tool name → method name
      const methodEntries = Object.entries(methods);
      // Each flat tool should correspond to exactly one method
      expect(flatTools.length).toBe(methodEntries.length);
    }
  });
});


// ─── Property 13: 废弃工具标记与警告 (Property-Based Test) ───

describe('Feature: endpoint-mode-refactor, Property 13: 废弃工具标记与警告', () => {
  /**
   * Validates: Requirements 10.1, 10.2, 10.3
   *
   * For any tool marked as deprecated: true:
   * (a) Its description should start with [DEPRECATED] prefix
   * (b) Calling the tool should produce a response with _deprecation field containing replaced_by info
   */
  it('applyDeprecatedPrefix always starts with [DEPRECATED] and contains replacedBy and original description', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 50 }),  // toolName
        fc.string({ minLength: 1, maxLength: 100 }), // description
        fc.string({ minLength: 1, maxLength: 30 }),   // replacedBy (e.g. "nodes.get")
        (toolName, description, replacedBy) => {
          // Test description prefix
          const prefixed = applyDeprecatedPrefix(description, true, replacedBy);
          expect(prefixed.startsWith('[DEPRECATED]')).toBe(true);
          expect(prefixed).toContain(replacedBy);
          expect(prefixed).toContain(description);

          // Test deprecation injection
          const result: Record<string, unknown> = { ok: true, data: toolName };
          injectDeprecation(result, replacedBy);
          expect(result._deprecation).toBeDefined();
          expect((result._deprecation as { warning: string; replacement: string }).warning).toContain(replacedBy);
          expect((result._deprecation as { warning: string; replacement: string }).replacement).toBe(replacedBy);
        }
      ),
      { numRuns: 100 }
    );
  });
});

// ─── Property 14: 已移除工具的迁移指引 (Property-Based Test) ───

describe('Feature: endpoint-mode-refactor, Property 14: 已移除工具的迁移指引', () => {
  /**
   * Validates: Requirements 11.3
   *
   * For any removed flat tool name, the migration guidance error should contain
   * the correct endpoint tool name and method name.
   */

  // Build all possible (flatTool, endpoint, method) triples from registry data
  const REMOVAL_CANDIDATES: Array<{ flatTool: string; endpoint: string; method: string }> = [];
  for (const [endpoint, flatTools] of Object.entries(GENERATED_ENDPOINT_REPLACES)) {
    const methods = Object.keys(GENERATED_ENDPOINT_METHOD_ACCESS[endpoint] ?? {});
    for (const flatTool of flatTools) {
      for (const method of methods) {
        REMOVAL_CANDIDATES.push({ flatTool, endpoint, method });
      }
    }
  }

  it('buildMigrationError produces correct error with endpoint and method for all removal candidates', () => {
    fc.assert(
      fc.property(
        fc.constantFrom(...REMOVAL_CANDIDATES),
        ({ flatTool, endpoint, method }) => {
          const err = buildMigrationError(flatTool, { endpoint, method }) as {
            ok: boolean;
            error: string;
            migration: { endpoint: string; method: string };
          };
          expect(err.ok).toBe(false);
          expect(err.error).toContain(flatTool);
          expect(err.error).toContain(endpoint);
          expect(err.error).toContain(`"${method}"`);
          expect(err.migration.endpoint).toBe(endpoint);
          expect(err.migration.method).toBe(method);
        }
      ),
      { numRuns: 100 }
    );
  });
});
