#!/usr/bin/env tsx
/**
 * FigCraft Content Compiler
 *
 * Reads content assets (guides, templates, prompts) from author-friendly formats
 * and generates TypeScript modules for consumption by core-mcp.
 *
 * Phase 1: Guides only (content/guides/*.md → _guides.ts)
 * Phase 2: Prompts (content/prompts/*.yaml → _prompts.ts)
 * Phase 3: Templates (content/templates/*.yaml → _templates.ts)
 *
 * Usage: npx tsx scripts/compile-content.ts
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, basename, extname } from 'node:path';
import { parse as parseYaml } from 'yaml';

const ROOT = resolve(import.meta.dirname, '..');
const GUIDES_DIR = resolve(ROOT, 'content/guides');
const PROMPTS_DIR = resolve(ROOT, 'content/prompts');
const TOOLS_OUT = resolve(ROOT, 'packages/core-mcp/src/tools');
const PROMPTS_OUT = resolve(ROOT, 'packages/core-mcp/src/prompts');

// ─── Guides ───

function compileGuides(): void {
  const files = readdirSync(GUIDES_DIR).filter(f => extname(f) === '.md').sort();

  if (files.length === 0) {
    throw new Error(`No .md files found in ${GUIDES_DIR}`);
  }

  const entries: string[] = [];

  for (const file of files) {
    const content = readFileSync(resolve(GUIDES_DIR, file), 'utf-8');
    const key = basename(file, '.md').replace(/-/g, '_').toUpperCase();
    // Escape backticks and ${} in template literals
    const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
    entries.push(`  ${key}: \`${escaped}\`,`);
  }

  const output = `// Auto-generated by scripts/compile-content.ts — DO NOT EDIT
// Source: content/guides/*.md

export const GUIDES: Record<string, string> = {
${entries.join('\n')}
};
`;

  writeFileSync(resolve(TOOLS_OUT, '_guides.ts'), output);
  console.log(`✅ Compiled ${files.length} guides → packages/core-mcp/src/tools/_guides.ts`);
}

// ─── Prompts ───

interface PromptDef {
  name: string;
  description: string;
  steps: string;
}

function compilePrompts(): void {
  const files = readdirSync(PROMPTS_DIR).filter(f => extname(f) === '.yaml').sort();

  if (files.length === 0) {
    throw new Error(`No .yaml files found in ${PROMPTS_DIR}`);
  }

  const defs: PromptDef[] = [];

  for (const file of files) {
    const raw = readFileSync(resolve(PROMPTS_DIR, file), 'utf-8');
    const parsed = parseYaml(raw) as Record<string, unknown>;

    // Validate required fields
    const name = parsed.name as string;
    const description = parsed.description as string;
    const steps = parsed.steps as string;

    if (!name || !description || !steps) {
      throw new Error(`${file}: missing required fields (name, description, steps)`);
    }

    defs.push({ name, description, steps });
  }

  // Escape for TypeScript template literals
  const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

  const entries = defs.map(d =>
    `  { name: ${JSON.stringify(d.name)}, description: ${JSON.stringify(d.description)}, steps: \`${esc(d.steps.trimEnd())}\` },`
  );

  const output = `// Auto-generated by scripts/compile-content.ts — DO NOT EDIT
// Source: content/prompts/*.yaml

export interface PromptDef {
  name: string;
  description: string;
  steps: string;
}

export const PROMPT_DEFINITIONS: PromptDef[] = [
${entries.join('\n')}
];
`;

  writeFileSync(resolve(PROMPTS_OUT, '_prompts.ts'), output);
  console.log(`✅ Compiled ${files.length} prompts → packages/core-mcp/src/prompts/_prompts.ts`);
}

// ─── Templates ───

const TEMPLATES_DIR = resolve(ROOT, 'content/templates');

const REQUIRED_TEMPLATE_FIELDS = ['structure', 'keyDecisions', 'pitfalls', 'toneVariants', 'exampleParams'] as const;

function compileTemplates(): void {
  const files = readdirSync(TEMPLATES_DIR).filter(f => extname(f) === '.yaml').sort();

  if (files.length === 0) {
    throw new Error(`No .yaml files found in ${TEMPLATES_DIR}`);
  }

  const entries: string[] = [];

  for (const file of files) {
    const raw = readFileSync(resolve(TEMPLATES_DIR, file), 'utf-8');
    const parsed = parseYaml(raw) as Record<string, unknown>;
    const name = basename(file, '.yaml');

    // Validate required fields
    for (const field of REQUIRED_TEMPLATE_FIELDS) {
      if (parsed[field] === undefined || parsed[field] === null) {
        throw new Error(`${file}: missing required field "${field}"`);
      }
    }

    // Serialize the entire pattern object as JSON (preserves nested exampleParams exactly)
    entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(parsed, null, 2).replace(/\n/g, '\n  ')},`);
  }

  const output = `// Auto-generated by scripts/compile-content.ts — DO NOT EDIT
// Source: content/templates/*.yaml

export interface UiPattern {
  structure: string;
  keyDecisions: Record<string, string>;
  pitfalls: string[];
  toneVariants: Record<string, Record<string, string>>;
  exampleParams: Record<string, unknown>;
}

export const UI_PATTERNS: Record<string, UiPattern> = {
${entries.join('\n')}
};
`;

  writeFileSync(resolve(TOOLS_OUT, '_templates.ts'), output);
  console.log(`✅ Compiled ${files.length} templates → packages/core-mcp/src/tools/_templates.ts`);
}

// ─── Main ───

compileGuides();
compilePrompts();
compileTemplates();
