#!/usr/bin/env tsx
/**
 * FigCraft Content Compiler
 *
 * Reads content assets (guides, templates, prompts) from author-friendly formats
 * and generates TypeScript modules for consumption by core-mcp.
 *
 * Phase 1: Guides only (content/guides/*.md → _guides.ts)
 * Phase 2: Prompts (content/prompts/*.yaml → _prompts.ts)
 * Phase 3: Templates (content/templates/*.yaml → _templates.ts)
 *
 * Usage: npx tsx scripts/compile-content.ts
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, basename, extname } from 'node:path';
import { parse as parseYaml } from 'yaml';

const ROOT = resolve(import.meta.dirname, '..');
const GUIDES_DIR = resolve(ROOT, 'content/guides');
const PROMPTS_DIR = resolve(ROOT, 'content/prompts');
const TOOLS_OUT = resolve(ROOT, 'packages/core-mcp/src/tools');
const PROMPTS_OUT = resolve(ROOT, 'packages/core-mcp/src/prompts');

// ─── Guides ───

function compileGuides(): void {
  const files = readdirSync(GUIDES_DIR).filter(f => extname(f) === '.md').sort();

  if (files.length === 0) {
    throw new Error(`No .md files found in ${GUIDES_DIR}`);
  }

  const entries: string[] = [];

  for (const file of files) {
    const content = readFileSync(resolve(GUIDES_DIR, file), 'utf-8');
    const key = basename(file, '.md').replace(/-/g, '_').toUpperCase();
    // Escape backticks and ${} in template literals
    const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
    entries.push(`  ${key}: \`${escaped}\`,`);
  }

  const output = `// Auto-generated by scripts/compile-content.ts — DO NOT EDIT
// Source: content/guides/*.md

export const GUIDES: Record<string, string> = {
${entries.join('\n')}
};
`;

  writeFileSync(resolve(TOOLS_OUT, '_guides.ts'), output);
  console.log(`✅ Compiled ${files.length} guides → packages/core-mcp/src/tools/_guides.ts`);
}

// ─── Prompts ───

interface PromptDef {
  name: string;
  description: string;
  steps: string;
}

function compilePrompts(): void {
  const files = readdirSync(PROMPTS_DIR).filter(f => extname(f) === '.yaml').sort();

  if (files.length === 0) {
    throw new Error(`No .yaml files found in ${PROMPTS_DIR}`);
  }

  const defs: PromptDef[] = [];

  for (const file of files) {
    const raw = readFileSync(resolve(PROMPTS_DIR, file), 'utf-8');
    const parsed = parseYaml(raw) as Record<string, unknown>;

    // Validate required fields
    const name = parsed.name as string;
    const description = parsed.description as string;
    const steps = parsed.steps as string;

    if (!name || !description || !steps) {
      throw new Error(`${file}: missing required fields (name, description, steps)`);
    }

    defs.push({ name, description, steps });
  }

  // Escape for TypeScript template literals
  const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

  const entries = defs.map(d =>
    `  { name: ${JSON.stringify(d.name)}, description: ${JSON.stringify(d.description)}, steps: \`${esc(d.steps.trimEnd())}\` },`
  );

  const output = `// Auto-generated by scripts/compile-content.ts — DO NOT EDIT
// Source: content/prompts/*.yaml

export interface PromptDef {
  name: string;
  description: string;
  steps: string;
}

export const PROMPT_DEFINITIONS: PromptDef[] = [
${entries.join('\n')}
];
`;

  writeFileSync(resolve(PROMPTS_OUT, '_prompts.ts'), output);
  console.log(`✅ Compiled ${files.length} prompts → packages/core-mcp/src/prompts/_prompts.ts`);
}

// ─── Main ───

compileGuides();
compilePrompts();
