#!/usr/bin/env tsx
/**
 * FigCraft Content Compiler
 *
 * Reads content assets (guides, templates, prompts) from author-friendly formats
 * and generates TypeScript modules for consumption by core-mcp.
 *
 * Phase 1: Guides only (content/guides/*.md → _guides.ts)
 * Phase 2: Prompts (content/prompts/*.yaml → _prompts.ts)
 * Phase 3: Templates (content/templates/*.yaml → _templates.ts)
 *
 * Usage: npx tsx scripts/compile-content.ts
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, basename, extname } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const GUIDES_DIR = resolve(ROOT, 'content/guides');
const OUT_DIR = resolve(ROOT, 'packages/core-mcp/src/tools');

// ─── Guides ───

function compileGuides(): void {
  const files = readdirSync(GUIDES_DIR).filter(f => extname(f) === '.md').sort();

  if (files.length === 0) {
    throw new Error(`No .md files found in ${GUIDES_DIR}`);
  }

  const entries: string[] = [];

  for (const file of files) {
    const content = readFileSync(resolve(GUIDES_DIR, file), 'utf-8');
    const key = basename(file, '.md').replace(/-/g, '_').toUpperCase();
    // Escape backticks and ${} in template literals
    const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
    entries.push(`  ${key}: \`${escaped}\`,`);
  }

  const output = `// Auto-generated by scripts/compile-content.ts — DO NOT EDIT
// Source: content/guides/*.md

export const GUIDES: Record<string, string> = {
${entries.join('\n')}
};
`;

  writeFileSync(resolve(OUT_DIR, '_guides.ts'), output);
  console.log(`✅ Compiled ${files.length} guides → packages/core-mcp/src/tools/_guides.ts`);
}

// ─── Main ───

compileGuides();
