/**
 * Generate lint rules documentation from the Quality Engine's ALL_RULES.
 *
 * Usage: node --import tsx scripts/generate-lint-rules-doc.ts
 * Output: docs/generated/lint-rules.md
 */

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { getAvailableRules } from '../packages/quality-engine/src/engine.js';

const rules = getAvailableRules();

// Group by category
const byCategory = new Map<string, typeof rules>();
for (const rule of rules) {
  const list = byCategory.get(rule.category) ?? [];
  list.push(rule);
  byCategory.set(rule.category, list);
}

// Category display order and labels
const CATEGORY_ORDER: Array<[string, string]> = [
  ['token', 'Token Compliance'],
  ['wcag', 'WCAG Accessibility'],
  ['layout', 'Layout & Structure'],
  ['naming', 'Naming & Content'],
  ['component', 'Component'],
];

// Safety check: warn if a category exists in rules but not in CATEGORY_ORDER
const knownKeys = new Set(CATEGORY_ORDER.map(([k]) => k));
for (const cat of byCategory.keys()) {
  if (!knownKeys.has(cat)) {
    console.warn(
      `WARNING: category "${cat}" found in rules but missing from CATEGORY_ORDER — it will be omitted from the doc`,
    );
  }
}

const lines: string[] = [
  '<!-- Auto-generated by scripts/generate-lint-rules-doc.ts — do not edit manually -->',
  '',
  '# Quality Engine — Lint Rules',
  '',
  `${rules.length} rules across ${byCategory.size} categories.`,
  '',
];

// Summary table
lines.push('## Summary', '');
lines.push('| Category | Rules | Auto-fixable |');
lines.push('| --- | ---: | ---: |');
for (const [key, label] of CATEGORY_ORDER) {
  const list = byCategory.get(key);
  if (!list) continue;
  const fixable = list.filter((r) => r.autoFixable).length;
  lines.push(`| ${label} | ${list.length} | ${fixable} |`);
}
const totalFixable = rules.filter((r) => r.autoFixable).length;
lines.push(`| **Total** | **${rules.length}** | **${totalFixable}** |`);
lines.push('');

// Per-category detail tables
for (const [key, label] of CATEGORY_ORDER) {
  const list = byCategory.get(key);
  if (!list) continue;

  lines.push(`## ${label}`, '');
  lines.push('| Rule | Severity | Fix | Description |');
  lines.push('| --- | --- | :---: | --- |');

  for (const rule of list) {
    const fix = rule.autoFixable ? '✅' : '—';
    // Escape pipe characters in description
    const desc = rule.description.replace(/\|/g, '\\|');
    lines.push(`| \`${rule.name}\` | ${rule.severity} | ${fix} | ${desc} |`);
  }
  lines.push('');
}

// AI prevention hints (for contributors)
const rulesWithHints = rules.filter((r) => r.ai?.preventionHint);
if (rulesWithHints.length > 0) {
  lines.push('## AI Prevention Hints', '');
  lines.push('These hints are injected into AI prompts to prevent violations during creation.', '');
  lines.push('| Rule | Hint |');
  lines.push('| --- | --- |');
  for (const rule of rulesWithHints) {
    const hint = rule.ai!.preventionHint.replace(/\|/g, '\\|');
    lines.push(`| \`${rule.name}\` | ${hint} |`);
  }
  lines.push('');
}

// Severity legend
lines.push(
  '## Severity Levels',
  '',
  '| Level | Meaning |',
  '| --- | --- |',
  '| error | Breakage that must be fixed |',
  '| unsafe | Layout issues that cause visual bugs |',
  '| heuristic | Best-practice violations detected by tooling |',
  '| style | Cosmetic / naming preferences |',
  '| verbose | WCAG AAA & enhancement checks (excluded by default) |',
);

const outputPath = path.join('docs', 'generated', 'lint-rules.md');
await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, `${lines.join('\n')}\n`, 'utf-8');
console.log(`Lint rules doc written to ${outputPath} (${rules.length} rules)`);
