// Auto-generated by scripts/compile-content.ts — DO NOT EDIT
// Source: content/prompts/*.yaml

export interface PromptDef {
  name: string;
  description: string;
  steps: string;
}

export const PROMPT_DEFINITIONS: PromptDef[] = [
  { name: "auto-fix", description: "Guide: Auto-fix all fixable lint violations on the current page.", steps: `Help me auto-fix design violations. Follow these steps:
1. Call load_toolset({ names: "lint" }) to enable granular lint tools
2. Run lint_check on the current page/selection
3. Show summary of violations
4. Filter to only autoFixable violations
5. Confirm with me before applying fixes
6. Run lint_fix with the fixable violations
7. Re-run lint_check to verify fixes were applied
8. Report any remaining violations that need manual attention` },
  { name: "compare-spec", description: "Guide: Compare Figma Library variables with DTCG spec tokens.", steps: `Help me compare my Figma variables against the DTCG spec. Follow these steps:
1. Ask for the DTCG JSON file path
2. Call load_toolset({ names: "tokens" }) to enable token tools
3. Use diff_tokens to compare
4. Categorize differences: in-sync, dtcg-ahead, figma-ahead, missing
5. Recommend actions for each category
6. Ask if I want to sync to resolve differences` },
  { name: "document-components", description: "Guide: Generate documentation for all components on the current page.", steps: `Help me generate documentation for the components in this Figma file. Follow these steps:

1. Call load_toolset({ names: "components-advanced" }) to enable component audit tools
2. Use audit_components to scan all components on the current page
3. For each component, use components(method: "get") and components(method: "list_properties") to get full details
4. Generate a structured documentation entry for each component:

   ## ComponentName
   **Description:** (from component description, or "No description")
   **Dimensions:** W × H
   **Properties:**
   | Name | Type | Default | Options |
   |------|------|---------|---------|
   | ... | BOOLEAN/TEXT/VARIANT/INSTANCE_SWAP | ... | (variant options if applicable) |

   **Usage:** Brief guidance on when/how to use this component
   **Variants:** List variant combinations if it's a component set

5. Flag any issues found during audit (missing descriptions, unexposed text, etc.)
6. Output the complete documentation in Markdown format
7. Suggest improvements to component structure based on audit findings` },
  { name: "generate-element", description: "Guide: Generate a design element with high design quality. Applies Design Guardian rules (with library) or Design Creator rules (without library).", steps: `Help me create a design element with high design quality. Follow the Think → Gather → Propose → Confirm → Query → Create → Check workflow:

## Think
1. Call get_mode to verify plugin connection and get designContext (includes libraryComponents or localComponents if available)
2. Based on the result, determine which mode you are in:
   - If selectedLibrary is set → Design Guardian mode. Key rules are in _workflow.designPreflight. For detailed rules on a specific area, call get_design_guidelines(category).
   - If no selectedLibrary → Design Creator mode. Key rules are in _workflow.designPreflight. For detailed rules on a specific area, call get_design_guidelines(category).

## Gather
3. Collect key preferences from the user in ONE message. Check what the user already provided, and ask ONLY for what's missing.
   Also check _workflow.searchBehavior to know whether search_design_system is available.
   Match the user's language. Present as a short checklist, not a wall of text.

   --- IF selectedLibrary is set (Design Guardian mode) ---
   Ask for (skip any already answered):
   a. **UI type** — if not clear from the request (e.g. "design a page" is vague; "login page" is clear). Provide 3–4 examples.
   b. **Platform** — Web, iOS, or Android? (affects touch targets, safe areas, conventions)
   c. **Library tone** — Do not ask the user. Infer from designContext and libraryComponents (corner radius patterns, color token naming, variant options). State the inferred tone in Propose.
   Language/region can be inferred from the user's message language — no need to ask unless ambiguous.
   After language is confirmed, load get_creation_guide(topic:"ux-writing") for UI copy conventions with language-specific rules.

   --- IF no selectedLibrary (Design Creator mode) ---
   Ask for (skip any already answered):
   a. **UI type** — if not clear from the request. Provide 3–4 examples.
   b. **Platform** — Web, iOS, or Android?
   c. **Style tone** — provide 4–5 options: Minimal / Elegant / Warm / Bold / Rich (or let user describe freely)
   Language/region can be inferred from the user's message language — no need to ask unless ambiguous.

   MERGE SHORTCUT: If ALL items are already clear from the user's request, skip Gather entirely and go directly to Propose.
   Language/region can be inferred from the user's message language if not explicitly stated — no need to ask.
   After language is confirmed, load get_creation_guide(topic:"ux-writing") for UI copy conventions with language-specific rules.
   **STOP and wait for answers.** Then proceed to Propose.

## Propose
4. Based on the gathered preferences, output a concrete design plan draft.

Start the draft by stating your understanding of the context:
> "I understand you need [what], for [audience/platform], with a [tone] feel."
This gives the user a chance to correct any wrong assumptions before you detail the plan.

Apply the mode-specific design rules from _workflow.designPreflight (already loaded via get_mode).
For detailed guidance on specific areas, call get_design_guidelines with a category (color, typography, spacing, composition, content, accessibility).
Do NOT load the full rule set upfront — use targeted category queries only when needed.

5. End the proposal with: "Want me to adjust anything, or should I go ahead?"
6. **STOP HERE.** Wait for the user to approve or request changes.

## Confirm
7. If the user requests changes, revise the plan and present again. If approved, proceed.

## Query (library/local mode with components)
8. Check get_mode response for available components:
   - Library mode: libraryComponents lists shared library component sets (use componentSetKey/componentKey).
   - Local mode: localComponents lists current file component sets (use componentId).
   Use containingFrame to verify component category — property names like "Placeholder"/"Size" appear on many types (Avatar, Input, Card).
   For full variant details, call search_design_system(query) or components(method: "list_properties").
   Skip this step entirely in Design Creator mode (no library selected).

## Create
9. Use create_frame + children (declarative) to build the design.
   create_frame has an Opinion Engine that auto-infers layoutMode, sizing, and FILL ordering.
   Token auto-binding happens automatically in library mode (colors, spacing, typography).
   For complex parameters, use dryRun:true first to preview inferences.
   For multi-screen flows, call get_creation_guide(topic:"multi-screen") for architecture rules.
   For complex layouts, call get_creation_guide(topic:"layout") for structural rules.
   For icons: use icon_search(query) to find icons, then icon_create to place them.
   For remote/stock images: use image_search(query), then create_frame with imageUrl.
   For local images: use create_image_frame_from_local for new frames, or fill_existing_image_from_local when editing an existing node.
   After creation, verify with export_image and run lint_fix_all.

## Check
10. Quick self-review before lint — verify:
    - Every container has layoutMode (HORIZONTAL or VERTICAL) and at least one child
    - Buttons are auto-layout frames with centered text, height ≥ 48px, padding ≥ 12px
    - Input fields have stroke, corner radius, padding, and placeholder text
    - No text overflow or truncation — text fits within parent
    - Mobile screens use correct dimensions (iOS 402×874, Android 412×915)
    - Every frame has a descriptive name (no "Frame 1")
    Fix violations immediately with nodes(method: "update").
11. Run lint_fix_all to auto-check all {{PREVENTION_CHECKLIST_COUNT}} quality rules and fix remaining issues.` },
  { name: "lint-page", description: "Guide: Lint the current Figma page for design compliance.", steps: `Help me check the current page for design compliance. Follow these steps in sequence without stopping:
1. Use ping to verify plugin connection
2. Use lint_fix_all to check and auto-fix violations in one step
3. Summarize: total checked / violations found / auto-fixed / remaining
4. For remaining violations, explain what needs manual attention` },
  { name: "prototype-flow", description: "Guide: Analyze prototype interactions and generate flow documentation.", steps: `Help me analyze the prototype flow in this Figma file. Follow these steps:
1. Call load_toolset({ names: "prototype" }) to enable prototype interaction tools
2. Use analyze_prototype_flow to scan the current page (format: "all")
3. Present the summary: total screens, interactions, entry points, dead ends, loops
4. Show the Mermaid flow diagram
5. Highlight any issues:
   - Dead ends (screens with no way out)
   - Missing back navigation
   - Loops that might trap users
   - Screens with only one trigger type (consider adding hover/keyboard alternatives)
6. If requested, output the full Markdown documentation
7. Suggest improvements to the prototype flow` },
  { name: "review-design", description: "Guide: Review existing Figma designs against design quality rules. Outputs structured violation report with fixes.", steps: `Help me review the design quality of existing Figma elements. Execute ALL steps in sequence without stopping:

1. Call ping to verify plugin connection
2. Call get_mode to determine the current mode and selected library
3. Use get_selection to get selected nodes, or fall back to get_current_page (maxDepth=2) children
4. Use nodes(method: "get") on each target node to read properties (fills, fontSize, fontName, spacing, dimensions, cornerRadius, etc.)

5. Apply the appropriate design rules based on mode:

--- IF selectedLibrary is set (Design Guardian rules) ---
Use get_design_guidelines() for Design Guardian rules, or call get_design_guidelines(category) for specific areas.

Review focus:
- Are colors/fonts bound to library tokens? Flag hardcoded values when tokens exist.
- Are gradients/shadows refined or cheap-looking?
- Is there a clear visual hierarchy and focal point?
- Is composition intentional (asymmetry where appropriate, no uniform grids)?
- Is spacing consistent and using library tokens (or 4px-grid spacing scale)?
- Are text contents realistic and contextually appropriate (not placeholder)?
- Are icons consistent in style (outline/filled/duotone not mixed)?
- Are shadow levels consistent and within ≤ 3 tiers?
- Does the node structure complexity match the design tone?
- Are accessibility standards met?

--- IF no selectedLibrary (Design Creator rules) ---
Use get_design_guidelines() for Design Creator rules, or call get_design_guidelines(category) for specific areas.

Review focus:
- Is there a clear design intent (not just AI defaults)?
- Do color choices serve a purpose?
- Are fonts chosen with intention (not just Inter)?
- Is spacing rhythmic, consistent, and based on a clear base unit?
- Is there a clear visual focal point? Is composition intentional (not just centered symmetry)?
- Are text contents realistic and contextually appropriate (not placeholder)?
- Are icons consistent in style (outline/filled/duotone not mixed)?
- Are shadow levels consistent and within ≤ 3 tiers?
- Does the node structure complexity match the design tone?
- Are accessibility standards met?

6. Output a structured report for each violation:
   - violation: quote the specific node, property, and value
   - why: one sentence explaining why this is a problem
   - fix: concrete fix suggestion with MCP tool call example

7. Summarize: X passed / Y violations / Z auto-fixable
8. Run lint_fix_all to auto-fix what's possible, then report remaining violations` },
  { name: "sync-tokens", description: "Guide: Sync DTCG design tokens to Figma variables and styles.", steps: `Help me sync design tokens to Figma. Follow these steps:
1. Ask for the DTCG JSON file path
2. Call load_toolset({ names: "tokens" }) to enable token tools
3. Use list_tokens to preview what will be synced
4. Use diff_tokens to check current state vs DTCG
5. Use sync_tokens to push changes
6. Report the sync result (created/updated/skipped/failed)

If there are composite tokens (typography, shadow), explain that they become Figma Styles (not Variables).` },
  { name: "text-replacement", description: "Guide: Bulk replace text content in a Figma design (localization, data filling, content updates).", steps: `Help me replace text content across a Figma design. Follow this workflow:

## 1. Scan
- Use \`text_scan\` on the target frame/page to discover all text nodes
- Categorize by role: headings, body, labels, placeholders, CTAs

## 2. Chunk
- Group text nodes by proximity (same parent frame = one chunk)
- For large designs (>30 text nodes), process in chunks of 10-15 nodes
- Prioritize: headings first, then body text, then labels/CTAs

## 3. Replace (per chunk)
- Use \`text(method:"set_content")\` to update each node
- For content that may not fit: check if the text node has a fixed width — keep replacement text similar in length or shorter
- After replacing each chunk, use \`export_image(scale:2)\` on the parent frame to verify visually

## 4. Verify
- After each chunk: confirm text fits containers, no truncation, no overflow
- If issues found: adjust text or container width before proceeding

## 5. Final QA
- Run \`lint_fix_all\` to catch any text overflow or layout issues introduced
- \`export_image(scale:1)\` on the full design for final review

Export scale guidelines:
- Overview (full page): scale 1
- Section check: scale 2
- Detail check (individual text): scale 3` },
];
