/**
 * AUTO-GENERATED by scripts/compile-schema.ts — DO NOT EDIT
 *
 * Tool response contracts and example payloads derived from schema/tools.yaml.
 * These are intended for docs, tests, and future prompt/runtime validation work.
 *
 * Re-generate: npm run schema
 */

import { z } from 'zod';

const NodeRoleSharedSchema: z.ZodTypeAny = z.lazy(() => z.enum(['screen', 'header', 'hero', 'nav', 'content', 'list', 'row', 'stats', 'card', 'form', 'field', 'input', 'button', 'footer', 'actions', 'social_row', 'system_bar']));
const NodeTypeSharedSchema: z.ZodTypeAny = z.lazy(() => z.enum(['frame', 'text', 'rectangle', 'ellipse', 'line', 'vector', 'instance']));
const NodeSpecSharedSchema: z.ZodTypeAny = z.lazy(() => z.object({
      type: NodeTypeSharedSchema,
      name: z.string().optional(),
      role: NodeRoleSharedSchema.optional(),
      props: z.record(z.unknown()).optional(),
      children: z.array(NodeSpecSharedSchema).optional(),
    }));

export const GENERATED_TOOL_RESPONSE_SCHEMAS: Record<string, z.ZodTypeAny> = {
  'ping': z.object({
      connected: z.boolean(),
      latency: z.string().optional(),
      serverVersion: z.string().optional(),
      pluginVersion: z.string().optional(),
      versionWarning: z.string().optional(),
      error: z.string().optional(),
      _hint: z.string().optional(),
      result: z.record(z.unknown()).optional(),
    }),
  'get_mode': z.object({
      connected: z.boolean(),
      latency: z.string().optional(),
      versionWarning: z.string().optional(),
      mode: z.enum(['library', 'spec']).optional(),
      selectedLibrary: z.string().optional(),
      designContext: z.record(z.unknown()).optional(),
      libraryComponents: z.array(z.object({
          key: z.string(),
          name: z.string(),
          description: z.string(),
        })).optional(),
      libraryComponentsError: z.string().optional(),
      libraryComponentsUnavailable: z.boolean().optional(),
      _hint: z.string().optional(),
      error: z.string().optional(),
    }),
  'set_mode': z.object({
      mode: z.enum(['library', 'spec']),
      description: z.string(),
    }),
  'join_channel': z.object({
      ok: z.boolean(),
      channel: z.string().optional(),
      message: z.string().optional(),
      error: z.string().optional(),
    }),
  'get_channel': z.object({
      channel: z.string(),
      connected: z.boolean(),
    }),
  'get_node_info': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      x: z.number().optional(),
      y: z.number().optional(),
      width: z.number().optional(),
      height: z.number().optional(),
      children: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
        })).optional(),
      _error: z.string().optional(),
      _sizeKB: z.number().optional(),
      _limitKB: z.number().optional(),
      method: z.string().optional(),
      warning: z.string().optional(),
      hints: z.array(z.string()).optional(),
      _preview: z.string().optional(),
    }),
  'get_current_page': z.object({
      id: z.string(),
      name: z.string(),
      childCount: z.number(),
      returnedNodes: z.number(),
      truncated: z.boolean().optional(),
      nodes: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
        })),
      _error: z.string().optional(),
      _sizeKB: z.number().optional(),
      _limitKB: z.number().optional(),
      method: z.string().optional(),
      warning: z.string().optional(),
      hints: z.array(z.string()).optional(),
      _preview: z.string().optional(),
    }),
  'get_document_info': z.object({
      name: z.string(),
      currentPage: z.string(),
      pages: z.array(z.object({
          id: z.string(),
          name: z.string(),
          childCount: z.number(),
        })),
    }),
  'get_selection': z.object({
      count: z.number(),
      nodes: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
        })),
    }),
  'search_nodes': z.object({
      count: z.number(),
      nodes: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
        })),
      _error: z.string().optional(),
      _sizeKB: z.number().optional(),
      _limitKB: z.number().optional(),
      method: z.string().optional(),
      warning: z.string().optional(),
      hints: z.array(z.string()).optional(),
      _preview: z.string().optional(),
    }),
  'list_fonts': z.object({
      family: z.string().optional(),
      styles: z.array(z.string()).optional(),
      count: z.number().optional(),
      families: z.array(z.string()).optional(),
      total: z.number().optional(),
    }),
  'create_document': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
      created: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
        })).optional(),
      truncated: z.boolean().optional(),
      warnings: z.array(z.string()).optional(),
      errors: z.array(z.object({
          index: z.number(),
          name: z.string().optional(),
          type: z.string(),
          error: z.string(),
        })).optional(),
      postCreateLint: z.record(z.unknown()).optional(),
    }),
  'create_screen': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
      failedStage: z.string().optional(),
      screenRootId: z.string().optional(),
      screen: z.record(z.unknown()).optional(),
      canvasSection: z.record(z.unknown()).optional(),
      sections: z.array(z.object({
          index: z.number(),
          name: z.string().optional(),
          ok: z.boolean(),
          result: z.record(z.unknown()).optional(),
        })).optional(),
      pipelineStages: z.array(z.object({
          stage: z.string(),
          ok: z.boolean(),
          createdCount: z.number(),
          nodeIds: z.array(z.string()).optional(),
          lint: z.record(z.unknown()).optional(),
          warningCount: z.number().optional(),
          patchCallCount: z.number().optional(),
          patchNodeCount: z.number().optional(),
          patchRules: z.array(z.string()).optional(),
          structuralErrors: z.array(z.record(z.unknown())).optional(),
          debugStats: z.record(z.unknown()).optional(),
        })).optional(),
      pipelineSummary: z.record(z.unknown()).optional(),
      finalLint: z.record(z.unknown()).optional(),
    }),
  'create_frame': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      x: z.number().optional(),
      y: z.number().optional(),
      width: z.number().optional(),
      height: z.number().optional(),
      layoutMode: z.string().optional(),
      itemSpacing: z.number().optional(),
      autoBound: z.string().optional(),
      colorHint: z.string().optional(),
      warnings: z.array(z.string()).optional(),
    }),
  'create_text': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      x: z.number().optional(),
      y: z.number().optional(),
      width: z.number().optional(),
      height: z.number().optional(),
      characters: z.string().optional(),
      fontSize: z.number().optional(),
      autoBound: z.record(z.unknown()).optional(),
      colorHint: z.string().optional(),
    }),
  'patch_nodes': z.object({
      results: z.array(z.object({
          nodeId: z.string(),
          ok: z.boolean(),
          error: z.string().optional(),
        })),
    }),
  'delete_nodes': z.object({
      results: z.array(z.object({
          nodeId: z.string(),
          ok: z.boolean(),
          error: z.string().optional(),
        })),
    }),
  'set_text_content': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  'clone_node': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      x: z.number().optional(),
      y: z.number().optional(),
      width: z.number().optional(),
      height: z.number().optional(),
    }),
  'insert_child': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  'list_components': z.object({
      count: z.number(),
      components: z.array(z.object({
          id: z.string(),
          name: z.string(),
          description: z.string().optional(),
          key: z.string().optional(),
        })),
    }),
  'list_library_components': z.object({
      count: z.number(),
      components: z.array(z.object({
          key: z.string(),
          name: z.string(),
          description: z.string().optional(),
        })),
    }),
  'list_component_properties': z.object({
      properties: z.array(z.object({
          key: z.string(),
          type: z.string(),
          defaultValue: z.unknown().optional(),
          variantOptions: z.array(z.string()).optional(),
        })),
    }),
  'get_component': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number().optional(),
      height: z.number().optional(),
      description: z.string().optional(),
      key: z.string().optional(),
      children: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
        })).optional(),
      componentPropertyDefinitions: z.record(z.unknown()).optional(),
    }),
  'create_instance': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      x: z.number().optional(),
      y: z.number().optional(),
      width: z.number().optional(),
      height: z.number().optional(),
      componentPropertyReferences: z.record(z.string()).optional(),
      error: z.string().optional(),
    }),
  'lint_fix_all': z.object({
      lint: z.object({
        total: z.number(),
        pass: z.number(),
        violations: z.number(),
        bySeverity: z.record(z.unknown()).optional(),
      }),
      fixable: z.number(),
      fixed: z.number(),
      fixFailed: z.number(),
      remaining: z.number(),
    }),
  'set_current_page': z.object({
      ok: z.boolean(),
      pageId: z.string().optional(),
      pageName: z.string().optional(),
      error: z.string().optional(),
    }),
  'export_image': z.object({
      format: z.string(),
      size: z.number(),
      base64: z.string(),
    }),
  'save_version_history': z.object({
      ok: z.boolean(),
      title: z.string(),
      description: z.string(),
    }),
  'set_selection': z.object({
      ok: z.boolean(),
      selectedCount: z.number(),
      notFound: z.array(z.string()),
    }),
  'create_rectangle': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      x: z.number().optional(),
      y: z.number().optional(),
      width: z.number().optional(),
      height: z.number().optional(),
      cornerRadius: z.unknown().optional(),
      autoBound: z.string().optional(),
      colorHint: z.string().optional(),
    }),
  'create_ellipse': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      x: z.number().optional(),
      y: z.number().optional(),
      width: z.number().optional(),
      height: z.number().optional(),
      autoBound: z.string().optional(),
      colorHint: z.string().optional(),
    }),
  'create_vector': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      x: z.number().optional(),
      y: z.number().optional(),
      width: z.number().optional(),
      height: z.number().optional(),
    }),
  'set_image_fill': z.object({
      ok: z.boolean(),
      imageHash: z.string().optional(),
      error: z.string().optional(),
    }),
  'list_variables': z.object({
      count: z.number(),
      variables: z.array(z.object({
          id: z.string(),
          name: z.string(),
          resolvedType: z.string(),
          description: z.string().optional(),
          collectionId: z.string(),
          collectionName: z.string(),
          scopes: z.array(z.string()),
          valuesByMode: z.record(z.unknown()),
        })),
    }),
  'get_variable': z.object({
      id: z.string(),
      name: z.string(),
      resolvedType: z.string(),
      description: z.string().optional(),
      collectionId: z.string(),
      collectionName: z.string().optional(),
      scopes: z.array(z.string()),
      codeSyntax: z.unknown().optional(),
      valuesByMode: z.record(z.unknown()),
      error: z.string().optional(),
    }),
  'list_collections': z.array(z.object({
          id: z.string(),
          name: z.string(),
          modes: z.array(z.object({
          modeId: z.string(),
          name: z.string(),
        })),
          variableCount: z.number(),
        })),
  'get_node_variables': z.object({
      nodeId: z.string(),
      bindings: z.record(z.unknown()),
      error: z.string().optional(),
    }),
  'set_variable_binding': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  'set_explicit_variable_mode': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  'create_variable': z.object({
      id: z.string(),
      name: z.string(),
      resolvedType: z.string(),
      error: z.string().optional(),
    }),
  'update_variable': z.object({
      ok: z.boolean(),
      id: z.string().optional(),
      error: z.string().optional(),
    }),
  'delete_variable': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  'create_collection': z.object({
      id: z.string(),
      name: z.string(),
      modes: z.array(z.object({
          modeId: z.string(),
          name: z.string(),
        })),
    }),
  'delete_collection': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  'rename_collection': z.object({
      ok: z.boolean(),
      id: z.string().optional(),
      name: z.string().optional(),
      error: z.string().optional(),
    }),
  'add_collection_mode': z.object({
      ok: z.boolean(),
      modeId: z.string().optional(),
      name: z.string().optional(),
      error: z.string().optional(),
    }),
  'rename_collection_mode': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  'remove_collection_mode': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  'create_variable_alias': z.object({
      ok: z.boolean(),
      variableId: z.string().optional(),
      aliasTo: z.string().optional(),
      error: z.string().optional(),
    }),
  'export_variables': z.object({
      count: z.number(),
      variables: z.array(z.object({
          path: z.string(),
          type: z.string(),
          valuesByMode: z.record(z.unknown()),
          description: z.string().optional(),
          scopes: z.array(z.string()).optional(),
          aliasOf: z.record(z.string()).optional(),
        })),
    }),
  'batch_create_variables': z.object({
      created: z.number(),
      skipped: z.number(),
      failed: z.number(),
      errors: z.array(z.object({
          name: z.string(),
          error: z.string(),
        })),
      collectionId: z.string(),
    }),
  'list_tokens': z.object({
      total: z.number(),
      showing: z.number(),
      tokens: z.array(z.object({
          path: z.string(),
          type: z.string(),
          value: z.unknown(),
          description: z.string().optional(),
          extensions: z.record(z.unknown()).optional(),
        })),
    }),
  'sync_tokens': z.object({
      variables: z.object({
        created: z.number(),
        updated: z.number(),
        skipped: z.number(),
        failed: z.number(),
        failures: z.array(z.record(z.unknown())),
      }),
      styles: z.object({
        created: z.number(),
        updated: z.number(),
        skipped: z.number(),
        failed: z.number(),
        failures: z.array(z.record(z.unknown())),
      }),
      totalTokens: z.number(),
    }),
  'sync_tokens_multi_mode': z.object({
      collectionId: z.string(),
      modes: z.array(z.object({
          modeId: z.string(),
          name: z.string(),
        })),
      results: z.record(z.unknown()),
    }),
  'diff_tokens': z.object({
      summary: z.object({
        inSync: z.number(),
        dtcgAhead: z.number(),
        missingInFigma: z.number(),
        missingInDtcg: z.number(),
      }),
      diff: z.array(z.object({
          path: z.string(),
          status: z.string(),
          dtcgValue: z.unknown().optional(),
          figmaValue: z.unknown().optional(),
        })),
    }),
  'reverse_sync_tokens': z.object({
      ok: z.boolean(),
      filePath: z.string(),
      tokenCount: z.number(),
    }),
  'cache_tokens': z.object({
      cached: z.number(),
      name: z.string(),
    }),
  'list_cached_tokens': z.object({
      entries: z.array(z.string()),
    }),
  'delete_cached_tokens': z.object({
      ok: z.boolean(),
    }),
  'scan_styles': z.object({
      paint: z.array(z.object({
          id: z.string(),
          name: z.string(),
          paints: z.number(),
        })),
      text: z.array(z.object({
          id: z.string(),
          name: z.string(),
          fontSize: z.number(),
          fontName: z.unknown().optional(),
        })),
      effect: z.array(z.object({
          id: z.string(),
          name: z.string(),
          effects: z.number(),
        })),
      summary: z.object({
        paintCount: z.number(),
        textCount: z.number(),
        effectCount: z.number(),
      }),
    }),
  'export_tokens': z.record(z.unknown()),
  'diff_styles': z.object({
      diff: z.array(z.object({
          path: z.string(),
          status: z.string(),
          dtcgValue: z.unknown().optional(),
          figmaValue: z.unknown().optional(),
        })),
      total: z.number(),
      error: z.string().optional(),
    }),
  'list_styles': z.object({
      count: z.number(),
      styles: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
          description: z.string().optional(),
          paints: z.array(z.record(z.unknown())).optional(),
          fontName: z.unknown().optional(),
          fontSize: z.number().optional(),
          letterSpacing: z.unknown().optional(),
          lineHeight: z.unknown().optional(),
          textCase: z.string().optional(),
          textDecoration: z.string().optional(),
          effects: z.array(z.record(z.unknown())).optional(),
        })),
    }),
  'get_style': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      description: z.string().optional(),
      paints: z.array(z.record(z.unknown())).optional(),
      fontName: z.unknown().optional(),
      fontSize: z.number().optional(),
      letterSpacing: z.unknown().optional(),
      lineHeight: z.unknown().optional(),
      textCase: z.string().optional(),
      textDecoration: z.string().optional(),
      effects: z.array(z.record(z.unknown())).optional(),
      error: z.string().optional(),
    }),
  'sync_styles': z.object({
      created: z.number(),
      updated: z.number(),
      skipped: z.number(),
      failed: z.number(),
      failures: z.array(z.object({
          path: z.string(),
          error: z.string(),
        })),
    }),
  'create_paint_style': z.object({
      id: z.string(),
      name: z.string(),
    }),
  'delete_style': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  'update_paint_style': z.object({
      id: z.string(),
      name: z.string(),
      error: z.string().optional(),
    }),
  'update_text_style': z.object({
      id: z.string(),
      name: z.string(),
      fontSize: z.number().optional(),
      error: z.string().optional(),
    }),
  'update_effect_style': z.object({
      id: z.string(),
      name: z.string(),
      error: z.string().optional(),
    }),
  'register_library_styles': z.object({
      ok: z.boolean(),
      registered: z.object({
        textStyles: z.number(),
        paintStyles: z.number(),
        effectStyles: z.number(),
      }),
    }),
  'get_registered_styles': z.object({
      textStyles: z.array(z.object({
          key: z.string(),
          name: z.string(),
          fontSize: z.number(),
          fontFamily: z.string(),
          fontWeight: z.string(),
        })),
      paintStyles: z.array(z.object({
          key: z.string(),
          name: z.string(),
          hex: z.string(),
        })),
      effectStyles: z.array(z.object({
          key: z.string(),
          name: z.string(),
          effectType: z.string(),
        })),
      _loaded: z.object({
        text: z.number(),
        paint: z.number(),
        effect: z.number(),
      }).optional(),
    }),
  'create_component': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
    }),
  'create_component_set': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
    }),
  'update_component': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
    }),
  'delete_component': z.object({
      ok: z.boolean(),
    }),
  'swap_instance': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
      error: z.string().optional(),
    }),
  'detach_instance': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
      error: z.string().optional(),
    }),
  'reset_instance_overrides': z.object({
      ok: z.boolean(),
    }),
  'get_instance_overrides': z.object({
      nodeId: z.string(),
      nodeName: z.string(),
      properties: z.array(z.object({
          key: z.string(),
          type: z.string(),
          value: z.unknown().optional(),
        })),
    }),
  'set_instance_overrides': z.object({
      succeeded: z.number(),
      failed: z.number(),
    }),
  'add_component_property': z.object({
      ok: z.boolean(),
      properties: z.array(z.string()).optional(),
      error: z.string().optional(),
    }),
  'update_component_property': z.object({
      ok: z.boolean(),
      properties: z.array(z.string()).optional(),
      error: z.string().optional(),
    }),
  'delete_component_property': z.object({
      ok: z.boolean(),
      properties: z.array(z.string()).optional(),
      error: z.string().optional(),
    }),
  'audit_components': z.object({
      summary: z.object({
        totalComponents: z.number(),
        totalIssues: z.number(),
      }),
      components: z.array(z.record(z.unknown())),
      issues: z.array(z.object({
          nodeId: z.string(),
          name: z.string(),
          issue: z.string(),
        })),
    }),
  'list_library_collections': z.array(z.object({
          key: z.string(),
          name: z.string(),
          libraryName: z.string(),
        })),
  'list_library_variables': z.object({
      count: z.number(),
      variables: z.array(z.object({
          key: z.string(),
          name: z.string(),
          resolvedType: z.string(),
        })),
    }),
  'import_library_variable': z.object({
      id: z.string(),
      name: z.string(),
      resolvedType: z.string(),
      description: z.string().optional(),
      key: z.string(),
    }),
  'list_library_styles': z.object({
      count: z.number(),
      styles: z.array(z.object({
          key: z.string(),
          file_key: z.string(),
          node_id: z.string(),
          style_type: z.string(),
          name: z.string(),
          description: z.string().optional(),
        })),
    }),
  'get_library_style_details': z.object({
      count: z.number(),
      styles: z.array(z.object({
          key: z.string(),
          file_key: z.string(),
          node_id: z.string(),
          style_type: z.string(),
          name: z.string(),
          description: z.string().optional(),
          properties: z.record(z.unknown()),
        })),
    }),
  'sync_library_styles': z.object({
      ok: z.boolean(),
      discovered: z.object({
        total: z.number(),
        text: z.number(),
        fill: z.number(),
        effect: z.number(),
      }),
      diff: z.record(z.unknown()),
      registered: z.unknown(),
    }),
  'import_library_style': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      key: z.string(),
      description: z.string().optional(),
    }),
  'create_line': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
    }),
  'create_star': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
    }),
  'create_polygon': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
    }),
  'create_section': z.object({
      id: z.string(),
      name: z.string(),
      x: z.number(),
      y: z.number(),
    }),
  'flatten_node': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
      error: z.string().optional(),
    }),
  'boolean_operation': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
    }),
  'get_annotations': z.object({
      nodes: z.array(z.object({
          nodeId: z.string(),
          nodeName: z.string(),
          annotations: z.array(z.record(z.unknown())),
        })),
      count: z.number(),
    }),
  'set_annotation': z.object({
      ok: z.boolean(),
      nodeId: z.string(),
      count: z.number(),
    }),
  'set_multiple_annotations': z.object({
      succeeded: z.number(),
      failed: z.number(),
      results: z.array(z.record(z.unknown())),
    }),
  'clear_annotations': z.object({
      cleared: z.number(),
    }),
  'get_reactions': z.object({
      nodes: z.array(z.object({
          nodeId: z.string(),
          nodeName: z.string(),
          reactions: z.array(z.record(z.unknown())),
        })),
      count: z.number(),
    }),
  'analyze_prototype_flow': z.object({
      graph: z.record(z.unknown()).optional(),
      mermaid: z.string().optional(),
      markdown: z.string().optional(),
      message: z.string().optional(),
      hint: z.string().optional(),
    }),
  'lint_check': z.object({
      summary: z.object({
        total: z.number(),
        pass: z.number(),
        violations: z.number(),
      }),
      categories: z.array(z.object({
          rule: z.string(),
          count: z.number(),
          nodes: z.array(z.record(z.unknown())),
        })),
      pagination: z.record(z.unknown()).optional(),
      scope: z.record(z.unknown()).optional(),
    }),
  'lint_fix': z.object({
      fixed: z.number(),
      failed: z.number(),
      errors: z.array(z.object({
          nodeId: z.string(),
          error: z.string(),
        })),
    }),
  'lint_rules': z.object({
      rules: z.array(z.object({
          name: z.string(),
          description: z.string(),
          category: z.string(),
          severity: z.string(),
        })),
    }),
  'compliance_report': z.object({
      overallScore: z.number(),
      lint: z.record(z.unknown()),
      components: z.record(z.unknown()),
    }),
  'figma_login': z.object({
      ok: z.boolean(),
      url: z.string(),
      message: z.string(),
    }),
  'figma_logout': z.object({
      ok: z.boolean(),
      message: z.string(),
    }),
  'figma_auth_status': z.object({
      method: z.string(),
      expiresAt: z.number().optional(),
    }),
  'create_page': z.object({
      id: z.string(),
      name: z.string(),
    }),
  'rename_page': z.object({
      ok: z.boolean(),
      id: z.string().optional(),
      name: z.string().optional(),
      error: z.string().optional(),
    }),
  'delete_node': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
};

export const GENERATED_TOOL_RESPONSE_EXAMPLES: Record<string, unknown[]> = {
  'ping': [
    {
      "connected": true,
      "latency": "18ms",
      "serverVersion": "0.1.0",
      "pluginVersion": "0.1.0",
      "_hint": "Connection OK. Proceed with your task — do NOT stop here.",
      "result": {
        "ok": true,
        "channel": "design-1"
      }
    },
    {
      "connected": false,
      "error": "Not connected to relay. Start the relay (npm run dev:relay) and open the Figma plugin."
    }
  ],
  'get_mode': [
    {
      "connected": true,
      "latency": "24ms",
      "mode": "library",
      "selectedLibrary": "Acme DS",
      "designContext": {
        "source": "library",
        "collections": [
          {
            "name": "Color",
            "key": "VariableCollectionId:1:2"
          }
        ]
      },
      "libraryComponents": [
        {
          "key": "component-key",
          "name": "Button / Primary",
          "description": "Primary CTA button"
        }
      ],
      "_hint": "Library mode — tokens and components loaded. NEXT: Reply to user to gather missing preferences (UI type, platform). Do NOT call any more tools. If user provided everything, reply with design proposal instead."
    },
    {
      "connected": false,
      "error": "Not connected to Figma. Open the FigCraft plugin in Figma and try again."
    }
  ],
  'set_mode': [
    {
      "mode": "library",
      "description": "Using Figma shared library as token source. Lint checks variable/style bindings."
    }
  ],
  'join_channel': [
    {
      "ok": true,
      "channel": "design-1",
      "message": "Joined channel \"design-1\". Commands will now target this document."
    }
  ],
  'get_channel': [
    {
      "channel": "design-1",
      "connected": true
    }
  ],
  'get_node_info': [
    {
      "id": "1:23",
      "name": "Login Screen",
      "type": "FRAME",
      "width": 402,
      "height": 874,
      "children": [
        {
          "id": "1:24",
          "name": "Login Form",
          "type": "FRAME"
        }
      ]
    }
  ],
  'get_current_page': [
    {
      "id": "0:1",
      "name": "Page 1",
      "childCount": 3,
      "returnedNodes": 2,
      "truncated": true,
      "nodes": [
        {
          "id": "1:10",
          "name": "Dashboard",
          "type": "FRAME"
        },
        {
          "id": "1:20",
          "name": "Settings",
          "type": "FRAME"
        }
      ]
    }
  ],
  'get_document_info': [
    {
      "name": "Acme Product",
      "currentPage": "Page 1",
      "pages": [
        {
          "id": "0:1",
          "name": "Page 1",
          "childCount": 12
        },
        {
          "id": "0:2",
          "name": "Components",
          "childCount": 48
        }
      ]
    }
  ],
  'get_selection': [
    {
      "count": 2,
      "nodes": [
        {
          "id": "1:10",
          "name": "CTA Button",
          "type": "FRAME"
        },
        {
          "id": "1:11",
          "name": "Headline",
          "type": "TEXT"
        }
      ]
    }
  ],
  'search_nodes': [
    {
      "count": 2,
      "nodes": [
        {
          "id": "1:10",
          "name": "Login Button",
          "type": "FRAME"
        },
        {
          "id": "1:11",
          "name": "Login Title",
          "type": "TEXT"
        }
      ]
    }
  ],
  'list_fonts': [
    {
      "families": [
        "Inter",
        "SF Pro Display",
        "JetBrains Mono"
      ],
      "total": 3
    },
    {
      "family": "Inter",
      "styles": [
        "Regular",
        "Medium",
        "Bold"
      ],
      "count": 3
    }
  ],
  'create_document': [
    {
      "ok": true,
      "created": [
        {
          "id": "12:34",
          "name": "Auth Screen",
          "type": "FRAME"
        }
      ],
      "postCreateLint": {
        "scopedNodeIds": [
          "12:34"
        ],
        "initial": {
          "violations": 0
        },
        "final": {
          "violations": 0
        }
      }
    },
    {
      "ok": false,
      "error": "nodes array must not be empty"
    }
  ],
  'create_screen': [
    {
      "ok": true,
      "screenRootId": "20:1",
      "screen": {
        "ok": true,
        "created": [
          {
            "id": "20:1",
            "name": "Marketing Hero",
            "type": "FRAME"
          }
        ]
      },
      "sections": [
        {
          "index": 0,
          "name": "Hero Section",
          "ok": true,
          "result": {
            "ok": true,
            "created": [
              {
                "id": "20:2",
                "name": "Hero Content",
                "type": "FRAME"
              }
            ]
          }
        }
      ],
      "pipelineStages": [
        {
          "stage": "shell",
          "ok": true,
          "createdCount": 1,
          "nodeIds": [
            "20:1"
          ],
          "warningCount": 0,
          "patchCallCount": 0,
          "patchNodeCount": 0,
          "patchRules": [],
          "structuralErrors": [],
          "debugStats": {}
        },
        {
          "stage": "section:1",
          "ok": true,
          "createdCount": 1,
          "nodeIds": [
            "20:2"
          ],
          "warningCount": 0,
          "patchCallCount": 0,
          "patchNodeCount": 0,
          "patchRules": [],
          "structuralErrors": [],
          "debugStats": {}
        }
      ],
      "pipelineSummary": {
        "stageCount": 2,
        "createdCount": 2,
        "warningCount": 0,
        "remaining": 0
      },
      "finalLint": {
        "scopedNodeIds": [
          "20:1"
        ],
        "remaining": 0
      }
    },
    {
      "ok": false,
      "error": "create_screen could not determine the created screen root"
    }
  ],
  'create_frame': [
    {
      "id": "30:1",
      "name": "Card Frame",
      "type": "FRAME",
      "x": 64,
      "y": 120,
      "width": 320,
      "height": 180,
      "layoutMode": "VERTICAL",
      "itemSpacing": 16,
      "autoBound": "surface/default"
    }
  ],
  'create_text': [
    {
      "id": "30:2",
      "name": "Hero Title",
      "type": "TEXT",
      "x": 88,
      "y": 164,
      "width": 220,
      "height": 40,
      "characters": "Ship Faster",
      "fontSize": 32,
      "autoBound": {
        "color": "text/primary",
        "typography": "style:Heading/L"
      }
    },
    {
      "id": "30:3",
      "name": "Body Copy",
      "type": "TEXT",
      "characters": "Build polished screens with AI.",
      "fontSize": 16
    }
  ],
  'patch_nodes': [
    {
      "results": [
        {
          "nodeId": "30:1",
          "ok": true
        },
        {
          "nodeId": "30:2",
          "ok": false,
          "error": "Node not found"
        }
      ]
    }
  ],
  'delete_nodes': [
    {
      "results": [
        {
          "nodeId": "30:1",
          "ok": true
        },
        {
          "nodeId": "999:1",
          "ok": false,
          "error": "Node not found"
        }
      ]
    }
  ],
  'set_text_content': [
    {
      "ok": true
    }
  ],
  'clone_node': [
    {
      "id": "60:1",
      "name": "Cloned Card",
      "type": "FRAME",
      "width": 320,
      "height": 180
    }
  ],
  'insert_child': [
    {
      "ok": true
    }
  ],
  'list_components': [
    {
      "count": 2,
      "components": [
        {
          "id": "12:1",
          "name": "Button / Primary",
          "description": "Main call-to-action button",
          "key": "button-primary-key"
        },
        {
          "id": "12:2",
          "name": "Input / Default",
          "key": "input-default-key"
        }
      ]
    }
  ],
  'list_library_components': [
    {
      "count": 2,
      "components": [
        {
          "key": "library-button-primary",
          "name": "Button / Primary",
          "description": "Primary CTA button"
        },
        {
          "key": "library-input-default",
          "name": "Input / Default",
          "description": "Default text field"
        }
      ]
    }
  ],
  'list_component_properties': [
    {
      "properties": [
        {
          "key": "State",
          "type": "VARIANT",
          "defaultValue": "Default",
          "variantOptions": [
            "Default",
            "Pressed",
            "Disabled"
          ]
        },
        {
          "key": "Has Icon",
          "type": "BOOLEAN",
          "defaultValue": false
        }
      ]
    }
  ],
  'get_component': [
    {
      "id": "12:1",
      "name": "Button / Primary",
      "type": "COMPONENT",
      "width": 160,
      "height": 48,
      "description": "Main call-to-action button",
      "key": "button-primary-key",
      "componentPropertyDefinitions": {
        "State#1": {
          "type": "VARIANT",
          "defaultValue": "Default"
        }
      }
    }
  ],
  'create_instance': [
    {
      "id": "40:1",
      "name": "Button / Primary",
      "type": "INSTANCE",
      "width": 160,
      "height": 48
    }
  ],
  'lint_fix_all': [
    {
      "lint": {
        "total": 24,
        "pass": 20,
        "violations": 4,
        "bySeverity": {
          "warning": 3,
          "error": 1
        }
      },
      "fixable": 3,
      "fixed": 3,
      "fixFailed": 0,
      "remaining": 1
    }
  ],
  'set_current_page': [
    {
      "ok": true,
      "pageId": "0:2",
      "pageName": "Components"
    }
  ],
  'export_image': [
    {
      "format": "PNG",
      "size": 18432,
      "base64": "iVBORw0KGgoAAAANSUhEUgAAAAUA"
    }
  ],
  'save_version_history': [
    {
      "ok": true,
      "title": "Before refactor",
      "description": "Checkpoint before layout cleanup"
    }
  ],
  'set_selection': [
    {
      "ok": true,
      "selectedCount": 2,
      "notFound": []
    },
    {
      "ok": true,
      "selectedCount": 1,
      "notFound": [
        "999:1"
      ]
    }
  ],
  'create_rectangle': [
    {
      "id": "50:1",
      "name": "Card Background",
      "type": "RECTANGLE",
      "width": 320,
      "height": 180,
      "cornerRadius": 24,
      "autoBound": "surface/default"
    }
  ],
  'create_ellipse': [
    {
      "id": "50:2",
      "name": "Avatar Dot",
      "type": "ELLIPSE",
      "width": 40,
      "height": 40,
      "autoBound": "surface/accent"
    }
  ],
  'create_vector': [
    {
      "id": "70:1",
      "name": "Arrow Icon",
      "type": "FRAME",
      "width": 24,
      "height": 24
    }
  ],
  'set_image_fill': [
    {
      "ok": true,
      "imageHash": "b2f7c1d4a9"
    }
  ],
  'list_variables': [
    {
      "count": 1,
      "variables": [
        {
          "id": "VariableID:1:12",
          "name": "color/brand/primary",
          "resolvedType": "COLOR",
          "description": "Primary brand color",
          "collectionId": "VariableCollectionId:1:2",
          "collectionName": "Primitives",
          "scopes": [
            "ALL_FILLS"
          ],
          "valuesByMode": {
            "Default": "#7c3aed"
          }
        }
      ]
    }
  ],
  'get_variable': [
    {
      "id": "VariableID:1:12",
      "name": "color/brand/primary",
      "resolvedType": "COLOR",
      "description": "Primary brand color",
      "collectionId": "VariableCollectionId:1:2",
      "collectionName": "Primitives",
      "scopes": [
        "ALL_FILLS"
      ],
      "codeSyntax": {
        "WEB": "var(--color-brand-primary)"
      },
      "valuesByMode": {
        "Default": "#7c3aed"
      }
    }
  ],
  'list_collections': [
    [
      {
        "id": "VariableCollectionId:1:2",
        "name": "Primitives",
        "modes": [
          {
            "modeId": "1:0",
            "name": "Default"
          }
        ],
        "variableCount": 12
      }
    ]
  ],
  'get_node_variables': [
    {
      "nodeId": "1:24",
      "bindings": {
        "fills": [
          {
            "variableId": "VariableID:1:12",
            "variableName": "color/brand/primary",
            "collectionId": "VariableCollectionId:1:2"
          }
        ]
      }
    }
  ],
  'set_variable_binding': [
    {
      "ok": true
    }
  ],
  'set_explicit_variable_mode': [
    {
      "ok": true
    }
  ],
  'create_variable': [
    {
      "id": "VariableID:1:30",
      "name": "spacing/md",
      "resolvedType": "FLOAT"
    }
  ],
  'update_variable': [
    {
      "ok": true,
      "id": "VariableID:1:30"
    }
  ],
  'delete_variable': [
    {
      "ok": true
    }
  ],
  'create_collection': [
    {
      "id": "VariableCollectionId:1:2",
      "name": "Semantic",
      "modes": [
        {
          "modeId": "1:0",
          "name": "Mode 1"
        }
      ]
    }
  ],
  'delete_collection': [
    {
      "ok": true
    }
  ],
  'rename_collection': [
    {
      "ok": true,
      "id": "VariableCollectionId:1:2",
      "name": "Semantic"
    }
  ],
  'add_collection_mode': [
    {
      "ok": true,
      "modeId": "1:1",
      "name": "Dark"
    }
  ],
  'rename_collection_mode': [
    {
      "ok": true
    }
  ],
  'remove_collection_mode': [
    {
      "ok": true
    }
  ],
  'create_variable_alias': [
    {
      "ok": true,
      "variableId": "VariableID:1:40",
      "aliasTo": "color/brand/primary"
    }
  ],
  'export_variables': [
    {
      "count": 1,
      "variables": [
        {
          "path": "color.brand.primary",
          "type": "color",
          "valuesByMode": {
            "Default": "#7c3aed"
          },
          "description": "Primary brand color",
          "scopes": [
            "ALL_FILLS"
          ]
        }
      ]
    }
  ],
  'batch_create_variables': [
    {
      "created": 2,
      "skipped": 0,
      "failed": 0,
      "errors": [],
      "collectionId": "VariableCollectionId:1:2",
      "description": "Array of variables to create"
    }
  ],
  'list_tokens': [
    {
      "total": 2,
      "showing": 2,
      "tokens": [
        {
          "path": "color.brand.primary",
          "type": "color",
          "value": "#7c3aed",
          "description": "Primary brand color"
        },
        {
          "path": "text.heading.l",
          "type": "typography",
          "value": {
            "fontFamily": "Inter",
            "fontWeight": 700,
            "fontSize": 32
          }
        }
      ]
    }
  ],
  'sync_tokens': [
    {
      "variables": {
        "created": 10,
        "updated": 2,
        "skipped": 1,
        "failed": 0,
        "failures": []
      },
      "styles": {
        "created": 2,
        "updated": 0,
        "skipped": 0,
        "failed": 0,
        "failures": []
      },
      "totalTokens": 15
    }
  ],
  'sync_tokens_multi_mode': [
    {
      "collectionId": "VariableCollectionId:1:2",
      "modes": [
        {
          "modeId": "1:0",
          "name": "Light"
        },
        {
          "modeId": "1:1",
          "name": "Dark"
        }
      ],
      "results": {
        "Light": {
          "variables": {
            "created": 8,
            "updated": 0,
            "skipped": 0,
            "failed": 0,
            "failures": []
          },
          "styles": {
            "created": 2,
            "updated": 0,
            "skipped": 0,
            "failed": 0,
            "failures": []
          },
          "totalTokens": 10
        }
      }
    }
  ],
  'diff_tokens': [
    {
      "summary": {
        "inSync": 8,
        "dtcgAhead": 1,
        "missingInFigma": 2,
        "missingInDtcg": 0
      },
      "diff": [
        {
          "path": "color.brand.primary",
          "status": "in-sync",
          "dtcgValue": "#7c3aed",
          "figmaValue": "#7c3aed"
        },
        {
          "path": "spacing.lg",
          "status": "missing-in-figma",
          "dtcgValue": 24
        }
      ]
    }
  ],
  'reverse_sync_tokens': [
    {
      "ok": true,
      "filePath": "/tmp/tokens.json",
      "tokenCount": 24
    }
  ],
  'cache_tokens': [
    {
      "cached": 24,
      "name": "tokens-light"
    }
  ],
  'list_cached_tokens': [
    {
      "entries": [
        "tokens-light",
        "tokens-dark"
      ]
    }
  ],
  'delete_cached_tokens': [
    {
      "ok": true
    }
  ],
  'scan_styles': [
    {
      "paint": [
        {
          "id": "Style:1",
          "name": "Color/Brand/Primary",
          "paints": 1
        }
      ],
      "text": [
        {
          "id": "Style:2",
          "name": "Text/Heading/L",
          "fontSize": 32,
          "fontName": {
            "family": "Inter",
            "style": "Bold"
          }
        }
      ],
      "effect": [
        {
          "id": "Style:3",
          "name": "Shadow/Card/Default",
          "effects": 1
        }
      ],
      "summary": {
        "paintCount": 1,
        "textCount": 1,
        "effectCount": 1
      }
    }
  ],
  'export_tokens': [
    {
      "Design Tokens": {
        "color/brand/primary": {
          "$value": "#7c3aed",
          "$type": "color",
          "$description": "Primary brand color"
        }
      }
    }
  ],
  'diff_styles': [
    {
      "diff": [
        {
          "path": "color.brand.primary",
          "status": "in-sync",
          "dtcgValue": "#7c3aed",
          "figmaValue": "#7c3aed"
        }
      ],
      "total": 1
    }
  ],
  'list_styles': [
    {
      "count": 2,
      "styles": [
        {
          "id": "Style:1",
          "name": "Color/Brand/Primary",
          "type": "PAINT",
          "description": "Primary brand color",
          "paints": [
            {
              "type": "SOLID",
              "visible": true,
              "opacity": 1,
              "color": "#7c3aed"
            }
          ]
        },
        {
          "id": "Style:2",
          "name": "Text/Heading/L",
          "type": "TEXT",
          "fontName": {
            "family": "Inter",
            "style": "Bold"
          },
          "fontSize": 32
        }
      ]
    }
  ],
  'get_style': [
    {
      "id": "Style:1",
      "name": "Color/Brand/Primary",
      "type": "PAINT",
      "description": "Primary brand color",
      "paints": [
        {
          "type": "SOLID",
          "visible": true,
          "opacity": 1,
          "color": "#7c3aed"
        }
      ]
    }
  ],
  'sync_styles': [
    {
      "created": 2,
      "updated": 1,
      "skipped": 0,
      "failed": 0,
      "failures": []
    }
  ],
  'create_paint_style': [
    {
      "id": "Style:10",
      "name": "Color/Brand/Primary"
    }
  ],
  'delete_style': [
    {
      "ok": true
    }
  ],
  'update_paint_style': [
    {
      "id": "Style:10",
      "name": "Color/Brand/Accent"
    }
  ],
  'update_text_style': [
    {
      "id": "Style:11",
      "name": "Text/Heading/L",
      "fontSize": 32
    }
  ],
  'update_effect_style': [
    {
      "id": "Style:12",
      "name": "Shadow/Card/Default"
    }
  ],
  'register_library_styles': [
    {
      "ok": true,
      "registered": {
        "textStyles": 8,
        "paintStyles": 12,
        "effectStyles": 3
      }
    }
  ],
  'get_registered_styles': [
    {
      "textStyles": [
        {
          "key": "S:1",
          "name": "Text/Heading/L",
          "fontSize": 32,
          "fontFamily": "Inter",
          "fontWeight": "Bold"
        }
      ],
      "paintStyles": [
        {
          "key": "S:2",
          "name": "Color/Brand/Primary",
          "hex": "#7c3aed"
        }
      ],
      "effectStyles": [
        {
          "key": "S:3",
          "name": "Shadow/Card/Default",
          "effectType": "DROP_SHADOW"
        }
      ],
      "_loaded": {
        "text": 1,
        "paint": 1,
        "effect": 1
      }
    }
  ],
  'create_component': [
    {
      "id": "80:1",
      "name": "Button / Primary",
      "type": "COMPONENT",
      "width": 160,
      "height": 48,
      "visible": true
    }
  ],
  'create_component_set': [
    {
      "id": "81:1",
      "name": "Button",
      "type": "COMPONENT_SET",
      "width": 320,
      "height": 48,
      "visible": true
    }
  ],
  'update_component': [
    {
      "id": "80:1",
      "name": "Button / Secondary",
      "type": "COMPONENT",
      "width": 160,
      "height": 48,
      "visible": true
    }
  ],
  'delete_component': [
    {
      "ok": true
    }
  ],
  'swap_instance': [
    {
      "id": "82:1",
      "name": "Button / Primary",
      "type": "INSTANCE",
      "width": 160,
      "height": 48,
      "visible": true
    }
  ],
  'detach_instance': [
    {
      "id": "83:1",
      "name": "Button / Primary",
      "type": "FRAME",
      "width": 160,
      "height": 48,
      "visible": true
    }
  ],
  'reset_instance_overrides': [
    {
      "ok": true
    }
  ],
  'get_instance_overrides': [
    {
      "nodeId": "82:1",
      "nodeName": "Button / Primary",
      "properties": [
        {
          "key": "State",
          "type": "VARIANT",
          "value": "Default"
        }
      ]
    }
  ],
  'set_instance_overrides': [
    {
      "succeeded": 3,
      "failed": 0
    }
  ],
  'add_component_property': [
    {
      "ok": true,
      "properties": [
        "State",
        "Label"
      ]
    }
  ],
  'update_component_property': [
    {
      "ok": true,
      "properties": [
        "State",
        "Label"
      ]
    }
  ],
  'delete_component_property': [
    {
      "ok": true,
      "properties": [
        "State"
      ]
    }
  ],
  'audit_components': [
    {
      "summary": {
        "totalComponents": 4,
        "totalIssues": 1
      },
      "components": [
        {
          "id": "80:1",
          "name": "Button / Primary",
          "propertyCount": 2
        }
      ],
      "issues": [
        {
          "nodeId": "80:1",
          "name": "Button / Primary",
          "issue": "Missing description"
        }
      ]
    }
  ],
  'list_library_collections': [
    [
      {
        "key": "VarCollectionKey:1",
        "name": "Color",
        "libraryName": "Acme DS"
      }
    ]
  ],
  'list_library_variables': [
    {
      "count": 1,
      "variables": [
        {
          "key": "VariableKey:1",
          "name": "color/brand/primary",
          "resolvedType": "COLOR"
        }
      ]
    }
  ],
  'import_library_variable': [
    {
      "id": "VariableID:9:1",
      "name": "color/brand/primary",
      "resolvedType": "COLOR",
      "description": "Primary brand color",
      "key": "VariableKey:1"
    }
  ],
  'list_library_styles': [
    {
      "count": 1,
      "styles": [
        {
          "key": "StyleKey:1",
          "file_key": "abc123",
          "node_id": "1:2",
          "style_type": "TEXT",
          "name": "Text/Heading/L",
          "description": "Display heading"
        }
      ]
    }
  ],
  'get_library_style_details': [
    {
      "count": 1,
      "styles": [
        {
          "key": "StyleKey:1",
          "file_key": "abc123",
          "node_id": "1:2",
          "style_type": "TEXT",
          "name": "Text/Heading/L",
          "description": "Display heading",
          "properties": {
            "fontFamily": "Inter",
            "fontSize": 32
          }
        }
      ]
    }
  ],
  'sync_library_styles': [
    {
      "ok": true,
      "discovered": {
        "total": 12,
        "text": 4,
        "fill": 6,
        "effect": 2
      },
      "diff": {
        "added": [],
        "removed": [],
        "modified": [],
        "unchanged": 12
      },
      "registered": {
        "ok": true,
        "registered": {
          "textStyles": 4,
          "paintStyles": 6,
          "effectStyles": 2
        }
      }
    }
  ],
  'import_library_style': [
    {
      "id": "Style:21",
      "name": "Text/Heading/L",
      "type": "TEXT",
      "key": "StyleKey:1",
      "description": "Display heading"
    }
  ],
  'create_line': [
    {
      "id": "90:1",
      "name": "Divider",
      "type": "LINE",
      "width": 320,
      "height": 0,
      "visible": true
    }
  ],
  'create_star': [
    {
      "id": "90:2",
      "name": "Star",
      "type": "STAR",
      "width": 100,
      "height": 100,
      "visible": true
    }
  ],
  'create_polygon': [
    {
      "id": "90:3",
      "name": "Triangle",
      "type": "POLYGON",
      "width": 100,
      "height": 100,
      "visible": true
    }
  ],
  'create_section': [
    {
      "id": "91:1",
      "name": "Onboarding",
      "x": 0,
      "y": 0
    }
  ],
  'flatten_node': [
    {
      "id": "92:1",
      "name": "Flattened Shape",
      "type": "VECTOR",
      "width": 120,
      "height": 120,
      "visible": true
    }
  ],
  'boolean_operation': [
    {
      "id": "93:1",
      "name": "Merged Shape",
      "type": "BOOLEAN_OPERATION",
      "width": 160,
      "height": 120,
      "visible": true
    }
  ],
  'get_annotations': [
    {
      "nodes": [
        {
          "nodeId": "100:1",
          "nodeName": "Login Form",
          "annotations": [
            {
              "label": "Check spacing",
              "properties": [
                {
                  "type": "design"
                }
              ]
            }
          ]
        }
      ],
      "count": 1
    }
  ],
  'set_annotation': [
    {
      "ok": true,
      "nodeId": "100:1",
      "count": 2
    }
  ],
  'set_multiple_annotations': [
    {
      "succeeded": 2,
      "failed": 0,
      "results": [
        {
          "nodeId": "100:1",
          "ok": true
        },
        {
          "nodeId": "100:2",
          "ok": true
        }
      ]
    }
  ],
  'clear_annotations': [
    {
      "cleared": 3
    }
  ],
  'get_reactions': [
    {
      "nodes": [
        {
          "nodeId": "101:1",
          "nodeName": "CTA Button",
          "reactions": [
            {
              "trigger": {
                "type": "ON_CLICK"
              },
              "actions": [
                {
                  "type": "NODE",
                  "destinationId": "101:2"
                }
              ]
            }
          ]
        }
      ],
      "count": 1
    }
  ],
  'analyze_prototype_flow': [
    {
      "graph": {
        "stats": {
          "totalScreens": 2,
          "totalInteractions": 1
        },
        "nodes": [],
        "edges": []
      },
      "mermaid": "graph TD\n  A --> B",
      "markdown": "# Prototype Flow Documentation"
    }
  ],
  'lint_check': [
    {
      "summary": {
        "total": 10,
        "pass": 8,
        "violations": 2
      },
      "categories": [
        {
          "rule": "default-name",
          "count": 1,
          "nodes": [
            {
              "nodeId": "1:2",
              "nodeName": "Frame 1",
              "suggestion": "Rename the frame semantically.",
              "autoFixable": false
            }
          ]
        }
      ],
      "scope": {
        "type": "page",
        "count": 1,
        "pageName": "Page 1"
      }
    }
  ],
  'lint_fix': [
    {
      "fixed": 2,
      "failed": 0,
      "errors": []
    }
  ],
  'lint_rules': [
    {
      "rules": [
        {
          "name": "default-name",
          "description": "Flags default Figma layer names.",
          "category": "naming",
          "severity": "warning"
        }
      ]
    }
  ],
  'compliance_report': [
    {
      "overallScore": 92,
      "lint": {
        "score": 95,
        "nodesChecked": 20,
        "passed": 19,
        "violations": 1
      },
      "components": {
        "score": 89,
        "total": 8,
        "issues": 1
      }
    }
  ],
  'figma_login': [
    {
      "ok": true,
      "url": "https://www.figma.com/oauth?client_id=example",
      "message": "Please open this URL in your browser to authorize figcraft with Figma."
    }
  ],
  'figma_logout': [
    {
      "ok": true,
      "message": "Figma credentials cleared."
    }
  ],
  'figma_auth_status': [
    {
      "method": "oauth",
      "expiresAt": 1893456000000
    }
  ],
  'create_page': [
    {
      "id": "0:3",
      "name": "Marketing"
    }
  ],
  'rename_page': [
    {
      "ok": true,
      "id": "0:3",
      "name": "Marketing"
    }
  ],
  'delete_node': [
    {
      "ok": true
    }
  ],
};

export const GENERATED_ENDPOINT_METHOD_RESPONSE_SCHEMAS: Record<string, Record<string, z.ZodTypeAny>> = {
  'nodes': {
    'get': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number().optional(),
      height: z.number().optional(),
      children: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
        })).optional(),
    }),
    'list': z.object({
      count: z.number(),
      nodes: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
        })),
      _error: z.string().optional(),
      _sizeKB: z.number().optional(),
      _limitKB: z.number().optional(),
      method: z.string().optional(),
      warning: z.string().optional(),
      hints: z.array(z.string()).optional(),
      _preview: z.string().optional(),
    }),
    'update': z.object({
      results: z.array(z.object({
          nodeId: z.string(),
          ok: z.boolean(),
          error: z.string().optional(),
        })),
    }),
    'delete': z.object({
      results: z.array(z.object({
          nodeId: z.string(),
          ok: z.boolean(),
          error: z.string().optional(),
        })),
    }),
    'clone': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number().optional(),
      height: z.number().optional(),
    }),
    'insert_child': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  },
  'text': {
    'create': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      characters: z.string().optional(),
      fontSize: z.number().optional(),
      autoBound: z.record(z.unknown()).optional(),
    }),
    'set_content': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  },
  'shapes': {
    'create_frame': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number().optional(),
      height: z.number().optional(),
      layoutMode: z.string().optional(),
      autoBound: z.string().optional(),
    }),
    'create_rectangle': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number().optional(),
      height: z.number().optional(),
      cornerRadius: z.unknown().optional(),
      autoBound: z.string().optional(),
    }),
    'create_ellipse': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number().optional(),
      height: z.number().optional(),
      autoBound: z.string().optional(),
    }),
    'create_vector': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number().optional(),
      height: z.number().optional(),
    }),
  },
  'components': {
    'list': z.object({
      count: z.number(),
      components: z.array(z.object({
          id: z.string(),
          name: z.string(),
          description: z.string().optional(),
          key: z.string().optional(),
        })),
    }),
    'list_library': z.object({
      count: z.number(),
      components: z.array(z.object({
          key: z.string(),
          name: z.string(),
          description: z.string().optional(),
        })),
    }),
    'get': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      description: z.string().optional(),
      key: z.string().optional(),
      componentPropertyDefinitions: z.record(z.unknown()).optional(),
    }),
    'create_instance': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number().optional(),
      height: z.number().optional(),
      error: z.string().optional(),
    }),
    'list_properties': z.object({
      properties: z.array(z.object({
          key: z.string(),
          type: z.string(),
          defaultValue: z.unknown().optional(),
          variantOptions: z.array(z.string()).optional(),
        })),
    }),
  },
  'variables_ep': {
    'list': z.object({
      count: z.number(),
      variables: z.array(z.object({
          id: z.string(),
          name: z.string(),
          resolvedType: z.string(),
          description: z.string().optional(),
          collectionId: z.string(),
          collectionName: z.string(),
          scopes: z.array(z.string()),
          valuesByMode: z.record(z.unknown()),
        })),
    }),
    'get': z.object({
      id: z.string(),
      name: z.string(),
      resolvedType: z.string(),
      description: z.string().optional(),
      collectionId: z.string(),
      collectionName: z.string().optional(),
      scopes: z.array(z.string()),
      codeSyntax: z.unknown().optional(),
      valuesByMode: z.record(z.unknown()),
      error: z.string().optional(),
    }),
    'list_collections': z.array(z.object({
          id: z.string(),
          name: z.string(),
          modes: z.array(z.object({
          modeId: z.string(),
          name: z.string(),
        })),
          variableCount: z.number(),
        })),
    'get_bindings': z.object({
      nodeId: z.string(),
      bindings: z.record(z.unknown()),
      error: z.string().optional(),
    }),
    'set_binding': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
    'create': z.object({
      id: z.string(),
      name: z.string(),
      resolvedType: z.string(),
      error: z.string().optional(),
    }),
    'update': z.object({
      ok: z.boolean(),
      id: z.string().optional(),
      error: z.string().optional(),
    }),
    'delete': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
    'create_collection': z.object({
      id: z.string(),
      name: z.string(),
      modes: z.array(z.object({
          modeId: z.string(),
          name: z.string(),
        })),
    }),
    'delete_collection': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
    'batch_create': z.object({
      created: z.number(),
      skipped: z.number(),
      failed: z.number(),
      errors: z.array(z.object({
          name: z.string(),
          error: z.string(),
        })),
      collectionId: z.string(),
    }),
    'export': z.object({
      count: z.number(),
      variables: z.array(z.object({
          path: z.string(),
          type: z.string(),
          valuesByMode: z.record(z.unknown()),
          description: z.string().optional(),
          scopes: z.array(z.string()).optional(),
          aliasOf: z.record(z.string()).optional(),
        })),
    }),
  },
  'styles_ep': {
    'list': z.object({
      count: z.number(),
      styles: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
          description: z.string().optional(),
          paints: z.array(z.record(z.unknown())).optional(),
          fontName: z.unknown().optional(),
          fontSize: z.number().optional(),
          letterSpacing: z.unknown().optional(),
          lineHeight: z.unknown().optional(),
          textCase: z.string().optional(),
          textDecoration: z.string().optional(),
          effects: z.array(z.record(z.unknown())).optional(),
        })),
    }),
    'get': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      description: z.string().optional(),
      paints: z.array(z.record(z.unknown())).optional(),
      fontName: z.unknown().optional(),
      fontSize: z.number().optional(),
      letterSpacing: z.unknown().optional(),
      lineHeight: z.unknown().optional(),
      textCase: z.string().optional(),
      textDecoration: z.string().optional(),
      effects: z.array(z.record(z.unknown())).optional(),
      error: z.string().optional(),
    }),
    'create_paint': z.object({
      id: z.string(),
      name: z.string(),
    }),
    'update_paint': z.object({
      id: z.string(),
      name: z.string(),
      error: z.string().optional(),
    }),
    'update_text': z.object({
      id: z.string(),
      name: z.string(),
      fontSize: z.number().optional(),
      error: z.string().optional(),
    }),
    'update_effect': z.object({
      id: z.string(),
      name: z.string(),
      error: z.string().optional(),
    }),
    'delete': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
    'sync': z.object({
      created: z.number(),
      updated: z.number(),
      skipped: z.number(),
      failed: z.number(),
      failures: z.array(z.object({
          path: z.string(),
          error: z.string(),
        })),
    }),
  },
};

export const GENERATED_ENDPOINT_METHOD_RESPONSE_EXAMPLES: Record<string, Record<string, unknown[]>> = {
  'nodes': {
    'get': [
      {
        "id": "1:23",
        "name": "Auth Screen",
        "type": "FRAME",
        "width": 402,
        "height": 874,
        "children": [
          {
            "id": "1:24",
            "name": "Login Form",
            "type": "FRAME"
          }
        ]
      }
    ],
    'list': [
      {
        "count": 1,
        "nodes": [
          {
            "id": "1:10",
            "name": "Login Button",
            "type": "FRAME"
          }
        ]
      }
    ],
    'update': [
      {
        "results": [
          {
            "nodeId": "30:1",
            "ok": true
          }
        ]
      }
    ],
    'delete': [
      {
        "results": [
          {
            "nodeId": "30:1",
            "ok": true
          }
        ]
      }
    ],
    'clone': [
      {
        "id": "60:1",
        "name": "Cloned Card",
        "type": "FRAME",
        "width": 320,
        "height": 180
      }
    ],
    'insert_child': [
      {
        "ok": true
      }
    ],
  },
  'text': {
    'create': [
      {
        "id": "30:2",
        "name": "Hero Title",
        "type": "TEXT",
        "characters": "Ship Faster",
        "fontSize": 32,
        "autoBound": {
          "color": "text/primary"
        }
      }
    ],
    'set_content': [
      {
        "ok": true
      }
    ],
  },
  'shapes': {
    'create_frame': [
      {
        "id": "30:1",
        "name": "Card Frame",
        "type": "FRAME",
        "width": 320,
        "height": 180,
        "layoutMode": "VERTICAL",
        "autoBound": "surface/default"
      }
    ],
    'create_rectangle': [
      {
        "id": "50:1",
        "name": "Card Background",
        "type": "RECTANGLE",
        "width": 320,
        "height": 180,
        "cornerRadius": 24
      }
    ],
    'create_ellipse': [
      {
        "id": "50:2",
        "name": "Avatar Dot",
        "type": "ELLIPSE",
        "width": 40,
        "height": 40
      }
    ],
    'create_vector': [
      {
        "id": "70:1",
        "name": "Arrow Icon",
        "type": "FRAME",
        "width": 24,
        "height": 24
      }
    ],
  },
  'components': {
    'list': [
      {
        "count": 1,
        "components": [
          {
            "id": "12:1",
            "name": "Button / Primary",
            "key": "button-primary-key"
          }
        ]
      }
    ],
    'list_library': [
      {
        "count": 1,
        "components": [
          {
            "key": "library-button-primary",
            "name": "Button / Primary",
            "description": "Primary CTA button"
          }
        ]
      }
    ],
    'get': [
      {
        "id": "12:1",
        "name": "Button / Primary",
        "type": "COMPONENT",
        "description": "Main call-to-action button",
        "key": "button-primary-key"
      }
    ],
    'create_instance': [
      {
        "id": "40:1",
        "name": "Button / Primary",
        "type": "INSTANCE",
        "width": 160,
        "height": 48
      }
    ],
    'list_properties': [
      {
        "properties": [
          {
            "key": "State",
            "type": "VARIANT",
            "defaultValue": "Default",
            "variantOptions": [
              "Default",
              "Pressed"
            ]
          }
        ]
      }
    ],
  },
  'variables_ep': {
    'list': [
      {
        "count": 1,
        "variables": [
          {
            "id": "VariableID:1:12",
            "name": "color/brand/primary",
            "resolvedType": "COLOR",
            "description": "Primary brand color",
            "collectionId": "VariableCollectionId:1:2",
            "collectionName": "Primitives",
            "scopes": [
              "ALL_FILLS"
            ],
            "valuesByMode": {
              "Default": "#7c3aed"
            }
          }
        ]
      }
    ],
    'get': [
      {
        "id": "VariableID:1:12",
        "name": "color/brand/primary",
        "resolvedType": "COLOR",
        "description": "Primary brand color",
        "collectionId": "VariableCollectionId:1:2",
        "collectionName": "Primitives",
        "scopes": [
          "ALL_FILLS"
        ],
        "codeSyntax": {
          "WEB": "var(--color-brand-primary)"
        },
        "valuesByMode": {
          "Default": "#7c3aed"
        }
      }
    ],
    'list_collections': [
      [
        {
          "id": "VariableCollectionId:1:2",
          "name": "Primitives",
          "modes": [
            {
              "modeId": "1:0",
              "name": "Default"
            }
          ],
          "variableCount": 12
        }
      ]
    ],
    'get_bindings': [
      {
        "nodeId": "1:24",
        "bindings": {
          "fills": [
            {
              "variableId": "VariableID:1:12",
              "variableName": "color/brand/primary",
              "collectionId": "VariableCollectionId:1:2"
            }
          ]
        }
      }
    ],
    'set_binding': [
      {
        "ok": true
      }
    ],
    'create': [
      {
        "id": "VariableID:1:30",
        "name": "spacing/md",
        "resolvedType": "FLOAT"
      }
    ],
    'update': [
      {
        "ok": true,
        "id": "VariableID:1:30"
      }
    ],
    'delete': [
      {
        "ok": true
      }
    ],
    'create_collection': [
      {
        "id": "VariableCollectionId:1:2",
        "name": "Semantic",
        "modes": [
          {
            "modeId": "1:0",
            "name": "Mode 1"
          }
        ]
      }
    ],
    'delete_collection': [
      {
        "ok": true
      }
    ],
    'batch_create': [
      {
        "created": 2,
        "skipped": 0,
        "failed": 0,
        "errors": [],
        "collectionId": "VariableCollectionId:1:2"
      }
    ],
    'export': [
      {
        "count": 1,
        "variables": [
          {
            "path": "color.brand.primary",
            "type": "color",
            "valuesByMode": {
              "Default": "#7c3aed"
            },
            "description": "Primary brand color",
            "scopes": [
              "ALL_FILLS"
            ]
          }
        ]
      }
    ],
  },
  'styles_ep': {
    'list': [
      {
        "count": 2,
        "styles": [
          {
            "id": "Style:1",
            "name": "Color/Brand/Primary",
            "type": "PAINT",
            "description": "Primary brand color",
            "paints": [
              {
                "type": "SOLID",
                "visible": true,
                "opacity": 1,
                "color": "#7c3aed"
              }
            ]
          },
          {
            "id": "Style:2",
            "name": "Text/Heading/L",
            "type": "TEXT",
            "fontName": {
              "family": "Inter",
              "style": "Bold"
            },
            "fontSize": 32
          }
        ]
      }
    ],
    'get': [
      {
        "id": "Style:1",
        "name": "Color/Brand/Primary",
        "type": "PAINT",
        "description": "Primary brand color",
        "paints": [
          {
            "type": "SOLID",
            "visible": true,
            "opacity": 1,
            "color": "#7c3aed"
          }
        ]
      }
    ],
    'create_paint': [
      {
        "id": "Style:10",
        "name": "Color/Brand/Primary"
      }
    ],
    'update_paint': [
      {
        "id": "Style:10",
        "name": "Color/Brand/Accent"
      }
    ],
    'update_text': [
      {
        "id": "Style:11",
        "name": "Text/Heading/L",
        "fontSize": 32
      }
    ],
    'update_effect': [
      {
        "id": "Style:12",
        "name": "Shadow/Card/Default"
      }
    ],
    'delete': [
      {
        "ok": true
      }
    ],
    'sync': [
      {
        "created": 2,
        "updated": 1,
        "skipped": 0,
        "failed": 0,
        "failures": []
      }
    ],
  },
};
