/**
 * AUTO-GENERATED by scripts/compile-schema.ts — DO NOT EDIT
 *
 * Tool response contracts and example payloads derived from schema/tools.yaml.
 * These are intended for docs, tests, and future prompt/runtime validation work.
 *
 * Re-generate: npm run schema
 */

import { z } from 'zod';

export const GENERATED_TOOL_RESPONSE_SCHEMAS: Record<string, z.ZodTypeAny> = {
  'ping': z.object({
      connected: z.boolean(),
      latency: z.string().optional(),
      serverVersion: z.string().optional(),
      pluginVersion: z.string().optional(),
      versionWarning: z.string().optional(),
      error: z.string().optional(),
      _hint: z.string().optional(),
      result: z.record(z.unknown()).optional(),
    }),
  'get_mode': z.object({
      connected: z.boolean(),
      latency: z.string().optional(),
      versionWarning: z.string().optional(),
      mode: z.enum(['library', 'spec']).optional(),
      selectedLibrary: z.string().optional(),
      designContext: z.record(z.unknown()).optional(),
      libraryComponents: z.object({
        componentSets: z.array(z.object({
          key: z.string(),
          name: z.string(),
          description: z.string(),
          variants: z.array(z.object({
          key: z.string(),
          name: z.string(),
          properties: z.record(z.string()).optional(),
        })).optional(),
        })).optional(),
        standalone: z.array(z.object({
          key: z.string(),
          name: z.string(),
          description: z.string(),
        })).optional(),
      }).optional(),
      libraryComponentsError: z.string().optional(),
      libraryComponentsUnavailable: z.boolean().optional(),
      _hint: z.string().optional(),
      error: z.string().optional(),
    }),
  'set_mode': z.object({
      mode: z.enum(['library', 'spec']),
      description: z.string(),
    }),
  'get_design_guidelines': z.object({
      mode: z.string(),
      selectedLibrary: z.string().optional(),
      category: z.string().optional(),
      guidelines: z.string(),
    }),
  'get_creation_guide': z.string(),
  'audit_node': z.object({
      nodeId: z.string(),
      nodeName: z.string(),
      nodeType: z.string(),
      qualityScore: z.number(),
      summary: z.object({
        totalChecked: z.number().optional(),
        violations: z.number().optional(),
        errors: z.number().optional(),
        unsafes: z.number().optional(),
        heuristics: z.number().optional(),
        styles: z.number().optional(),
        autoFixable: z.number().optional(),
      }),
      violations: z.array(z.record(z.unknown())).optional(),
      structuralNotes: z.array(z.string()).optional(),
      recommendation: z.string(),
    }),
  'join_channel': z.object({
      ok: z.boolean(),
      channel: z.string().optional(),
      message: z.string().optional(),
      error: z.string().optional(),
    }),
  'get_channel': z.object({
      channel: z.string(),
      connected: z.boolean(),
    }),
  'get_current_page': z.object({
      id: z.string(),
      name: z.string(),
      childCount: z.number(),
      returnedNodes: z.number(),
      truncated: z.boolean().optional(),
      nodes: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
        })),
      _error: z.string().optional(),
      _sizeKB: z.number().optional(),
      _limitKB: z.number().optional(),
      method: z.string().optional(),
      warning: z.string().optional(),
      hints: z.array(z.string()).optional(),
      _previewHint: z.string().optional(),
    }),
  'get_design_context': z.object({
      framework: z.string(),
      frameworkHint: z.string().describe("Short guidance string the calling LLM can lean on while generating code"),
      tree: z.record(z.unknown()).describe("Full node tree (boundVariables/styleIds preserved)"),
      summary: z.object({
        textNodes: z.number(),
        imageNodes: z.number(),
        variablesUsed: z.number(),
        stylesUsed: z.number(),
        componentsUsed: z.number(),
      }),
      variables: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
          collection: z.string().optional(),
        })),
      styles: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
        })),
      components: z.array(z.object({
          id: z.string(),
          key: z.string().optional(),
          name: z.string(),
          isSet: z.boolean(),
          remote: z.boolean(),
          description: z.string().optional(),
          propertyDefinitions: z.record(z.unknown()).optional(),
        })),
    }),
  'get_document_info': z.object({
      name: z.string(),
      currentPage: z.string(),
      pages: z.array(z.object({
          id: z.string(),
          name: z.string(),
          childCount: z.number(),
        })),
    }),
  'get_selection': z.object({
      count: z.number(),
      nodes: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
        })),
    }),
  'list_fonts': z.object({
      family: z.string().optional(),
      styles: z.array(z.string()).optional(),
      count: z.number().optional(),
      families: z.array(z.string()).optional(),
      total: z.number().optional(),
    }),
  'create_frame': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
      _libraryBindings: z.array(z.unknown()).optional().describe("Token/style bindings applied during creation"),
      _hints: z.array(z.unknown()).optional().describe("Smart default inferences applied (sizing, layoutMode)"),
      _warnings: z.array(z.unknown()).optional().describe("Non-fatal issues during creation (e.g. image load failed, style not found)"),
      _children: z.array(z.unknown()).optional().describe("Created child node IDs (when children param used)"),
      _inferences: z.array(z.unknown()).optional().describe("Layout inferences applied during creation (deterministic or ambiguous)"),
      _correctedPayload: z.record(z.unknown()).optional().describe("Corrected params when ambiguous inferences detected — use this in your next call to avoid ambiguity"),
      _diff: z.string().optional().describe("Git-style diff of ambiguous inferences (only present when ambiguity detected)"),
      _lintSummary: z.record(z.unknown()).optional().describe("Quick lint summary after creation (only present when children created and violations found). Run lint_fix_all to fix."),
    }),
  'create_text': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
      _libraryBindings: z.array(z.unknown()).optional().describe("Token/style bindings applied during creation"),
      _hints: z.array(z.unknown()).optional().describe("Smart default inferences applied (sizing, textAutoResize)"),
    }),
  'lint_fix_all': z.object({
      lint: z.object({
        total: z.number(),
        pass: z.number(),
        violations: z.number(),
        bySeverity: z.record(z.unknown()).optional(),
      }),
      fixable: z.number(),
      fixed: z.number(),
      fixFailed: z.number(),
      remaining: z.number(),
      remainingFixCalls: z.array(z.unknown()).optional().describe("Remaining violations with structured fixCall for AI follow-up (max 10). Each: {nodeId, nodeName, rule, severity, suggestion, fixCall: {tool, params}}"),
    }),
  'set_current_page': z.object({
      ok: z.boolean(),
      pageId: z.string().optional(),
      pageName: z.string().optional(),
      error: z.string().optional(),
    }),
  'export_image': z.object({
      format: z.string(),
      size: z.number(),
      base64: z.string(),
    }),
  'save_version_history': z.object({
      ok: z.boolean(),
      title: z.string(),
      description: z.string(),
    }),
  'set_selection': z.object({
      ok: z.boolean(),
      selectedCount: z.number(),
      notFound: z.array(z.string()),
    }),
  'execute_js': z.object({
      ok: z.boolean(),
      result: z.unknown().optional(),
      error: z.string().optional(),
      stack: z.string().optional(),
      _warning: z.string().optional(),
    }),
  'icon_search': z.object({
      icons: z.array(z.string()).optional(),
      total: z.number().optional(),
    }),
  'icon_collections': z.object({
      collections: z.array(z.unknown()).optional(),
      total: z.number().optional(),
    }),
  'icon_create': z.object({
      id: z.string(),
      name: z.string().optional(),
    }),
  'image_search': z.object({
      photos: z.array(z.unknown()).optional(),
      total_results: z.number().optional(),
      page: z.number().optional(),
    }),
  'image_preview': z.record(z.unknown()).describe("Image content (base64) + photo metadata"),
  'create_image_frame_from_local': z.object({
      id: z.string().optional(),
      name: z.string().optional(),
      width: z.number().optional(),
      height: z.number().optional(),
      imageHash: z.string().optional(),
      source: z.record(z.unknown()).optional(),
      placement: z.record(z.unknown()).optional(),
    }),
  'fill_existing_image_from_local': z.object({
      ok: z.boolean().optional(),
      id: z.string().optional(),
      name: z.string().optional(),
      width: z.number().optional(),
      height: z.number().optional(),
      imageHash: z.string().optional(),
      source: z.record(z.unknown()).optional(),
    }),
  'create_svg': z.object({
      id: z.string(),
      name: z.string().optional(),
    }),
  'text_scan': z.object({
      nodeId: z.string(),
      count: z.number(),
      textNodes: z.array(z.object({
          id: z.string().optional(),
          name: z.string().optional(),
          characters: z.string().optional(),
          fontSize: z.number().optional(),
          fontFamily: z.string().optional(),
          path: z.string().optional(),
        })).optional(),
    }),
  'search_design_system': z.object({
      query: z.string(),
      components: z.array(z.unknown()).optional().describe("Matching components with key, name, description"),
      variables: z.array(z.unknown()).optional().describe("Matching variables with key, name, resolvedType, collection"),
      styles: z.array(z.unknown()).optional().describe("Matching styles with key, name, styleType"),
      summary: z.object({
        components: z.number().optional(),
        variables: z.number().optional(),
        styles: z.number().optional(),
      }).optional(),
    }),
  'set_explicit_variable_mode': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  'rename_collection': z.object({
      ok: z.boolean(),
      id: z.string().optional(),
      name: z.string().optional(),
      error: z.string().optional(),
    }),
  'add_collection_mode': z.object({
      ok: z.boolean(),
      modeId: z.string().optional(),
      name: z.string().optional(),
      error: z.string().optional(),
    }),
  'rename_collection_mode': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  'remove_collection_mode': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  'create_variable_alias': z.object({
      ok: z.boolean(),
      variableId: z.string().optional(),
      aliasTo: z.string().optional(),
      error: z.string().optional(),
    }),
  'list_tokens': z.object({
      total: z.number(),
      showing: z.number(),
      tokens: z.array(z.object({
          path: z.string(),
          type: z.string(),
          value: z.unknown(),
          description: z.string().optional(),
          extensions: z.record(z.unknown()).optional(),
        })),
    }),
  'sync_tokens': z.object({
      variables: z.object({
        created: z.number(),
        updated: z.number(),
        skipped: z.number(),
        failed: z.number(),
        failures: z.array(z.record(z.unknown())),
      }),
      styles: z.object({
        created: z.number(),
        updated: z.number(),
        skipped: z.number(),
        failed: z.number(),
        failures: z.array(z.record(z.unknown())),
      }),
      totalTokens: z.number(),
    }),
  'sync_tokens_multi_mode': z.object({
      collectionId: z.string(),
      modes: z.array(z.object({
          modeId: z.string(),
          name: z.string(),
        })),
      results: z.record(z.unknown()),
    }),
  'diff_tokens': z.object({
      summary: z.object({
        inSync: z.number(),
        dtcgAhead: z.number(),
        missingInFigma: z.number(),
        missingInDtcg: z.number(),
      }),
      diff: z.array(z.object({
          path: z.string(),
          status: z.string(),
          dtcgValue: z.unknown().optional(),
          figmaValue: z.unknown().optional(),
        })),
    }),
  'reverse_sync_tokens': z.object({
      ok: z.boolean(),
      filePath: z.string(),
      tokenCount: z.number(),
    }),
  'cache_tokens': z.object({
      cached: z.number(),
      name: z.string(),
    }),
  'list_cached_tokens': z.object({
      entries: z.array(z.string()),
    }),
  'delete_cached_tokens': z.object({
      ok: z.boolean(),
    }),
  'scan_styles': z.object({
      paint: z.array(z.object({
          id: z.string(),
          name: z.string(),
          paints: z.number(),
        })),
      text: z.array(z.object({
          id: z.string(),
          name: z.string(),
          fontSize: z.number(),
          fontName: z.unknown().optional(),
        })),
      effect: z.array(z.object({
          id: z.string(),
          name: z.string(),
          effects: z.number(),
        })),
      summary: z.object({
        paintCount: z.number(),
        textCount: z.number(),
        effectCount: z.number(),
      }),
    }),
  'export_tokens': z.record(z.unknown()),
  'diff_styles': z.object({
      diff: z.array(z.object({
          path: z.string(),
          status: z.string(),
          dtcgValue: z.unknown().optional(),
          figmaValue: z.unknown().optional(),
        })),
      total: z.number(),
      error: z.string().optional(),
    }),
  'register_library_styles': z.object({
      ok: z.boolean(),
      registered: z.object({
        textStyles: z.number(),
        paintStyles: z.number(),
        effectStyles: z.number(),
      }),
    }),
  'get_registered_styles': z.object({
      textStyles: z.array(z.object({
          key: z.string(),
          name: z.string(),
          fontSize: z.number(),
          fontFamily: z.string(),
          fontWeight: z.string(),
        })),
      paintStyles: z.array(z.object({
          key: z.string(),
          name: z.string(),
          hex: z.string(),
        })),
      effectStyles: z.array(z.object({
          key: z.string(),
          name: z.string(),
          effectType: z.string(),
        })),
      _loaded: z.object({
        text: z.number(),
        paint: z.number(),
        effect: z.number(),
      }).optional(),
    }),
  'create_component': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
      _libraryBindings: z.array(z.unknown()).optional().describe("Token/style bindings applied during creation"),
      _hints: z.array(z.unknown()).optional().describe("Smart default inferences applied"),
      _warnings: z.array(z.unknown()).optional().describe("Non-fatal issues during creation"),
      _children: z.array(z.unknown()).optional().describe("Created child node IDs"),
      _lintSummary: z.record(z.unknown()).optional().describe("Quick lint summary after creation. Run lint_fix_all to fix violations."),
    }),
  'create_component_set': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
    }),
  'update_component': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
      _warnings: z.array(z.string()).optional().describe("Non-fatal warnings (e.g. width/height ignored on COMPONENT_SET). Only present when at least one warning was collected."),
    }),
  'delete_component': z.object({
      ok: z.boolean(),
    }),
  'create_instance': z.object({
      id: z.string(),
      name: z.string().optional(),
      type: z.string().optional(),
    }),
  'create_instances': z.object({
      results: z.array(z.unknown()),
    }),
  'create_component_from_node': z.object({
      id: z.string(),
      name: z.string().optional(),
    }),
  'layout_component_set': z.object({
      ok: z.boolean(),
      componentSetId: z.string(),
      positioned: z.number(),
      grid: z.object({
        columns: z.number().optional(),
        rows: z.number().optional(),
        columnAxis: z.string().optional(),
        rowAxes: z.array(z.string()).optional(),
      }).optional(),
      size: z.object({
        width: z.number().optional(),
        height: z.number().optional(),
      }).optional(),
    }),
  'bind_component_property': z.object({
      ok: z.boolean(),
      action: z.string().optional().describe("'single' for single-component mode, 'batch' when items[] was used"),
      bindingsProcessed: z.number().optional(),
      variantsTargeted: z.number().optional(),
      totalBound: z.number().optional(),
      totalNotFound: z.number().optional(),
      results: z.array(z.object({
          propertyName: z.string(),
          bound: z.number(),
          notFound: z.number(),
        })).optional().describe("Single-component mode: per-binding counters"),
      errors: z.array(z.object({
          variantName: z.string().optional(),
          propertyName: z.string().optional(),
          error: z.string().optional(),
        })).optional(),
      created: z.number().optional().describe("Batch mode only: count of successfully processed items"),
      total: z.number().optional().describe("Batch mode only: total items submitted"),
      items: z.array(z.object({
          nodeId: z.string(),
          ok: z.boolean(),
          bindingsProcessed: z.number().optional(),
          variantsTargeted: z.number().optional(),
          totalBound: z.number().optional(),
          totalNotFound: z.number().optional(),
          error: z.string().optional(),
        })).optional().describe("Batch mode only: per-item outcome"),
    }),
  'swap_instance': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
      error: z.string().optional(),
    }),
  'detach_instance': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
      error: z.string().optional(),
    }),
  'reset_instance_overrides': z.object({
      ok: z.boolean(),
    }),
  'get_instance_overrides': z.object({
      nodeId: z.string(),
      nodeName: z.string(),
      properties: z.array(z.object({
          key: z.string(),
          type: z.string(),
          value: z.unknown().optional(),
        })),
    }),
  'set_instance_overrides': z.object({
      succeeded: z.number(),
      failed: z.number(),
    }),
  'add_component_property': z.object({
      ok: z.boolean(),
      key: z.string().optional().describe("The property key with Figma suffix (e.g. \"Label#0:1\"). Use this key for componentPropertyReferences."),
      properties: z.array(z.string()).optional(),
      error: z.string().optional(),
    }),
  'update_component_property': z.object({
      ok: z.boolean(),
      properties: z.array(z.string()).optional(),
      error: z.string().optional(),
    }),
  'delete_component_property': z.object({
      ok: z.boolean(),
      properties: z.array(z.string()).optional(),
      error: z.string().optional(),
    }),
  'audit_components': z.object({
      summary: z.object({
        totalComponents: z.number(),
        totalIssues: z.number(),
      }),
      components: z.array(z.record(z.unknown())),
      issues: z.array(z.object({
          nodeId: z.string(),
          name: z.string(),
          issue: z.string(),
        })),
    }),
  'get_code_connect_metadata': z.object({
      componentName: z.string(),
      nodeId: z.string(),
      isComponentSet: z.boolean(),
      remote: z.boolean(),
      description: z.string().optional(),
      figmaUrl: z.string(),
      properties: z.array(z.object({
          bareName: z.string().describe("Property name with #id suffix stripped — use this in Code Connect files"),
          figmaKey: z.string(),
          type: z.string(),
          defaultValue: z.string().optional(),
          variantOptions: z.array(z.string()).optional(),
        })),
      slots: z.object({
        textSlots: z.array(z.object({
          name: z.string(),
          characters: z.string(),
        })),
        instanceSlots: z.array(z.object({
          name: z.string(),
          mainComponentName: z.string().optional(),
        })),
      }),
      summary: z.object({
        propertyCount: z.number(),
        textProperties: z.number(),
        booleanProperties: z.number(),
        instanceSwapProperties: z.number(),
        variantProperties: z.number(),
        slotProperties: z.number(),
        textSlotCount: z.number(),
        instanceSlotCount: z.number(),
      }),
    }),
  'preflight_library_publish': z.object({
      ready: z.boolean().describe("True when there are no blockers (warnings are OK)"),
      summary: z.object({
        components: z.number(),
        componentSets: z.number(),
        variables: z.number(),
        styles: z.number(),
        blockerCount: z.number(),
        warningCount: z.number(),
      }),
      blockers: z.array(z.object({
          severity: z.string(),
          category: z.string(),
          target: z.string(),
          nodeId: z.string().optional(),
          message: z.string(),
          suggestion: z.string().optional(),
        })),
      warnings: z.array(z.object({
          severity: z.string(),
          category: z.string(),
          target: z.string(),
          nodeId: z.string().optional(),
          message: z.string(),
          suggestion: z.string().optional(),
        })),
    }),
  'list_library_collections': z.array(z.object({
          key: z.string(),
          name: z.string(),
          libraryName: z.string(),
        })),
  'list_library_variables': z.object({
      count: z.number(),
      variables: z.array(z.object({
          key: z.string(),
          name: z.string(),
          resolvedType: z.string(),
        })),
    }),
  'import_library_variable': z.object({
      id: z.string(),
      name: z.string(),
      resolvedType: z.string(),
      description: z.string().optional(),
      key: z.string(),
    }),
  'list_library_styles': z.object({
      count: z.number(),
      styles: z.array(z.object({
          key: z.string(),
          file_key: z.string(),
          node_id: z.string(),
          style_type: z.string(),
          name: z.string(),
          description: z.string().optional(),
        })),
    }),
  'get_library_style_details': z.object({
      count: z.number(),
      styles: z.array(z.object({
          key: z.string(),
          file_key: z.string(),
          node_id: z.string(),
          style_type: z.string(),
          name: z.string(),
          description: z.string().optional(),
          properties: z.record(z.unknown()),
        })),
    }),
  'sync_library_styles': z.object({
      ok: z.boolean(),
      discovered: z.object({
        total: z.number(),
        text: z.number(),
        fill: z.number(),
        effect: z.number(),
      }),
      diff: z.record(z.unknown()),
      registered: z.unknown(),
    }),
  'import_library_style': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      key: z.string(),
      description: z.string().optional(),
    }),
  'create_line': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
    }),
  'create_star': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
    }),
  'create_polygon': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
    }),
  'create_rectangle': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
      _libraryBindings: z.array(z.unknown()).optional().describe("Token/style bindings applied during creation"),
    }),
  'create_ellipse': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
      _libraryBindings: z.array(z.unknown()).optional().describe("Token/style bindings applied during creation"),
    }),
  'create_section': z.object({
      id: z.string(),
      name: z.string(),
      x: z.number(),
      y: z.number(),
    }),
  'group_nodes': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      childCount: z.number(),
    }),
  'flatten_node': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
      error: z.string().optional(),
    }),
  'boolean_operation': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number(),
      height: z.number(),
      visible: z.boolean(),
    }),
  'get_annotations': z.object({
      nodes: z.array(z.object({
          nodeId: z.string(),
          nodeName: z.string(),
          annotations: z.array(z.record(z.unknown())),
        })),
      count: z.number(),
    }),
  'set_annotation': z.object({
      ok: z.boolean(),
      nodeId: z.string(),
      count: z.number(),
    }),
  'set_multiple_annotations': z.object({
      succeeded: z.number(),
      failed: z.number(),
      results: z.array(z.record(z.unknown())),
    }),
  'clear_annotations': z.object({
      cleared: z.number(),
    }),
  'get_reactions': z.object({
      nodes: z.array(z.object({
          nodeId: z.string(),
          nodeName: z.string(),
          reactions: z.array(z.record(z.unknown())),
        })),
      count: z.number(),
    }),
  'analyze_prototype_flow': z.object({
      graph: z.record(z.unknown()).optional(),
      mermaid: z.string().optional(),
      markdown: z.string().optional(),
      message: z.string().optional(),
      hint: z.string().optional(),
    }),
  'add_reaction': z.object({
      ok: z.boolean().optional(),
      reactionCount: z.number().optional(),
      results: z.array(z.record(z.unknown())).optional(),
    }),
  'remove_reaction': z.object({
      ok: z.boolean(),
      removed: z.number().optional(),
      remaining: z.number().optional(),
      error: z.string().optional(),
    }),
  'set_reactions': z.object({
      ok: z.boolean(),
      reactionCount: z.number().optional(),
      error: z.string().optional(),
    }),
  'connect_screens': z.object({
      connected: z.number(),
      total: z.number(),
      failures: z.array(z.record(z.unknown())).optional(),
      flowAnalysis: z.record(z.unknown()).optional(),
      hint: z.string().optional(),
    }),
  'lint_check': z.object({
      summary: z.object({
        total: z.number(),
        pass: z.number(),
        violations: z.number(),
      }),
      categories: z.array(z.object({
          rule: z.string(),
          count: z.number(),
          nodes: z.array(z.record(z.unknown())),
        })),
      pagination: z.record(z.unknown()).optional(),
      scope: z.record(z.unknown()).optional(),
    }),
  'lint_fix': z.object({
      fixed: z.number(),
      failed: z.number(),
      errors: z.array(z.object({
          nodeId: z.string(),
          error: z.string(),
        })),
    }),
  'lint_rules': z.object({
      rules: z.array(z.object({
          name: z.string(),
          description: z.string(),
          category: z.string(),
          severity: z.string(),
        })),
    }),
  'set_lint_ignore': z.object({
      ok: z.boolean(),
    }),
  'lint_stats': z.record(z.unknown()),
  'verify_design': z.record(z.unknown()),
  'compliance_report': z.object({
      overallScore: z.number(),
      lint: z.record(z.unknown()),
      components: z.record(z.unknown()),
    }),
  'figma_login': z.object({
      ok: z.boolean(),
      url: z.string(),
      message: z.string(),
    }),
  'figma_logout': z.object({
      ok: z.boolean(),
      message: z.string(),
    }),
  'figma_auth_status': z.object({
      method: z.string(),
      expiresAt: z.number().optional(),
    }),
  'create_page': z.object({
      id: z.string(),
      name: z.string(),
    }),
  'rename_page': z.object({
      ok: z.boolean(),
      id: z.string().optional(),
      name: z.string().optional(),
      error: z.string().optional(),
    }),
  'delete_node': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
  'stage_changes': z.object({
      staged: z.number(),
      errors: z.array(z.record(z.unknown())).optional(),
      stagedNodeIds: z.array(z.string()).optional(),
    }),
  'commit_changes': z.object({
      committed: z.number(),
      errors: z.array(z.record(z.unknown())).optional(),
      remainingStaged: z.array(z.string()).optional(),
    }),
  'discard_changes': z.object({
      discarded: z.number(),
      errors: z.array(z.record(z.unknown())).optional(),
      remainingStaged: z.array(z.string()).optional(),
    }),
  'list_staged': z.object({
      staged: z.array(z.record(z.unknown())),
      count: z.number(),
    }),
};

export const GENERATED_TOOL_RESPONSE_EXAMPLES: Record<string, unknown[]> = {
  'ping': [
    {
      "connected": true,
      "latency": "18ms",
      "serverVersion": "0.1.0",
      "pluginVersion": "0.1.0",
      "_hint": "Connection OK. Proceed with your task — do NOT stop here.",
      "result": {
        "ok": true,
        "channel": "design-1"
      }
    },
    {
      "connected": false,
      "error": "Cannot reach the FigCraft relay server.",
      "diagnosis": {
        "stage": "relay_not_running",
        "steps": [
          "The relay server is not running or not reachable.",
          "Ensure FigCraft MCP is running in your IDE.",
          "If already running, try restarting the IDE or the Figma plugin."
        ]
      }
    }
  ],
  'get_mode': [
    {
      "connected": true,
      "latency": "24ms",
      "mode": "library",
      "selectedLibrary": "Acme DS",
      "designContext": {
        "source": "library",
        "collections": [
          {
            "name": "Color",
            "key": "VariableCollectionId:1:2"
          }
        ]
      },
      "libraryComponents": {
        "componentSets": [
          {
            "key": "component-set-key",
            "name": "Button",
            "description": "Primary CTA button",
            "variants": [
              {
                "key": "variant-key-1",
                "name": "Type=Primary, Size=Medium, State=Default",
                "properties": {
                  "Type": "Primary",
                  "Size": "Medium",
                  "State": "Default"
                }
              }
            ]
          }
        ],
        "standalone": [
          {
            "key": "standalone-key",
            "name": "Logo",
            "description": "Brand logo"
          }
        ]
      },
      "_hint": "Library mode — tokens and components loaded. NEXT: Reply to user to gather missing preferences (UI type, platform). Do NOT call any more tools. If user provided everything, reply with design proposal instead."
    },
    {
      "connected": false,
      "error": "Relay is running, but no Figma plugin is connected.",
      "diagnosis": {
        "stage": "plugin_not_open",
        "steps": [
          "Open your Figma file in the Figma desktop app.",
          "Run the FigCraft plugin (Plugins → FigCraft).",
          "Wait for the plugin UI to show a channel ID, then try again."
        ]
      }
    }
  ],
  'set_mode': [
    {
      "mode": "library",
      "description": "Using Figma shared library as token source. Lint checks variable/style bindings."
    }
  ],
  'get_design_guidelines': [
    {
      "mode": "Design Guardian (Library Mode)",
      "selectedLibrary": "My Design System",
      "guidelines": "# Design Guardian — Library Mode Rules..."
    }
  ],
  'get_creation_guide': [
    {
      "topic": "layout",
      "description": "Returns numbered list of layout & structure prevention rules from Quality Engine"
    },
    {
      "topic": "ui-patterns",
      "uiType": "login",
      "description": "Returns login screen template with structure, key decisions, pitfalls, and tone variants"
    }
  ],
  'audit_node': [
    {
      "nodeId": "1:23",
      "nodeName": "Login Button",
      "nodeType": "FRAME",
      "qualityScore": 94,
      "summary": {
        "totalChecked": 12,
        "violations": 2,
        "errors": 0,
        "unsafes": 0,
        "heuristics": 2,
        "styles": 0,
        "autoFixable": 1
      },
      "violations": [],
      "structuralNotes": [],
      "recommendation": "Fix 1 auto-fixable issue, then review the remaining manually."
    }
  ],
  'join_channel': [
    {
      "ok": true,
      "channel": "design-1",
      "message": "Joined channel \"design-1\". Commands will now target this document."
    }
  ],
  'get_channel': [
    {
      "channel": "design-1",
      "connected": true
    }
  ],
  'get_current_page': [
    {
      "id": "0:1",
      "name": "Page 1",
      "childCount": 3,
      "returnedNodes": 2,
      "truncated": true,
      "nodes": [
        {
          "id": "1:10",
          "name": "Dashboard",
          "type": "FRAME"
        },
        {
          "id": "1:20",
          "name": "Settings",
          "type": "FRAME"
        }
      ]
    }
  ],
  'get_design_context': [
    {
      "framework": "react",
      "frameworkHint": "React + TypeScript. Map auto-layout → Flexbox...",
      "summary": {
        "textNodes": 3,
        "imageNodes": 1,
        "variablesUsed": 6,
        "stylesUsed": 2,
        "componentsUsed": 1
      },
      "variables": [
        {
          "id": "VariableID:1:30",
          "name": "color/bg/primary",
          "type": "COLOR",
          "collection": "Color"
        }
      ],
      "styles": [
        {
          "id": "S:abc123",
          "name": "Heading/Large",
          "type": "TEXT"
        }
      ],
      "components": [
        {
          "id": "80:1",
          "key": "abc...",
          "name": "Button",
          "isSet": true,
          "remote": true
        }
      ]
    }
  ],
  'get_document_info': [
    {
      "name": "Acme Product",
      "currentPage": "Page 1",
      "pages": [
        {
          "id": "0:1",
          "name": "Page 1",
          "childCount": 12
        },
        {
          "id": "0:2",
          "name": "Components",
          "childCount": 48
        }
      ]
    }
  ],
  'get_selection': [
    {
      "count": 2,
      "nodes": [
        {
          "id": "1:10",
          "name": "CTA Button",
          "type": "FRAME"
        },
        {
          "id": "1:11",
          "name": "Headline",
          "type": "TEXT"
        }
      ]
    }
  ],
  'list_fonts': [
    {
      "families": [
        "Inter",
        "SF Pro Display",
        "JetBrains Mono"
      ],
      "total": 3
    },
    {
      "family": "Inter",
      "styles": [
        "Regular",
        "Medium",
        "Bold"
      ],
      "count": 3
    }
  ],
  'create_frame': [
    {
      "id": "50:1",
      "name": "Login Screen",
      "type": "FRAME",
      "width": 375,
      "height": 812,
      "visible": true
    }
  ],
  'create_text': [
    {
      "id": "51:1",
      "name": "Welcome back",
      "type": "TEXT",
      "width": 84,
      "height": 17,
      "visible": true
    }
  ],
  'lint_fix_all': [
    {
      "lint": {
        "total": 24,
        "pass": 20,
        "violations": 4,
        "bySeverity": {
          "warning": 3,
          "error": 1
        }
      },
      "fixable": 3,
      "fixed": 3,
      "fixFailed": 0,
      "remaining": 1
    }
  ],
  'set_current_page': [
    {
      "ok": true,
      "pageId": "0:2",
      "pageName": "Components"
    }
  ],
  'export_image': [
    {
      "format": "PNG",
      "size": 18432,
      "base64": "iVBORw0KGgoAAAANSUhEUgAAAAUA"
    }
  ],
  'save_version_history': [
    {
      "ok": true,
      "title": "Before refactor",
      "description": "Checkpoint before layout cleanup"
    }
  ],
  'set_selection': [
    {
      "ok": true,
      "selectedCount": 2,
      "notFound": []
    },
    {
      "ok": true,
      "selectedCount": 1,
      "notFound": [
        "999:1"
      ]
    }
  ],
  'execute_js': [
    {
      "ok": true,
      "result": {
        "pages": [
          "Page 1",
          "Components"
        ]
      }
    },
    {
      "ok": false,
      "error": "figma.notify is not a function"
    }
  ],
  'icon_search': [],
  'icon_collections': [],
  'icon_create': [],
  'image_search': [],
  'image_preview': [],
  'create_image_frame_from_local': [],
  'fill_existing_image_from_local': [],
  'create_svg': [],
  'text_scan': [],
  'search_design_system': [],
  'set_explicit_variable_mode': [
    {
      "ok": true
    }
  ],
  'rename_collection': [
    {
      "ok": true,
      "id": "VariableCollectionId:1:2",
      "name": "Semantic"
    }
  ],
  'add_collection_mode': [
    {
      "ok": true,
      "modeId": "1:1",
      "name": "Dark"
    }
  ],
  'rename_collection_mode': [
    {
      "ok": true
    }
  ],
  'remove_collection_mode': [
    {
      "ok": true
    }
  ],
  'create_variable_alias': [
    {
      "ok": true,
      "variableId": "VariableID:1:40",
      "aliasTo": "color/brand/primary"
    }
  ],
  'list_tokens': [
    {
      "total": 2,
      "showing": 2,
      "tokens": [
        {
          "path": "color.brand.primary",
          "type": "color",
          "value": "#7c3aed",
          "description": "Primary brand color"
        },
        {
          "path": "text.heading.l",
          "type": "typography",
          "value": {
            "fontFamily": "Inter",
            "fontWeight": 700,
            "fontSize": 32
          }
        }
      ]
    }
  ],
  'sync_tokens': [
    {
      "variables": {
        "created": 10,
        "updated": 2,
        "skipped": 1,
        "failed": 0,
        "failures": []
      },
      "styles": {
        "created": 2,
        "updated": 0,
        "skipped": 0,
        "failed": 0,
        "failures": []
      },
      "totalTokens": 15
    }
  ],
  'sync_tokens_multi_mode': [
    {
      "collectionId": "VariableCollectionId:1:2",
      "modes": [
        {
          "modeId": "1:0",
          "name": "Light"
        },
        {
          "modeId": "1:1",
          "name": "Dark"
        }
      ],
      "results": {
        "Light": {
          "variables": {
            "created": 8,
            "updated": 0,
            "skipped": 0,
            "failed": 0,
            "failures": []
          },
          "styles": {
            "created": 2,
            "updated": 0,
            "skipped": 0,
            "failed": 0,
            "failures": []
          },
          "totalTokens": 10
        }
      }
    }
  ],
  'diff_tokens': [
    {
      "summary": {
        "inSync": 8,
        "dtcgAhead": 1,
        "missingInFigma": 2,
        "missingInDtcg": 0
      },
      "diff": [
        {
          "path": "color.brand.primary",
          "status": "in-sync",
          "dtcgValue": "#7c3aed",
          "figmaValue": "#7c3aed"
        },
        {
          "path": "spacing.lg",
          "status": "missing-in-figma",
          "dtcgValue": 24
        }
      ]
    }
  ],
  'reverse_sync_tokens': [
    {
      "ok": true,
      "filePath": "/tmp/tokens.json",
      "tokenCount": 24
    }
  ],
  'cache_tokens': [
    {
      "cached": 24,
      "name": "tokens-light"
    }
  ],
  'list_cached_tokens': [
    {
      "entries": [
        "tokens-light",
        "tokens-dark"
      ]
    }
  ],
  'delete_cached_tokens': [
    {
      "ok": true
    }
  ],
  'scan_styles': [
    {
      "paint": [
        {
          "id": "Style:1",
          "name": "Color/Brand/Primary",
          "paints": 1
        }
      ],
      "text": [
        {
          "id": "Style:2",
          "name": "Text/Heading/L",
          "fontSize": 32,
          "fontName": {
            "family": "Inter",
            "style": "Bold"
          }
        }
      ],
      "effect": [
        {
          "id": "Style:3",
          "name": "Shadow/Card/Default",
          "effects": 1
        }
      ],
      "summary": {
        "paintCount": 1,
        "textCount": 1,
        "effectCount": 1
      }
    }
  ],
  'export_tokens': [
    {
      "Design Tokens": {
        "color/brand/primary": {
          "$value": "#7c3aed",
          "$type": "color",
          "$description": "Primary brand color"
        }
      }
    }
  ],
  'diff_styles': [
    {
      "diff": [
        {
          "path": "color.brand.primary",
          "status": "in-sync",
          "dtcgValue": "#7c3aed",
          "figmaValue": "#7c3aed"
        }
      ],
      "total": 1
    }
  ],
  'register_library_styles': [
    {
      "ok": true,
      "registered": {
        "textStyles": 8,
        "paintStyles": 12,
        "effectStyles": 3
      }
    }
  ],
  'get_registered_styles': [
    {
      "textStyles": [
        {
          "key": "S:1",
          "name": "Text/Heading/L",
          "fontSize": 32,
          "fontFamily": "Inter",
          "fontWeight": "Bold"
        }
      ],
      "paintStyles": [
        {
          "key": "S:2",
          "name": "Color/Brand/Primary",
          "hex": "#7c3aed"
        }
      ],
      "effectStyles": [
        {
          "key": "S:3",
          "name": "Shadow/Card/Default",
          "effectType": "DROP_SHADOW"
        }
      ],
      "_loaded": {
        "text": 1,
        "paint": 1,
        "effect": 1
      }
    }
  ],
  'create_component': [
    {
      "id": "80:1",
      "name": "Button / Primary",
      "type": "COMPONENT",
      "width": 160,
      "height": 48,
      "visible": true
    }
  ],
  'create_component_set': [
    {
      "id": "81:1",
      "name": "Button",
      "type": "COMPONENT_SET",
      "width": 320,
      "height": 48,
      "visible": true
    }
  ],
  'update_component': [
    {
      "id": "80:1",
      "name": "Button / Secondary",
      "type": "COMPONENT",
      "width": 160,
      "height": 48,
      "visible": true
    }
  ],
  'delete_component': [
    {
      "ok": true
    }
  ],
  'create_instance': [
    {
      "id": "60:1",
      "name": "Button",
      "type": "INSTANCE"
    }
  ],
  'create_instances': [],
  'create_component_from_node': [],
  'layout_component_set': [
    {
      "ok": true,
      "componentSetId": "81:1",
      "positioned": 18,
      "grid": {
        "columns": 3,
        "rows": 6,
        "columnAxis": "State",
        "rowAxes": [
          "Size",
          "Style"
        ]
      },
      "size": {
        "width": 560,
        "height": 480
      }
    }
  ],
  'bind_component_property': [
    {
      "ok": true,
      "action": "single",
      "bindingsProcessed": 4,
      "variantsTargeted": 6,
      "totalBound": 24,
      "totalNotFound": 0,
      "results": [
        {
          "propertyName": "Label",
          "bound": 6,
          "notFound": 0
        },
        {
          "propertyName": "ShowIcon",
          "bound": 6,
          "notFound": 0
        }
      ]
    },
    {
      "ok": true,
      "action": "batch",
      "created": 3,
      "total": 3,
      "items": [
        {
          "nodeId": "1:24",
          "ok": true,
          "bindingsProcessed": 2,
          "totalBound": 2
        },
        {
          "nodeId": "1:30",
          "ok": true,
          "bindingsProcessed": 2,
          "totalBound": 2
        },
        {
          "nodeId": "1:36",
          "ok": true,
          "bindingsProcessed": 2,
          "totalBound": 2
        }
      ]
    }
  ],
  'swap_instance': [
    {
      "id": "82:1",
      "name": "Button / Primary",
      "type": "INSTANCE",
      "width": 160,
      "height": 48,
      "visible": true
    }
  ],
  'detach_instance': [
    {
      "id": "83:1",
      "name": "Button / Primary",
      "type": "FRAME",
      "width": 160,
      "height": 48,
      "visible": true
    }
  ],
  'reset_instance_overrides': [
    {
      "ok": true
    }
  ],
  'get_instance_overrides': [
    {
      "nodeId": "82:1",
      "nodeName": "Button / Primary",
      "properties": [
        {
          "key": "State",
          "type": "VARIANT",
          "value": "Default"
        }
      ]
    }
  ],
  'set_instance_overrides': [
    {
      "succeeded": 3,
      "failed": 0
    }
  ],
  'add_component_property': [
    {
      "ok": true,
      "key": "Label#0:1",
      "properties": [
        "State",
        "Label#0:1"
      ]
    }
  ],
  'update_component_property': [
    {
      "ok": true,
      "properties": [
        "State",
        "Label"
      ]
    }
  ],
  'delete_component_property': [
    {
      "ok": true,
      "properties": [
        "State"
      ]
    }
  ],
  'audit_components': [
    {
      "summary": {
        "totalComponents": 4,
        "totalIssues": 1
      },
      "components": [
        {
          "id": "80:1",
          "name": "Button / Primary",
          "propertyCount": 2
        }
      ],
      "issues": [
        {
          "nodeId": "80:1",
          "name": "Button / Primary",
          "issue": "Missing description"
        }
      ]
    }
  ],
  'get_code_connect_metadata': [
    {
      "componentName": "Button",
      "nodeId": "80:1",
      "isComponentSet": true,
      "remote": false,
      "figmaUrl": "https://figma.com/design/abc/Button?node-id=80-1",
      "properties": [
        {
          "bareName": "Label",
          "figmaKey": "Label#42:0",
          "type": "TEXT",
          "defaultValue": "Button"
        },
        {
          "bareName": "Style",
          "figmaKey": "Style",
          "type": "VARIANT",
          "variantOptions": [
            "Primary",
            "Secondary",
            "Ghost"
          ]
        }
      ],
      "slots": {
        "textSlots": [
          {
            "name": "label",
            "characters": "Button"
          }
        ],
        "instanceSlots": []
      },
      "summary": {
        "propertyCount": 2,
        "textProperties": 1,
        "booleanProperties": 0,
        "instanceSwapProperties": 0,
        "variantProperties": 1,
        "slotProperties": 0,
        "textSlotCount": 1,
        "instanceSlotCount": 0
      }
    }
  ],
  'preflight_library_publish': [
    {
      "ready": false,
      "summary": {
        "components": 12,
        "componentSets": 3,
        "variables": 48,
        "styles": 6,
        "blockerCount": 2,
        "warningCount": 5
      },
      "blockers": [
        {
          "severity": "blocker",
          "category": "component",
          "target": "Button",
          "nodeId": "80:1",
          "message": "Component set missing description",
          "suggestion": "update_component(nodeId:\"80:1\", description:\"...\")"
        }
      ]
    }
  ],
  'list_library_collections': [
    [
      {
        "key": "VarCollectionKey:1",
        "name": "Color",
        "libraryName": "Acme DS"
      }
    ]
  ],
  'list_library_variables': [
    {
      "count": 1,
      "variables": [
        {
          "key": "VariableKey:1",
          "name": "color/brand/primary",
          "resolvedType": "COLOR"
        }
      ]
    }
  ],
  'import_library_variable': [
    {
      "id": "VariableID:9:1",
      "name": "color/brand/primary",
      "resolvedType": "COLOR",
      "description": "Primary brand color",
      "key": "VariableKey:1"
    }
  ],
  'list_library_styles': [
    {
      "count": 1,
      "styles": [
        {
          "key": "StyleKey:1",
          "file_key": "abc123",
          "node_id": "1:2",
          "style_type": "TEXT",
          "name": "Text/Heading/L",
          "description": "Display heading"
        }
      ]
    }
  ],
  'get_library_style_details': [
    {
      "count": 1,
      "styles": [
        {
          "key": "StyleKey:1",
          "file_key": "abc123",
          "node_id": "1:2",
          "style_type": "TEXT",
          "name": "Text/Heading/L",
          "description": "Display heading",
          "properties": {
            "fontFamily": "Inter",
            "fontSize": 32
          }
        }
      ]
    }
  ],
  'sync_library_styles': [
    {
      "ok": true,
      "discovered": {
        "total": 12,
        "text": 4,
        "fill": 6,
        "effect": 2
      },
      "diff": {
        "added": [],
        "removed": [],
        "modified": [],
        "unchanged": 12
      },
      "registered": {
        "ok": true,
        "registered": {
          "textStyles": 4,
          "paintStyles": 6,
          "effectStyles": 2
        }
      }
    }
  ],
  'import_library_style': [
    {
      "id": "Style:21",
      "name": "Text/Heading/L",
      "type": "TEXT",
      "key": "StyleKey:1",
      "description": "Display heading"
    }
  ],
  'create_line': [
    {
      "id": "90:1",
      "name": "Divider",
      "type": "LINE",
      "width": 320,
      "height": 0,
      "visible": true
    }
  ],
  'create_star': [
    {
      "id": "90:2",
      "name": "Star",
      "type": "STAR",
      "width": 100,
      "height": 100,
      "visible": true
    }
  ],
  'create_polygon': [
    {
      "id": "90:3",
      "name": "Triangle",
      "type": "POLYGON",
      "width": 100,
      "height": 100,
      "visible": true
    }
  ],
  'create_rectangle': [
    {
      "id": "90:4",
      "name": "Card Background",
      "type": "RECTANGLE",
      "width": 320,
      "height": 200,
      "visible": true
    }
  ],
  'create_ellipse': [
    {
      "id": "90:5",
      "name": "Avatar",
      "type": "ELLIPSE",
      "width": 48,
      "height": 48,
      "visible": true
    }
  ],
  'create_section': [
    {
      "id": "91:1",
      "name": "Onboarding",
      "x": 0,
      "y": 0
    }
  ],
  'group_nodes': [
    {
      "id": "93:1",
      "name": "Group",
      "type": "GROUP",
      "childCount": 3
    }
  ],
  'flatten_node': [
    {
      "id": "92:1",
      "name": "Flattened Shape",
      "type": "VECTOR",
      "width": 120,
      "height": 120,
      "visible": true
    }
  ],
  'boolean_operation': [
    {
      "id": "93:1",
      "name": "Merged Shape",
      "type": "BOOLEAN_OPERATION",
      "width": 160,
      "height": 120,
      "visible": true
    }
  ],
  'get_annotations': [
    {
      "nodes": [
        {
          "nodeId": "100:1",
          "nodeName": "Login Form",
          "annotations": [
            {
              "label": "Check spacing",
              "properties": [
                {
                  "type": "design"
                }
              ]
            }
          ]
        }
      ],
      "count": 1
    }
  ],
  'set_annotation': [
    {
      "ok": true,
      "nodeId": "100:1",
      "count": 2
    }
  ],
  'set_multiple_annotations': [
    {
      "succeeded": 2,
      "failed": 0,
      "results": [
        {
          "nodeId": "100:1",
          "ok": true
        },
        {
          "nodeId": "100:2",
          "ok": true
        }
      ]
    }
  ],
  'clear_annotations': [
    {
      "cleared": 3
    }
  ],
  'get_reactions': [
    {
      "nodes": [
        {
          "nodeId": "101:1",
          "nodeName": "CTA Button",
          "reactions": [
            {
              "trigger": {
                "type": "ON_CLICK"
              },
              "actions": [
                {
                  "type": "NODE",
                  "destinationId": "101:2"
                }
              ]
            }
          ]
        }
      ],
      "count": 1
    }
  ],
  'analyze_prototype_flow': [
    {
      "graph": {
        "stats": {
          "totalScreens": 2,
          "totalInteractions": 1
        },
        "nodes": [],
        "edges": []
      },
      "mermaid": "graph TD\n  A --> B",
      "markdown": "# Prototype Flow Documentation"
    }
  ],
  'add_reaction': [
    {
      "ok": true,
      "reactionCount": 1
    }
  ],
  'remove_reaction': [
    {
      "ok": true,
      "removed": 1,
      "remaining": 0
    }
  ],
  'set_reactions': [
    {
      "ok": true,
      "reactionCount": 2
    }
  ],
  'connect_screens': [
    {
      "connected": 3,
      "total": 3,
      "flowAnalysis": {
        "totalScreens": 4,
        "totalInteractions": 3,
        "entryPoints": [],
        "deadEnds": [],
        "loops": 0
      }
    }
  ],
  'lint_check': [
    {
      "summary": {
        "total": 10,
        "pass": 8,
        "violations": 2
      },
      "categories": [
        {
          "rule": "default-name",
          "count": 1,
          "nodes": [
            {
              "nodeId": "1:2",
              "nodeName": "Frame 1",
              "suggestion": "Rename the frame semantically.",
              "autoFixable": false
            }
          ]
        }
      ],
      "scope": {
        "type": "page",
        "count": 1,
        "pageName": "Page 1"
      }
    }
  ],
  'lint_fix': [
    {
      "fixed": 2,
      "failed": 0,
      "errors": []
    }
  ],
  'lint_rules': [
    {
      "rules": [
        {
          "name": "default-name",
          "description": "Flags default Figma layer names.",
          "category": "naming",
          "severity": "warning"
        }
      ]
    }
  ],
  'set_lint_ignore': [
    {
      "ok": true
    }
  ],
  'lint_stats': [
    {
      "sortBy": "frequency",
      "description": "Returns session stats sorted by violation frequency"
    }
  ],
  'verify_design': [
    {
      "nodeId": "1:23",
      "fix": true,
      "exportImage": true,
      "description": "Lint + fix + export screenshot in one call"
    }
  ],
  'compliance_report': [
    {
      "overallScore": 92,
      "lint": {
        "score": 95,
        "nodesChecked": 20,
        "passed": 19,
        "violations": 1
      },
      "components": {
        "score": 89,
        "total": 8,
        "issues": 1
      }
    }
  ],
  'figma_login': [
    {
      "ok": true,
      "url": "https://www.figma.com/oauth?client_id=example",
      "message": "Please open this URL in your browser to authorize figcraft with Figma."
    }
  ],
  'figma_logout': [
    {
      "ok": true,
      "message": "Figma credentials cleared."
    }
  ],
  'figma_auth_status': [
    {
      "method": "oauth",
      "expiresAt": 1893456000000
    }
  ],
  'create_page': [
    {
      "id": "0:3",
      "name": "Marketing"
    }
  ],
  'rename_page': [
    {
      "ok": true,
      "id": "0:3",
      "name": "Marketing"
    }
  ],
  'delete_node': [
    {
      "ok": true
    }
  ],
  'stage_changes': [
    {
      "staged": 3,
      "errors": [],
      "stagedNodeIds": [
        "1:23",
        "1:24",
        "1:25"
      ]
    }
  ],
  'commit_changes': [
    {
      "committed": 3,
      "errors": [],
      "remainingStaged": []
    }
  ],
  'discard_changes': [
    {
      "discarded": 2,
      "errors": [],
      "remainingStaged": [
        "1:25"
      ]
    }
  ],
  'list_staged': [
    {
      "staged": [
        {
          "nodeId": "1:23",
          "name": "Login Screen"
        }
      ],
      "count": 1
    }
  ],
};

export const GENERATED_ENDPOINT_METHOD_RESPONSE_SCHEMAS: Record<string, Record<string, z.ZodTypeAny>> = {
  'nodes': {
    'get': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      width: z.number().optional(),
      height: z.number().optional(),
      children: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
        })).optional(),
    }),
    'get_batch': z.object({
      count: z.number(),
      nodes: z.array(z.unknown()),
    }),
    'list': z.object({
      count: z.number(),
      nodes: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
        })),
      _error: z.string().optional(),
      _sizeKB: z.number().optional(),
      _limitKB: z.number().optional(),
      method: z.string().optional(),
      warning: z.string().optional(),
      hints: z.array(z.string()).optional(),
      _preview: z.string().optional(),
    }),
    'update': z.object({
      results: z.array(z.object({
          nodeId: z.string(),
          ok: z.boolean(),
          error: z.string().optional(),
        })),
    }),
    'delete': z.object({
      results: z.array(z.object({
          nodeId: z.string(),
          ok: z.boolean(),
          error: z.string().optional(),
        })),
    }),
    'clone': z.object({
      results: z.array(z.object({
          id: z.string(),
          ok: z.boolean(),
          error: z.string().optional(),
        })),
    }),
    'reparent': z.object({
      results: z.array(z.object({
          id: z.string(),
          ok: z.boolean(),
          error: z.string().optional(),
        })),
    }),
  },
  'text': {
    'set_content': z.object({
      ok: z.boolean(),
      action: z.string().optional().describe("'single' for single-node update, 'batch' when items[] was used"),
      created: z.number().optional().describe("Batch mode only: count of successfully updated items"),
      total: z.number().optional().describe("Batch mode only: total items processed"),
      results: z.array(z.object({
          nodeId: z.string(),
          ok: z.boolean(),
          error: z.string().optional(),
        })).optional().describe("Batch mode only: per-item outcome"),
      error: z.string().optional(),
    }),
    'set_range': z.object({
      ok: z.boolean(),
      characterCount: z.number().optional(),
      results: z.array(z.object({
          index: z.number().optional(),
          ok: z.boolean().optional(),
          error: z.string().optional(),
        })).optional(),
    }),
  },
  'components': {
    'list': z.object({
      count: z.number(),
      components: z.array(z.object({
          id: z.string(),
          name: z.string(),
          description: z.string().optional(),
          key: z.string().optional(),
        })),
    }),
    'list_library': z.object({
      count: z.number(),
      components: z.array(z.object({
          key: z.string(),
          name: z.string(),
          description: z.string().optional(),
        })),
    }),
    'get': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      description: z.string().optional(),
      key: z.string().optional(),
      componentPropertyDefinitions: z.record(z.unknown()).optional(),
    }),
    'list_properties': z.object({
      properties: z.array(z.object({
          key: z.string(),
          type: z.string(),
          defaultValue: z.unknown().optional(),
          variantOptions: z.array(z.string()).optional(),
        })),
    }),
  },
  'variables_ep': {
    'list': z.object({
      count: z.number(),
      variables: z.array(z.object({
          id: z.string(),
          name: z.string(),
          resolvedType: z.string(),
          description: z.string().optional(),
          collectionId: z.string(),
          collectionName: z.string(),
          scopes: z.array(z.string()),
          codeSyntax: z.record(z.unknown()).optional().describe("Code syntax per platform {WEB, ANDROID, iOS}. Present only when set."),
          valuesByMode: z.record(z.unknown()),
        })),
    }),
    'get': z.object({
      id: z.string(),
      name: z.string(),
      resolvedType: z.string(),
      description: z.string().optional(),
      collectionId: z.string(),
      collectionName: z.string().optional(),
      scopes: z.array(z.string()),
      codeSyntax: z.unknown().optional(),
      valuesByMode: z.record(z.unknown()),
      error: z.string().optional(),
    }),
    'list_collections': z.array(z.object({
          id: z.string(),
          name: z.string(),
          modes: z.array(z.object({
          modeId: z.string(),
          name: z.string(),
        })),
          variableCount: z.number(),
        })),
    'get_bindings': z.object({
      nodeId: z.string(),
      bindings: z.record(z.unknown()),
      error: z.string().optional(),
    }),
    'set_binding': z.object({
      ok: z.boolean(),
      action: z.string().optional().describe("'bound' when a variable was attached, 'unbound' when variableId was null"),
      error: z.string().optional(),
    }),
    'create': z.object({
      id: z.string(),
      name: z.string(),
      resolvedType: z.string(),
      error: z.string().optional(),
    }),
    'update': z.object({
      ok: z.boolean(),
      id: z.string().optional(),
      error: z.string().optional(),
    }),
    'batch_update': z.object({
      updated: z.number(),
      total: z.number(),
      results: z.array(z.unknown()),
    }),
    'delete': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
    'create_collection': z.object({
      id: z.string(),
      name: z.string(),
      modes: z.array(z.object({
          modeId: z.string(),
          name: z.string(),
        })),
    }),
    'delete_collection': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
    'batch_create': z.object({
      created: z.number(),
      skipped: z.number(),
      failed: z.number(),
      errors: z.array(z.object({
          name: z.string(),
          error: z.string(),
        })),
      collectionId: z.string(),
    }),
    'export': z.object({
      count: z.number(),
      variables: z.array(z.object({
          path: z.string(),
          type: z.string(),
          valuesByMode: z.record(z.unknown()),
          description: z.string().optional(),
          scopes: z.array(z.string()).optional(),
          aliasOf: z.record(z.string()).optional(),
        })),
    }),
    'set_code_syntax': z.object({
      ok: z.boolean(),
      variableId: z.string(),
      variableName: z.string(),
      applied: z.array(z.string()).optional(),
    }),
    'batch_bind': z.object({
      succeeded: z.number(),
      failed: z.number(),
      total: z.number(),
      errors: z.array(z.record(z.unknown())).optional(),
    }),
    'set_values_multi_mode': z.object({
      ok: z.boolean(),
      variableId: z.string(),
      variableName: z.string(),
      set: z.number(),
      total: z.number(),
      errors: z.array(z.record(z.unknown())).optional(),
    }),
    'extend_collection': z.object({
      id: z.string(),
      name: z.string(),
      isExtension: z.boolean(),
      rootVariableCollectionId: z.string(),
      modes: z.array(z.record(z.unknown())),
      variableCount: z.number(),
    }),
    'get_overrides': z.object({
      collectionId: z.string(),
      collectionName: z.string(),
      rootVariableCollectionId: z.string(),
      overrideCount: z.number(),
      overrides: z.array(z.record(z.unknown())),
    }),
    'remove_override': z.object({
      ok: z.boolean(),
    }),
  },
  'styles_ep': {
    'list': z.object({
      count: z.number(),
      styles: z.array(z.object({
          id: z.string(),
          name: z.string(),
          type: z.string(),
          description: z.string().optional(),
          paints: z.array(z.record(z.unknown())).optional(),
          fontName: z.unknown().optional(),
          fontSize: z.number().optional(),
          letterSpacing: z.unknown().optional(),
          lineHeight: z.unknown().optional(),
          textCase: z.string().optional(),
          textDecoration: z.string().optional(),
          effects: z.array(z.record(z.unknown())).optional(),
        })),
    }),
    'get': z.object({
      id: z.string(),
      name: z.string(),
      type: z.string(),
      description: z.string().optional(),
      paints: z.array(z.record(z.unknown())).optional(),
      fontName: z.unknown().optional(),
      fontSize: z.number().optional(),
      letterSpacing: z.unknown().optional(),
      lineHeight: z.unknown().optional(),
      textCase: z.string().optional(),
      textDecoration: z.string().optional(),
      effects: z.array(z.record(z.unknown())).optional(),
      error: z.string().optional(),
    }),
    'create_paint': z.object({
      id: z.string(),
      name: z.string(),
    }),
    'update_paint': z.object({
      id: z.string(),
      name: z.string(),
      error: z.string().optional(),
    }),
    'update_text': z.object({
      id: z.string(),
      name: z.string(),
      fontSize: z.number().optional(),
      error: z.string().optional(),
    }),
    'update_effect': z.object({
      id: z.string(),
      name: z.string(),
      error: z.string().optional(),
    }),
    'delete': z.object({
      ok: z.boolean(),
      error: z.string().optional(),
    }),
    'sync': z.object({
      created: z.number(),
      updated: z.number(),
      skipped: z.number(),
      failed: z.number(),
      failures: z.array(z.object({
          path: z.string(),
          error: z.string(),
        })),
    }),
    'create_text': z.object({
      id: z.string(),
      name: z.string(),
      fontSize: z.number().optional(),
      alreadyExists: z.boolean().optional(),
    }),
    'create_effect': z.object({
      id: z.string(),
      name: z.string(),
      alreadyExists: z.boolean().optional(),
    }),
  },
};

export const GENERATED_ENDPOINT_METHOD_RESPONSE_EXAMPLES: Record<string, Record<string, unknown[]>> = {
  'nodes': {
    'get': [
      {
        "id": "1:23",
        "name": "Auth Screen",
        "type": "FRAME",
        "width": 402,
        "height": 874,
        "children": [
          {
            "id": "1:24",
            "name": "Login Form",
            "type": "FRAME"
          }
        ]
      }
    ],
    'get_batch': [
      {
        "nodeIds": [
          "1:1",
          "1:2",
          "1:3"
        ],
        "detail": "standard"
      }
    ],
    'list': [
      {
        "count": 1,
        "nodes": [
          {
            "id": "1:10",
            "name": "Login Button",
            "type": "FRAME"
          }
        ]
      }
    ],
    'update': [
      {
        "results": [
          {
            "nodeId": "30:1",
            "ok": true
          }
        ]
      }
    ],
    'delete': [
      {
        "results": [
          {
            "nodeId": "30:1",
            "ok": true
          }
        ]
      }
    ],
    'clone': [
      {
        "results": [
          {
            "id": "50:1",
            "ok": true
          }
        ]
      }
    ],
    'reparent': [
      {
        "results": [
          {
            "id": "30:1",
            "ok": true
          }
        ]
      }
    ],
  },
  'text': {
    'set_content': [
      {
        "ok": true,
        "action": "single"
      },
      {
        "ok": true,
        "action": "batch",
        "created": 3,
        "total": 3,
        "results": [
          {
            "nodeId": "1:24",
            "ok": true
          },
          {
            "nodeId": "1:25",
            "ok": true
          },
          {
            "nodeId": "1:26",
            "ok": true
          }
        ]
      }
    ],
    'set_range': [
      {
        "ok": true,
        "characterCount": 42,
        "results": [
          {
            "index": 0,
            "ok": true
          }
        ]
      }
    ],
  },
  'components': {
    'list': [
      {
        "count": 1,
        "components": [
          {
            "id": "12:1",
            "name": "Button / Primary",
            "key": "button-primary-key"
          }
        ]
      }
    ],
    'list_library': [
      {
        "count": 1,
        "components": [
          {
            "key": "library-button-primary",
            "name": "Button / Primary",
            "description": "Primary CTA button"
          }
        ]
      }
    ],
    'get': [
      {
        "id": "12:1",
        "name": "Button / Primary",
        "type": "COMPONENT",
        "description": "Main call-to-action button",
        "key": "button-primary-key"
      }
    ],
    'list_properties': [
      {
        "properties": [
          {
            "key": "State",
            "type": "VARIANT",
            "defaultValue": "Default",
            "variantOptions": [
              "Default",
              "Pressed"
            ]
          }
        ]
      }
    ],
  },
  'variables_ep': {
    'list': [
      {
        "count": 1,
        "variables": [
          {
            "id": "VariableID:1:12",
            "name": "color/brand/primary",
            "resolvedType": "COLOR",
            "description": "Primary brand color",
            "collectionId": "VariableCollectionId:1:2",
            "collectionName": "Primitives",
            "scopes": [
              "ALL_FILLS"
            ],
            "valuesByMode": {
              "Default": "#7c3aed"
            }
          }
        ]
      }
    ],
    'get': [
      {
        "id": "VariableID:1:12",
        "name": "color/brand/primary",
        "resolvedType": "COLOR",
        "description": "Primary brand color",
        "collectionId": "VariableCollectionId:1:2",
        "collectionName": "Primitives",
        "scopes": [
          "ALL_FILLS"
        ],
        "codeSyntax": {
          "WEB": "var(--color-brand-primary)"
        },
        "valuesByMode": {
          "Default": "#7c3aed"
        }
      }
    ],
    'list_collections': [
      [
        {
          "id": "VariableCollectionId:1:2",
          "name": "Primitives",
          "modes": [
            {
              "modeId": "1:0",
              "name": "Default"
            }
          ],
          "variableCount": 12
        }
      ]
    ],
    'get_bindings': [
      {
        "nodeId": "1:24",
        "bindings": {
          "fills": [
            {
              "variableId": "VariableID:1:12",
              "variableName": "color/brand/primary",
              "collectionId": "VariableCollectionId:1:2"
            }
          ]
        }
      }
    ],
    'set_binding': [
      {
        "ok": true,
        "action": "bound"
      },
      {
        "ok": true,
        "action": "unbound"
      }
    ],
    'create': [
      {
        "id": "VariableID:1:30",
        "name": "spacing/md",
        "resolvedType": "FLOAT"
      }
    ],
    'update': [
      {
        "ok": true,
        "id": "VariableID:1:30"
      }
    ],
    'batch_update': [
      {
        "updated": 3,
        "total": 3,
        "results": [
          {
            "variableId": "VariableID:1:30",
            "ok": true
          }
        ]
      }
    ],
    'delete': [
      {
        "ok": true
      }
    ],
    'create_collection': [
      {
        "id": "VariableCollectionId:1:2",
        "name": "Semantic",
        "modes": [
          {
            "modeId": "1:0",
            "name": "Mode 1"
          }
        ]
      }
    ],
    'delete_collection': [
      {
        "ok": true
      }
    ],
    'batch_create': [
      {
        "created": 2,
        "skipped": 0,
        "failed": 0,
        "errors": [],
        "collectionId": "VariableCollectionId:1:2"
      }
    ],
    'export': [
      {
        "count": 1,
        "variables": [
          {
            "path": "color.brand.primary",
            "type": "color",
            "valuesByMode": {
              "Default": "#7c3aed"
            },
            "description": "Primary brand color",
            "scopes": [
              "ALL_FILLS"
            ]
          }
        ]
      }
    ],
    'set_code_syntax': [
      {
        "ok": true,
        "variableId": "VariableID:1:30",
        "variableName": "color/bg/primary",
        "applied": [
          "WEB",
          "iOS"
        ]
      }
    ],
    'batch_bind': [
      {
        "succeeded": 108,
        "failed": 0,
        "total": 108
      }
    ],
    'set_values_multi_mode': [
      {
        "ok": true,
        "variableId": "VariableID:1:30",
        "variableName": "color/bg/primary",
        "set": 2,
        "total": 2
      }
    ],
    'extend_collection': [
      {
        "id": "VariableCollectionId:2:1",
        "name": "Brand A",
        "isExtension": true,
        "rootVariableCollectionId": "VariableCollectionId:1:1",
        "modes": [
          {
            "modeId": "2:0",
            "name": "Light"
          }
        ],
        "variableCount": 50
      }
    ],
    'get_overrides': [
      {
        "collectionId": "VariableCollectionId:2:1",
        "collectionName": "Brand A",
        "rootVariableCollectionId": "VariableCollectionId:1:1",
        "overrideCount": 5,
        "overrides": []
      }
    ],
    'remove_override': [
      {
        "ok": true
      }
    ],
  },
  'styles_ep': {
    'list': [
      {
        "count": 2,
        "styles": [
          {
            "id": "Style:1",
            "name": "Color/Brand/Primary",
            "type": "PAINT",
            "description": "Primary brand color",
            "paints": [
              {
                "type": "SOLID",
                "visible": true,
                "opacity": 1,
                "color": "#7c3aed"
              }
            ]
          },
          {
            "id": "Style:2",
            "name": "Text/Heading/L",
            "type": "TEXT",
            "fontName": {
              "family": "Inter",
              "style": "Bold"
            },
            "fontSize": 32
          }
        ]
      }
    ],
    'get': [
      {
        "id": "Style:1",
        "name": "Color/Brand/Primary",
        "type": "PAINT",
        "description": "Primary brand color",
        "paints": [
          {
            "type": "SOLID",
            "visible": true,
            "opacity": 1,
            "color": "#7c3aed"
          }
        ]
      }
    ],
    'create_paint': [
      {
        "id": "Style:10",
        "name": "Color/Brand/Primary"
      }
    ],
    'update_paint': [
      {
        "id": "Style:10",
        "name": "Color/Brand/Accent"
      }
    ],
    'update_text': [
      {
        "id": "Style:11",
        "name": "Text/Heading/L",
        "fontSize": 32
      }
    ],
    'update_effect': [
      {
        "id": "Style:12",
        "name": "Shadow/Card/Default"
      }
    ],
    'delete': [
      {
        "ok": true
      }
    ],
    'sync': [
      {
        "created": 2,
        "updated": 1,
        "skipped": 0,
        "failed": 0,
        "failures": []
      }
    ],
    'create_text': [
      {
        "id": "S:style1",
        "name": "Text/Heading/L",
        "fontSize": 32
      }
    ],
    'create_effect': [
      {
        "id": "S:effect1",
        "name": "Shadow/Card/Default"
      }
    ],
  },
};
