/**
 * AUTO-GENERATED by scripts/compile-schema.ts — DO NOT EDIT
 *
 * Simple bridge tools compiled from schema/tools.yaml.
 * These tools forward params to the Figma plugin via bridge.request().
 *
 * Re-generate: npm run schema
 */

import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { Bridge } from '../bridge.js';


export interface GeneratedToolRegistrationOptions {
  include?: ReadonlySet<string>;
}

function shouldRegisterGeneratedTool(include: ReadonlySet<string> | undefined, toolName: string): boolean {
  return !include || include.has(toolName);
}

export function registerGeneratedTools(
  server: McpServer,
  bridge: Bridge,
  options: GeneratedToolRegistrationOptions = {},
): void {
  const include = options.include;
  if (shouldRegisterGeneratedTool(include, 'get_selection')) {
    server.tool(
    'get_selection',
    "Get the currently selected nodes in Figma with full compressed data.",
    {},
    async (params) => {
      const result = await bridge.request('get_selection', {});
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'list_fonts')) {
    server.tool(
    'list_fonts',
    "List available font families in the Figma environment. Pass family to get all available styles for that family. Use before creating text to ensure the chosen font is available.",
    {
      family: z.string().optional().describe("Font family name to get available styles for"),
    },
    async ({ family }) => {
      const result = await bridge.request('list_fonts', { family });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'create_frame')) {
    server.tool(
    'create_frame',
    "Create a frame node with optional auto-layout, fills, corner radius, and parent. Supports all common layout properties for building UI structures.",
    {
      name: z.string().optional().describe("Frame name (default: \"Frame\")"),
      x: z.number().optional().describe("X position"),
      y: z.number().optional().describe("Y position"),
      width: z.number().optional().describe("Width (default: 100)"),
      height: z.number().optional().describe("Height (default: 100)"),
      fill: z.string().optional().describe("Fill color as hex (e.g. \"#FFFFFF\")"),
      layoutMode: z.enum(['HORIZONTAL', 'VERTICAL']).optional().describe("Auto-layout direction"),
      itemSpacing: z.number().optional().describe("Spacing between children"),
      paddingLeft: z.number().optional().describe("Left padding"),
      paddingRight: z.number().optional().describe("Right padding"),
      paddingTop: z.number().optional().describe("Top padding"),
      paddingBottom: z.number().optional().describe("Bottom padding"),
      cornerRadius: z.number().optional().describe("Corner radius"),
      parentId: z.string().optional().describe("Parent node ID to append into"),
      layoutSizingHorizontal: z.enum(['FIXED', 'HUG', 'FILL']).optional().describe("Horizontal sizing mode (set AFTER parent append)"),
      layoutSizingVertical: z.enum(['FIXED', 'HUG', 'FILL']).optional().describe("Vertical sizing mode (set AFTER parent append)"),
      primaryAxisAlignItems: z.enum(['MIN', 'CENTER', 'MAX', 'SPACE_BETWEEN']).optional().describe("Primary axis alignment"),
      counterAxisAlignItems: z.enum(['MIN', 'CENTER', 'MAX']).optional().describe("Counter axis alignment"),
    },
    async (params) => {
      const result = await bridge.request('create_frame', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'create_text')) {
    server.tool(
    'create_text',
    "Create a text node with specified content, font, size, and color. Supports font family/style selection with fallback chain.",
    {
      content: z.string().optional().describe("Text content to display"),
      name: z.string().optional().describe("Node name (defaults to content)"),
      x: z.number().optional().describe("X position"),
      y: z.number().optional().describe("Y position"),
      fontSize: z.number().optional().describe("Font size (default: 14)"),
      fontFamily: z.string().optional().describe("Font family (default: \"Inter\")"),
      fontStyle: z.string().optional().describe("Font style (default: \"Regular\")"),
      fill: z.string().optional().describe("Text color as hex (e.g. \"#000000\")"),
      lineHeight: z.number().optional().describe("Line height in pixels"),
      letterSpacing: z.number().optional().describe("Letter spacing in pixels"),
      textAlignHorizontal: z.enum(['LEFT', 'CENTER', 'RIGHT', 'JUSTIFIED']).optional().describe("Horizontal text alignment"),
      parentId: z.string().optional().describe("Parent node ID to append into"),
    },
    async (params) => {
      const result = await bridge.request('create_text', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'set_current_page')) {
    server.tool(
    'set_current_page',
    "Switch to a different page by name or ID. Warning: this changes the context for all subsequent operations.",
    {
      nameOrId: z.string().describe("Page name or page ID"),
    },
    async ({ nameOrId }) => {
      const result = await bridge.request('set_current_page', { nameOrId });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'save_version_history')) {
    server.tool(
    'save_version_history',
    "Save a named version history snapshot of the current Figma file. Use before making significant changes so you can restore if needed.",
    {
      title: z.string().describe("Snapshot title (e.g. \"Before refactor\")"),
      description: z.string().optional().describe("Optional description of what was done"),
    },
    async ({ title, description }) => {
      const result = await bridge.request('save_version_history', { title, description });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'set_selection')) {
    server.tool(
    'set_selection',
    "Set the current selection to specific nodes and optionally scroll them into view. Nodes must be on the current page.",
    {
      nodeIds: z.array(z.string()).describe("Node IDs to select"),
      scrollIntoView: z.boolean().optional().describe("Scroll viewport to show selected nodes (default: true)"),
    },
    async (params) => {
      const result = await bridge.request('set_selection', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'set_explicit_variable_mode')) {
    server.tool(
    'set_explicit_variable_mode',
    "Set an explicit variable mode on a node for a specific collection. This overrides the inherited mode.",
    {
      nodeId: z.string().describe("Node ID"),
      collectionId: z.string().describe("Variable collection ID"),
      modeId: z.string().describe("Mode ID to set (get available modes from list_collections)"),
    },
    async ({ nodeId, collectionId, modeId }) => {
      const result = await bridge.request('set_explicit_variable_mode', { nodeId, collectionId, modeId });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'rename_collection')) {
    server.tool(
    'rename_collection',
    "Rename a variable collection.",
    {
      collectionId: z.string().describe("Collection ID"),
      name: z.string().describe("New collection name"),
    },
    async ({ collectionId, name }) => {
      const result = await bridge.request('rename_collection', { collectionId, name });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'add_collection_mode')) {
    server.tool(
    'add_collection_mode',
    "Add a new mode to a variable collection. Returns the new mode ID.",
    {
      collectionId: z.string().describe("Collection ID"),
      name: z.string().describe("Mode name (e.g. \"Dark\", \"Compact\")"),
    },
    async ({ collectionId, name }) => {
      const result = await bridge.request('add_collection_mode', { collectionId, name });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'rename_collection_mode')) {
    server.tool(
    'rename_collection_mode',
    "Rename an existing mode in a variable collection.",
    {
      collectionId: z.string().describe("Collection ID"),
      modeId: z.string().describe("Mode ID to rename"),
      name: z.string().describe("New mode name"),
    },
    async ({ collectionId, modeId, name }) => {
      const result = await bridge.request('rename_collection_mode', { collectionId, modeId, name });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'remove_collection_mode')) {
    server.tool(
    'remove_collection_mode',
    "Remove a mode from a variable collection. Cannot remove the last remaining mode.",
    {
      collectionId: z.string().describe("Collection ID"),
      modeId: z.string().describe("Mode ID to remove"),
    },
    async ({ collectionId, modeId }) => {
      const result = await bridge.request('remove_collection_mode', { collectionId, modeId });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'create_variable_alias')) {
    server.tool(
    'create_variable_alias',
    "Set a variable's value to reference another variable (alias). Both variables must have the same resolved type. This is how Figma implements semantic tokens (e.g. \"text/primary\" → \"gray/900\").",
    {
      variableId: z.string().describe("Variable ID to set as alias"),
      targetVariableId: z.string().describe("Target variable ID to reference"),
      modeId: z.string().optional().describe("Mode ID (defaults to first mode)"),
    },
    async ({ variableId, targetVariableId, modeId }) => {
      const result = await bridge.request('create_variable_alias', { variableId, targetVariableId, modeId });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'list_cached_tokens')) {
    server.tool(
    'list_cached_tokens',
    "List all cached token entries in Figma clientStorage.",
    {},
    async (params) => {
      const result = await bridge.request('list_spec_tokens', {});
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'delete_cached_tokens')) {
    server.tool(
    'delete_cached_tokens',
    "Delete a cached token entry from Figma clientStorage.",
    {
      name: z.string().describe("Cache entry name to delete"),
    },
    async ({ name }) => {
      const result = await bridge.request('delete_spec_tokens', { name });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'scan_styles')) {
    server.tool(
    'scan_styles',
    "Scan all local styles (paint, text, effect) and return a summary with counts and details.",
    {},
    async (params) => {
      const result = await bridge.request('scan_styles', {});
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'export_tokens')) {
    server.tool(
    'export_tokens',
    "Export all local Figma variables as DTCG-format tokens, grouped by collection.",
    {},
    async (params) => {
      const result = await bridge.request('export_tokens', {});
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'diff_styles')) {
    server.tool(
    'diff_styles',
    "Compare DTCG tokens against current Figma variables. Shows in-sync, value-mismatch, and missing tokens in both directions.",
    {
      tokens: z.array(z.object({
          path: z.string().describe("Token path"),
          type: z.string().describe("Token type"),
          value: z.unknown().describe("Token value"),
        })).describe("DTCG tokens to compare against Figma variables"),
    },
    async (params) => {
      const result = await bridge.request('diff_styles', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'get_registered_styles')) {
    server.tool(
    'get_registered_styles',
    "Get previously registered styles for a library. Returns null if not registered.",
    {
      library: z.string().describe("Library name"),
    },
    async ({ library }) => {
      const result = await bridge.request('get_registered_styles', { library });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'create_component')) {
    server.tool(
    'create_component',
    "Create a new component with specified dimensions.",
    {
      name: z.string().optional().describe("Component name (default: \"Component\")"),
      width: z.number().optional().describe("Width in px (default: 100)"),
      height: z.number().optional().describe("Height in px (default: 100)"),
      description: z.string().optional().describe("Component description"),
    },
    async ({ name, width, height, description }) => {
      const result = await bridge.request('create_component', { name, width, height, description });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'create_component_set')) {
    server.tool(
    'create_component_set',
    "Combine multiple existing components into a variant set (ComponentSet).",
    {
      componentIds: z.array(z.string()).describe("Component node IDs to combine into a variant set"),
      name: z.string().optional().describe("Name for the variant set"),
    },
    async (params) => {
      const result = await bridge.request('create_component_set', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'update_component')) {
    server.tool(
    'update_component',
    "Update a component's name, description, or size.",
    {
      nodeId: z.string().describe("Component node ID"),
      name: z.string().optional().describe("New component name"),
      description: z.string().optional().describe("New component description"),
      width: z.number().optional().describe("New width in px"),
      height: z.number().optional().describe("New height in px"),
    },
    async (params) => {
      const result = await bridge.request('update_component', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'delete_component')) {
    server.tool(
    'delete_component',
    "Delete a component node.",
    {
      nodeId: z.string().describe("Component node ID to delete"),
    },
    async ({ nodeId }) => {
      const result = await bridge.request('delete_component', { nodeId });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'swap_instance')) {
    server.tool(
    'swap_instance',
    "Swap an existing instance to a different component.",
    {
      instanceId: z.string().describe("Instance node ID"),
      componentKey: z.string().describe("New component key to swap to"),
    },
    async ({ instanceId, componentKey }) => {
      const result = await bridge.request('swap_instance', { instanceId, componentKey });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'detach_instance')) {
    server.tool(
    'detach_instance',
    "Detach an instance from its component, converting it to a frame.",
    {
      instanceId: z.string().describe("Instance node ID"),
    },
    async ({ instanceId }) => {
      const result = await bridge.request('detach_instance', { instanceId });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'reset_instance_overrides')) {
    server.tool(
    'reset_instance_overrides',
    "Reset all overrides on an instance back to the component defaults.",
    {
      instanceId: z.string().describe("Instance node ID"),
    },
    async ({ instanceId }) => {
      const result = await bridge.request('reset_instance_overrides', { instanceId });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'get_instance_overrides')) {
    server.tool(
    'get_instance_overrides',
    "Get the current override properties of a component instance (values that differ from component defaults).",
    {
      nodeId: z.string().describe("Instance node ID"),
    },
    async ({ nodeId }) => {
      const result = await bridge.request('get_instance_overrides', { nodeId });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'set_instance_overrides')) {
    server.tool(
    'set_instance_overrides',
    "Copy override properties from a source instance to one or more target instances. Use get_instance_overrides first to inspect the source, then propagate to targets.",
    {
      sourceId: z.string().describe("Source instance node ID to copy overrides from"),
      targetIds: z.array(z.string()).describe("Target instance node IDs to apply overrides to"),
    },
    async (params) => {
      const result = await bridge.request('set_instance_overrides', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'add_component_property')) {
    server.tool(
    'add_component_property',
    "Add a new property to a component or component set. Supported types: BOOLEAN, TEXT, INSTANCE_SWAP, VARIANT.",
    {
      nodeId: z.string().describe("Component or ComponentSet node ID"),
      propertyName: z.string().describe("Property name"),
      type: z.enum(['BOOLEAN', 'TEXT', 'INSTANCE_SWAP', 'VARIANT']).describe("Property type"),
      defaultValue: z.unknown().describe("Default value"),
    },
    async ({ nodeId, propertyName, type, defaultValue }) => {
      const result = await bridge.request('add_component_property', { nodeId, propertyName, type, defaultValue });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'update_component_property')) {
    server.tool(
    'update_component_property',
    "Update an existing component property (rename or change default value).",
    {
      nodeId: z.string().describe("Component or ComponentSet node ID"),
      propertyName: z.string().describe("Current property name"),
      newName: z.string().optional().describe("New property name"),
      defaultValue: z.unknown().optional().describe("New default value"),
    },
    async ({ nodeId, propertyName, newName, defaultValue }) => {
      const result = await bridge.request('update_component_property', { nodeId, propertyName, newName, defaultValue });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'delete_component_property')) {
    server.tool(
    'delete_component_property',
    "Remove a property from a component or component set.",
    {
      nodeId: z.string().describe("Component or ComponentSet node ID"),
      propertyName: z.string().describe("Property name to delete"),
    },
    async ({ nodeId, propertyName }) => {
      const result = await bridge.request('delete_component_property', { nodeId, propertyName });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'audit_components')) {
    server.tool(
    'audit_components',
    "Audit all components on the current page for structural health. Reports: missing descriptions, unexposed text nodes, empty components, single-variant sets, and property counts. Use for design system maintenance.",
    {
      nodeIds: z.array(z.string()).optional().describe("Specific node IDs to audit (default: entire page)"),
    },
    async (params) => {
      const result = await bridge.request('audit_components', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'list_library_collections')) {
    server.tool(
    'list_library_collections',
    "List all available team library variable collections. Returns collection key, name, and library name.",
    {},
    async (params) => {
      const result = await bridge.request('list_library_collections', {});
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'list_library_variables')) {
    server.tool(
    'list_library_variables',
    "List all variables in a specific team library collection.",
    {
      collectionKey: z.string().describe("The library collection key"),
    },
    async ({ collectionKey }) => {
      const result = await bridge.request('list_library_variables', { collectionKey });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'import_library_variable')) {
    server.tool(
    'import_library_variable',
    "Import a team library variable into the current file by key. Returns the imported variable details.",
    {
      variableKey: z.string().describe("The library variable key to import"),
    },
    async ({ variableKey }) => {
      const result = await bridge.request('import_library_variable', { variableKey });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'create_line')) {
    server.tool(
    'create_line',
    "Create a line node. Specify length and optional rotation.",
    {
      name: z.string().optional().describe("Node name"),
      x: z.number().optional().describe("X position"),
      y: z.number().optional().describe("Y position"),
      length: z.number().optional().describe("Line length in px (default: 100)"),
      rotation: z.number().optional().describe("Rotation in degrees (0 = horizontal)"),
      parentId: z.string().optional().describe("Parent node ID"),
      stroke: z.string().optional().describe("Stroke color as hex (default: #000000)"),
      strokeWeight: z.number().optional().describe("Stroke weight (default: 1)"),
    },
    async (params) => {
      const result = await bridge.request('create_line', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'create_star')) {
    server.tool(
    'create_star',
    "Create a star shape node.",
    {
      name: z.string().optional().describe("Node name"),
      x: z.number().optional().describe("X position"),
      y: z.number().optional().describe("Y position"),
      width: z.number().optional().describe("Width (default: 100)"),
      height: z.number().optional().describe("Height (default: 100)"),
      pointCount: z.number().optional().describe("Number of points (default: 5)"),
      innerRadius: z.number().optional().describe("Inner radius ratio 0-1 (default: 0.382)"),
      fill: z.string().optional().describe("Fill color as hex"),
      parentId: z.string().optional().describe("Parent node ID"),
    },
    async (params) => {
      const result = await bridge.request('create_star', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'create_polygon')) {
    server.tool(
    'create_polygon',
    "Create a regular polygon shape node.",
    {
      name: z.string().optional().describe("Node name"),
      x: z.number().optional().describe("X position"),
      y: z.number().optional().describe("Y position"),
      width: z.number().optional().describe("Width (default: 100)"),
      height: z.number().optional().describe("Height (default: 100)"),
      pointCount: z.number().optional().describe("Number of sides (default: 3 = triangle)"),
      fill: z.string().optional().describe("Fill color as hex"),
      parentId: z.string().optional().describe("Parent node ID"),
    },
    async (params) => {
      const result = await bridge.request('create_polygon', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'create_section')) {
    server.tool(
    'create_section',
    "Create a Figma Section node for organizing canvas content. Sections group frames without clipping and can be collapsed in Figma. Optionally move existing nodes inside by providing childIds.",
    {
      name: z.string().optional().describe("Section name (default: \"Section\")"),
      x: z.number().optional().describe("X position"),
      y: z.number().optional().describe("Y position"),
      childIds: z.array(z.string()).optional().describe("Node IDs to move inside the section"),
    },
    async (params) => {
      const result = await bridge.request('create_section', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'flatten_node')) {
    server.tool(
    'flatten_node',
    "Flatten a node (or group) into a single vector. Useful for converting complex shapes into a single editable path.",
    {
      nodeId: z.string().describe("Node ID to flatten"),
    },
    async ({ nodeId }) => {
      const result = await bridge.request('flatten_node', { nodeId });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'boolean_operation')) {
    server.tool(
    'boolean_operation',
    "Apply a boolean operation to two or more vector/shape nodes. UNION merges shapes, SUBTRACT removes overlap from the first shape, INTERSECT keeps only the overlapping area, EXCLUDE keeps non-overlapping areas. All nodes must share the same parent. Returns the resulting BooleanOperation node.",
    {
      nodeIds: z.array(z.string()).describe("Node IDs to combine (at least 2, order matters for SUBTRACT)"),
      operation: z.enum(['UNION', 'SUBTRACT', 'INTERSECT', 'EXCLUDE']).describe("Boolean operation type"),
      name: z.string().optional().describe("Name for the resulting node"),
    },
    async (params) => {
      const result = await bridge.request('boolean_operation', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'get_annotations')) {
    server.tool(
    'get_annotations',
    "Get all annotations on the current page or a specific node. Returns each annotated node with its annotation labels.",
    {
      nodeId: z.string().optional().describe("Node ID to inspect; omit to scan the entire current page"),
    },
    async ({ nodeId }) => {
      const result = await bridge.request('get_annotations', { nodeId });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'set_annotation')) {
    server.tool(
    'set_annotation',
    "Add or replace an annotation on a node. Use replace=true to overwrite existing annotations; omit or set false to append.",
    {
      nodeId: z.string().describe("Target node ID"),
      label: z.string().describe("Annotation text (Markdown supported)"),
      replace: z.boolean().optional().describe("If true, replaces all existing annotations on the node (default: false = append)"),
    },
    async ({ nodeId, label, replace }) => {
      const result = await bridge.request('set_annotation', { nodeId, label, replace });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'set_multiple_annotations')) {
    server.tool(
    'set_multiple_annotations',
    "Batch annotate multiple nodes in a single call. Each item can independently append or replace.",
    {
      items: z.array(z.object({
          nodeId: z.string().describe("Target node ID"),
          label: z.string().describe("Annotation text"),
          replace: z.boolean().optional().describe("If true, replaces existing annotations on this node"),
        })).describe("List of annotation operations"),
    },
    async (params) => {
      const result = await bridge.request('set_multiple_annotations', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'clear_annotations')) {
    server.tool(
    'clear_annotations',
    "Remove all figcraft lint annotations from specified nodes or the whole page.",
    {
      nodeIds: z.array(z.string()).optional().describe("Node IDs to clear (default: all on page)"),
    },
    async (params) => {
      const result = await bridge.request('clear_annotations', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'get_reactions')) {
    server.tool(
    'get_reactions',
    "Get prototype reactions (interactions) on a specific node or all nodes on the current page. Returns trigger types and action types. Useful for analyzing prototype flows.",
    {
      nodeId: z.string().optional().describe("Node ID to inspect; omit to scan the entire current page"),
    },
    async ({ nodeId }) => {
      const result = await bridge.request('get_reactions', { nodeId });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'add_reaction')) {
    server.tool(
    'add_reaction',
    "Add a prototype reaction (interaction) to a node. Supports single node or batch mode via items array. Use this to wire up click/hover/press navigation between screens.",
    {
      nodeId: z.string().optional().describe("Target node ID (single mode)"),
      trigger: z.object({
          type: z.string(),
          delay: z.number().optional(),
          timeout: z.number().optional(),
        }).optional().describe("Trigger definition (single mode). type is required: ON_CLICK, ON_HOVER, ON_PRESS, ON_DRAG, AFTER_TIMEOUT, MOUSE_ENTER, MOUSE_LEAVE, MOUSE_UP, MOUSE_DOWN. Optional: delay (ms), timeout (ms)."),
      actions: z.array(z.object({
          type: z.string(),
          destinationId: z.string().optional(),
          navigation: z.string().optional(),
          url: z.string().optional(),
          transition: z.object({
            type: z.string(),
            duration: z.number(),
            easing: z.record(z.unknown()).optional(),
            direction: z.string().optional(),
          }).optional(),
          overlay: z.record(z.unknown()).optional(),
        })).optional().describe("Action definitions (single mode). Each action: type (NODE|BACK|CLOSE|URL), destinationId, navigation (NAVIGATE|SWAP|OVERLAY|SCROLL_TO|CHANGE_TO), transition ({type, duration, easing, direction}), url (for URL type)."),
      items: z.array(z.object({
          nodeId: z.string(),
          trigger: z.record(z.unknown()),
          actions: z.array(z.unknown()),
        })).optional().describe("Batch mode: array of {nodeId, trigger, actions} objects. When provided, nodeId/trigger/actions params are ignored."),
    },
    async (params) => {
      const result = await bridge.request('add_reaction', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'remove_reaction')) {
    server.tool(
    'remove_reaction',
    "Remove prototype reactions from a node. Remove by index, by trigger type, or all at once.",
    {
      nodeId: z.string().describe("Target node ID"),
      index: z.number().optional().describe("Reaction index to remove (0-based)"),
      triggerType: z.string().optional().describe("Remove all reactions with this trigger type (e.g. ON_CLICK)"),
      removeAll: z.boolean().optional().describe("Remove all reactions from the node"),
    },
    async ({ nodeId, index, triggerType, removeAll }) => {
      const result = await bridge.request('remove_reaction', { nodeId, index, triggerType, removeAll });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'set_reactions')) {
    server.tool(
    'set_reactions',
    "Replace all prototype reactions on a node with a new set. Use this for full control over a node's interactions.",
    {
      nodeId: z.string().describe("Target node ID"),
      reactions: z.array(z.object({
          trigger: z.object({
            type: z.string(),
            delay: z.number().optional(),
            timeout: z.number().optional(),
          }),
          actions: z.array(z.object({
          type: z.string(),
          destinationId: z.string().optional(),
          navigation: z.string().optional(),
          url: z.string().optional(),
          transition: z.record(z.unknown()).optional(),
          overlay: z.record(z.unknown()).optional(),
        })),
        })).describe("Array of reaction specs. Each: {trigger: {type, delay?, timeout?}, actions: [{type, destinationId?, navigation?, transition?, url?}]}"),
    },
    async (params) => {
      const result = await bridge.request('set_reactions', params);
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'lint_rules')) {
    server.tool(
    'lint_rules',
    "List all available lint rules with descriptions.",
    {},
    async (params) => {
      const result = await bridge.request('lint_rules', {});
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'create_page')) {
    server.tool(
    'create_page',
    "Create a new page in the document.",
    {
      name: z.string().describe("Page name"),
    },
    async ({ name }) => {
      const result = await bridge.request('create_page', { name });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'rename_page')) {
    server.tool(
    'rename_page',
    "Rename an existing page.",
    {
      pageId: z.string().describe("Page ID"),
      name: z.string().describe("New page name"),
    },
    async ({ pageId, name }) => {
      const result = await bridge.request('rename_page', { pageId, name });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

  if (shouldRegisterGeneratedTool(include, 'delete_node')) {
    server.tool(
    'delete_node',
    "Delete a node by ID.",
    {
      nodeId: z.string().describe("Node ID to delete"),
    },
    async ({ nodeId }) => {
      const result = await bridge.request('delete_node', { nodeId });
      return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
    },
  );
  }

}

// ─── Endpoint Zod Schemas ───

export const nodesEndpointSchema = {
      method: z.enum(['get', 'list', 'update', 'delete']).describe('Method to invoke on this endpoint'),
      nodeId: z.string().optional().describe("Node ID or Figma URL"),
      query: z.string().optional().describe("Search query"),
      types: z.array(z.string()).optional().describe("Filter by node types"),
      limit: z.number().optional().describe("Max results (default 50)"),
      patches: z.array(z.object({
          nodeId: z.string(),
          props: z.record(z.unknown()),
        })).optional(),
      nodeIds: z.array(z.string()).optional(),
    };

export const textEndpointSchema = {
      method: z.enum(['set_content']).describe('Method to invoke on this endpoint'),
      nodeId: z.string().optional().describe("Text node ID"),
      content: z.string().optional().describe("New text content"),
    };

export const componentsEndpointSchema = {
      method: z.enum(['list', 'list_library', 'get', 'list_properties']).describe('Method to invoke on this endpoint'),
      fileKey: z.string().optional().describe("Figma file key"),
      nodeId: z.string().optional().describe("Component node ID"),
    };

export const variables_epEndpointSchema = {
      method: z.enum(['list', 'get', 'list_collections', 'get_bindings', 'set_binding', 'create', 'update', 'delete', 'create_collection', 'delete_collection', 'batch_create', 'export']).describe('Method to invoke on this endpoint'),
      collectionId: z.string().optional().describe("Filter by collection ID"),
      type: z.string().optional().describe("Filter by type: COLOR, FLOAT, STRING, BOOLEAN"),
      variableId: z.string().optional(),
      nodeId: z.string().optional(),
      field: z.string().optional(),
      name: z.string().optional(),
      resolvedType: z.enum(['COLOR', 'FLOAT', 'STRING', 'BOOLEAN']).optional(),
      value: z.unknown().optional(),
      modeId: z.string().optional(),
      description: z.string().optional(),
      scopes: z.array(z.string()).optional(),
      collectionName: z.string().optional(),
      modeName: z.string().optional(),
      variables: z.array(z.record(z.unknown())).optional(),
    };

export const styles_epEndpointSchema = {
      method: z.enum(['list', 'get', 'create_paint', 'update_paint', 'update_text', 'update_effect', 'delete', 'sync']).describe('Method to invoke on this endpoint'),
      type: z.string().optional().describe("Filter by style type: PAINT, TEXT, EFFECT, GRID"),
      styleId: z.string().optional(),
      name: z.string().optional(),
      color: z.string().optional(),
      description: z.string().optional(),
      fontFamily: z.string().optional(),
      fontStyle: z.string().optional(),
      fontSize: z.number().optional(),
      lineHeight: z.unknown().optional(),
      letterSpacing: z.unknown().optional(),
      effects: z.array(z.record(z.unknown())).optional(),
      tokens: z.array(z.record(z.unknown())).optional(),
    };

