// Auto-generated by scripts/compile-content.ts — DO NOT EDIT
// Source: content/guides/*.md

export const GUIDES: Record<string, string> = {
  BATCHING: `# Context Budget & Batching Strategy

Large design tasks accumulate context with each tool call. Proactively manage context to prevent stalling.

## Granularity Rules

| Task scale | Strategy | Example |
|------------|----------|---------|
| Single element | 1 create_frame call | One call with children builds the card |
| Single screen | 1 create_frame with full children tree | Entire screen in one call |
| Multi-screen (3-5) | create_frame with items[] batch | One call creates all screens (max 20) |
| Large flow (6+) | Batch 2-3 screens per turn | "I'll create screens 1-3 now, then 4-6 next" |
| Multiple labels | create_text with items[] batch | One call creates up to 50 text nodes |
| Complex params | dryRun:true first | Preview inferences, then create with correctedPayload |

## Batch Mode Tradeoff (items[] vs individual calls)

| | items[] batch | Individual calls |
|---|---|---|
| Context cost | 1 request + 1 response | N requests + N responses |
| Visual verification | export_image after batch | export_image per screen |
| Error isolation | Per-item (one failure doesn't block) | Natural isolation |
| Best for | Skeleton/wrapper creation | Screens with complex children |

**Recommendation**: items[] for skeleton (empty screens), then fill each screen individually via parentId.

## Verification Strategy

- **Embedded check** (zero cost): inspect _children from create_frame response
- **Visual check**: export_image(scale:0.5) at key milestones (after each screen, after skeleton)
`,
  CONTENT_STATES: `# Content State Patterns

Every data-driven view MUST consider these states:

## Empty State
\`\`\`
Container (VERTICAL, FILL/HUG, counterAxisAlignItems: CENTER, padding 40-60)
  ├── Illustration (120-160px, subtle fill or SVG placeholder)
  ├── Heading ("No items yet" / "Get started") — 20px, semibold
  ├── Body ("Add your first item to see it here") — 14-16px, muted
  └── CTA Button ("Add Item") — primary style
\`\`\`
- Center the empty state vertically and horizontally in its container
- Use encouraging, action-oriented language (not error language)
- The CTA should directly trigger the creation action

## Loading State (Skeleton)
\`\`\`
Same structure as loaded state, but:
  ├── Text nodes → gray rectangles (cornerRadius 4, fill gray-200, height matching line-height)
  ├── Images → gray rectangles (same dimensions, fill gray-100)
  ├── Avatar → gray circle (same size)
  └── All skeleton elements: no stroke, uniform gray palette
\`\`\`
- Match the loaded layout exactly — skeleton IS the layout with gray placeholders
- NEVER use a centered spinner for content that has a known layout
- Spinner only for indeterminate operations (file upload, search)

## Error State
\`\`\`
Container (VERTICAL, FILL/HUG, counterAxisAlignItems: CENTER, padding 40-60)
  ├── Error icon (48-64px, warning/error color)
  ├── Heading ("Something went wrong") — 20px, semibold
  ├── Body ("We couldn't load your data. Please try again.") — 14-16px, muted
  └── Retry Button ("Try Again") — secondary or outline style
\`\`\`
- Use neutral, non-blaming language
- Always provide a retry action
- Don't use red for the entire error state — red for icon/accent only
`,
  ICONOGRAPHY: `# Iconography Guide

## Ordering — children order = visual order (CRITICAL)

In auto-layout, the children array index directly controls visual position:
- **Index 0** = leftmost (HORIZONTAL) / topmost (VERTICAL)
- **Last index** = rightmost / bottommost

\`icon_create\` with \`parentId\` **appends to END** by default. Use \`index\` to control position:
- \`index: 0\` — icon appears FIRST (left of text in HORIZONTAL)
- Omit index — icon appears LAST (right of text)

### Common Patterns

| UI Pattern | Correct children order | icon_create index |
|------------|----------------------|-------------------|
| Search input | [search-icon, text-input] | \`index: 0\` |
| Password input | [lock-icon, text-input, eye-icon] | lock: \`index: 0\`, eye: omit |
| Nav menu item | [icon, label, chevron-right] | icon: \`index: 0\`, chevron: omit |
| Button with leading icon | [icon, label] | \`index: 0\` |
| Button with trailing icon | [label, icon] | omit (default append) |
| Settings row | [icon, label, toggle/chevron] | icon: \`index: 0\` |
| List item | [thumbnail, content, trailing-action] | thumbnail: \`index: 0\` |
| Tab bar item | [icon, label] (VERTICAL) | \`index: 0\` |
| Notification badge | [bell-icon, red-dot] | bell: \`index: 0\` |
| Back navigation | [arrow-left, title] | \`index: 0\` |

### Inline Children vs icon_create

Two approaches for placing icons in create_frame:

1. **Inline children** (preferred for structured layouts): Include icon as a \`type: "frame"\` placeholder in the children array at the correct position, then use \`icon_create(parentId: "<placeholder-id>")\` to fill it. Array position controls visual order directly.

2. **Post-creation icon_create** (simpler): Create the frame first, then call \`icon_create(parentId: "<frame-id>", index: 0)\` to insert at the correct position.

Note: \`create_frame\` children \`type: "svg"\` requires raw SVG markup string, NOT icon names like "lucide:home". Use \`icon_create\` for named icons.

## Tool Chain

### Library Mode (Design Guardian)
1. \`search_design_system(query: "icon chevron")\` — find library icon components
2. If found: use \`type: "instance"\` in children or component insert
3. If not found: fall back to Iconify flow below

### No-Library Mode (Design Creator)
1. \`icon_search(query: "search", prefix: "lucide")\` — find icon name
2. \`icon_create(icon: "lucide:search", parentId: "...", index: 0, size: 20)\` — create + place

### Key Constraints
- \`icon_create\` accepts icon name ("prefix:name") — fetches SVG automatically
- \`create_frame\` children \`type: "svg"\` requires raw SVG markup, NOT icon name
- These are different mechanisms — don't mix them

## Sizing

| Context | Icon Size | itemSpacing to text | Notes |
|---------|----------|--------------------|----|
| Inline (body text) | 16px | 4-6px | Match text line height |
| Input field | 20px | 8px | Vertically centered |
| Navigation / toolbar | 24px | 8-12px | Default icon_create size |
| Button with icon | 20px | 8px | Match button text size |
| Feature / empty state | 32-64px | 12-16px | Prominent, muted color |
| Tab bar | 24px | 4px | Above label (VERTICAL layout) |
| Avatar placeholder | 40-80px | — | Inside circular frame |

## Alignment

- Parent frame needs \`counterAxisAlignItems: "CENTER"\` to vertically center icon with text
- Icon containers: use \`type: "frame"\` with \`layoutMode\`, \`primaryAxisAlignItems: "CENTER"\`, \`counterAxisAlignItems: "CENTER"\`
- Touch targets: icon buttons need minimum 44x44px tap area — add padding to reach 44x44 even if icon is 24px

## Color

- Use \`colorVariableName\` in \`icon_create\` to bind icon color to design token
- \`icon_create\` auto-detects fill vs stroke icons and binds accordingly
- Without binding, icon won't respond to theme changes (light/dark mode)

## Style Consistency

- Single icon set per design (all \`lucide:\`, or all \`mdi:\`, etc.) — never mix sets
- Single style: outline, filled, or duotone — never mix styles
- Icon stroke weight should match typography weight (light type -> thin icons)
- NEVER use decorative icons without functional meaning

## Common Pitfalls

| Pitfall | Prevention |
|---------|-----------|
| Icon placed after text (wrong order) | Use \`icon_create\` with \`index: 0\` for leading icons |
| Text as icon (">" for chevron, "..." for more) | Runtime detection warns; use \`icon_create\` instead |
| Rectangle as icon container | Use \`type: "frame"\` — rectangles can't have children |
| Forgot icon entirely (search bar without search icon) | Plan ALL icons before create_frame |
| Icon name in SVG child | \`type: "svg"\` needs raw SVG markup; use \`icon_create\` for named icons |
| Icon too small / too large | Follow sizing table above per context |
| No color binding | Pass \`colorVariableName\` when design system has tokens |
| Mixed icon sets (lucide + mdi) | Pick one prefix and use it consistently |
| Mixed icon styles (outline + filled) | Choose one style for the entire design |
| Touch target too small | Icon buttons need 44x44px minimum via padding |
| Icon-text vertical misalignment | Set \`counterAxisAlignItems: "CENTER"\` on parent |
| Icon spacing inconsistent | Use sizing table itemSpacing values per context |
`,
  MULTI_SCREEN: `# Multi-Screen Flow Architecture

Multi-screen flows (login, onboarding, checkout, etc.) MUST use create_frame + children.

## Hierarchy (do not skip levels)

\`\`\`
Wrapper (VERTICAL, HUG/HUG, counterAxisAlignItems=MIN, clipsContent=false, cornerRadius=20-40, fill=lightGray, padding, itemSpacing)
  ├── Header (title + description)
  └── Flow Row (HORIZONTAL, HUG/HUG, clipsContent=false, itemSpacing between screens)
        └── Stage / {label} (VERTICAL, HUG/HUG, clipsContent=false) — one per screen
              ├── Step Pill (badge: "01 Welcome")
              └── Screen / {label} (VERTICAL, FIXED 402×874, cornerRadius=28, clipsContent=true, padding, SPACE_BETWEEN, shadow:{y:4, blur:16})
                    ├── Top Content (VERTICAL, FILL/HUG)
                    └── Bottom Content (HORIZONTAL or VERTICAL, FILL/HUG)
\`\`\`

## Build Order

1. create_frame: Wrapper + children with full skeleton (Header + Flow Row + Stages + Screens) → check _children in response to confirm structure
2. ⚠️ MUST export_image(scale:0.3) to verify all screens are laid out horizontally in Flow Row — do NOT proceed to fill screens until this is confirmed
3. create_frame: Fill Screen 1 (parentId=screen1Id, children=[TopContent, BottomContent]) → export_image to verify layout
4. create_frame: Fill remaining screens one by one → export_image as needed
5. lint_fix_all → done

The Opinion Engine automatically handles: sizing inference, FILL ordering, conflict detection, cross-level validation, and failure cleanup. No need to manually handle these Figma API details.

## Key Rules

- Screen uses primaryAxisAlignItems: "SPACE_BETWEEN" for top/bottom distribution (use "MIN" for sparse content screens)
- Shadow elements: ALL ancestor containers must have clipsContent: false
- Screen dimensions: iOS 402×874, Android 412×915
- Use dryRun: true when uncertain about parameters
`,
  OPINION_ENGINE: `# Opinion Engine (create_frame built-in)

create_frame includes an Opinion Engine that automatically handles common Figma API pitfalls. You do NOT need to handle these manually.

## Automatic Inferences

| What | How | Confidence |
|------|-----|------------|
| layoutMode | Inferred from padding/spacing/alignment params | deterministic |
| layoutSizing | Context-aware: FILL cross-axis, HUG primary-axis; mobile → FIXED | deterministic |
| FILL → HUG downgrade | Parent HUG + child FILL would collapse → auto-downgrade | deterministic |
| Parent promotion | Children need FILL → parent auto-gets layoutMode | deterministic/ambiguous |
| Text resize | Empty text → HEIGHT; overflow → HEIGHT; lineHeight fix | deterministic |
| Empty frame → rectangle | Empty fixed-size frame downgraded to avoid HUG errors | deterministic |
| Font normalization | "700" → "Bold", "SemiBold" → "Semi Bold" | deterministic |
| Direction | WRAP → HORIZONTAL; name matches row/toolbar → HORIZONTAL | deterministic |

## Token Auto-Binding (library mode)

- fillVariableName → searches library COLOR variables
- textStyleName → matches library text styles
- Spacing/padding → matches library FLOAT variables by scope
- Falls back to hardcoded values if no match

## Response Fields

- _hints: what inferences were applied [confidence, field, value, reason]
- _warnings: non-fatal issues (style not found, padding > frame)
- _inferences: full inference array
- _libraryBindings: bound variables/styles
- _lintSummary: quick lint after creation
- _previewHint: suggests export_image for verification
- _correctedPayload: corrected params when ambiguous (use for retry)

## dryRun Mode

create_frame(dryRun:true) validates without creating:
- Returns inferences, conflicts, ambiguities
- Provides correctedPayload for safe retry
- Zero side effects — no nodes created
`,
  RESPONSIVE: `# Responsive Web Layout Guide

## Breakpoints

| Breakpoint | Width | Columns | Padding |
|-----------|-------|---------|---------|
| Mobile    | 375px | 1       | 16px    |
| Tablet    | 768px | 2       | 24px    |
| Desktop   | 1280px| 3-4     | 32-64px |

## Auto Layout Strategy

- Mobile: VERTICAL stack, 1 column, FILL width children
- Tablet: mix HORIZONTAL rows (2-col) + VERTICAL sections
- Desktop: HORIZONTAL main layout with sidebar + content area

## Sizing Patterns

| Context | Horizontal | Vertical |
|---------|-----------|----------|
| Page container | FIXED (breakpoint width) | HUG |
| Content area | FILL | HUG |
| Sidebar | FIXED (240-300px) | FILL |
| Cards in grid | layoutGrow: 1 (equal width) | HUG |
| Full-width sections | FILL | HUG |

## Key Rules

- NEVER use fixed pixel widths for content children at mobile — use FILL
- SHOULD use maxWidth constraints for text readability (600-800px at desktop)
- Breakpoint frames are FIXED width; their children adapt via FILL/HUG
- Cards: use layoutGrow: 1 in HORIZONTAL rows for equal distribution
- Navigation: HORIZONTAL on desktop, bottom tab bar on mobile
`,
  TOOL_BEHAVIOR: `# Tool Behavior Rules

## Mandatory Sequence
1. Always call ping first to verify connection
2. Complete workflow in one turn until ⛔ HARD STOP checkpoints
3. Prefer batch tools: lint_fix_all over lint_check + lint_fix separately

## Parallelization
4. Parallelize independent calls (e.g., multiple nodes(method:"get") in one message)
5. Sequential for dependent calls (create parent before children)

## Update Patterns
6. nodes(method:"update") uses 5-phase ordered execution: simple props → fills/strokes → layout sizing → resize → text. Safe to send layoutMode + width in same patch.
7. nodes(method:"update") supports width/height directly (calls resize internally), text properties, and layoutPositioning.

## Validation
8. dryRun:true for complex or ambiguous parameters — preview Opinion Engine inferences before committing
9. After the FIRST create_frame failure, review ALL remaining planned payloads for the same pattern before retrying
`,
};
