// Auto-generated by scripts/compile-content.ts — DO NOT EDIT
// Source: content/templates/*.yaml

export interface UiPattern {
  structure: string;
  keyDecisions: Record<string, string>;
  pitfalls: string[];
  toneVariants: Record<string, Record<string, string>>;
  exampleParams: Record<string, unknown>;
}

export const UI_PATTERNS: Record<string, UiPattern> = {
  "card-grid": {
    "structure": "Screen (VERTICAL, FIXED 402×874 mobile / 1280×800 web, padding 16-24)\n  ├── Header (HORIZONTAL, FILL/HUG, itemSpacing 12)\n  │     ├── Title (\"Explore\")\n  │     └── Filter chips (HORIZONTAL, HUG/HUG, itemSpacing 8)\n  └── Grid (VERTICAL, FILL/FILL, itemSpacing 16)\n        └── Row × N (HORIZONTAL, FILL/HUG, itemSpacing 12-16)\n              └── Card × 2-3 (VERTICAL, layoutGrow 1, cornerRadius 12-16, clipsContent true)\n                    ├── Image (FILL/FIXED height 140-180, fill gray-100)\n                    └── Content (VERTICAL, FILL/HUG, padding 12-16, itemSpacing 4-8)\n                          ├── Title (16px, semibold, max 2 lines)\n                          ├── Subtitle (14px, muted)\n                          └── Footer (HORIZONTAL, FILL/HUG) — price, rating, action",
    "keyDecisions": {
      "columns": "Mobile: 2 columns (layoutGrow: 1 each). Web: 3-4 columns",
      "cardImage": "Image placeholder with fill color + description — NEVER empty frame",
      "cardAspectRatio": "4:3 for products, 16:9 for content/media, 1:1 for square thumbnails",
      "equalHeight": "Cards in same row should have equal height via matching image + content height",
      "interactionHint": "Optional: subtle shadow or scale on card for tap affordance"
    },
    "pitfalls": [
      "overflow-parent: cards overflow screen width (need layoutGrow, not fixed width)",
      "empty-container: image placeholder frames empty",
      "text-overflow: titles overflow card width at 2 columns",
      "no-autolayout: cards manually positioned instead of auto-layout grid rows",
      "default-name: cards named \"Frame 1\" instead of \"Card / Product Name\"",
      "cta-width-inconsistent: footer action buttons different sizes across cards"
    ],
    "toneVariants": {
      "minimal": {
        "cornerRadius": "12px",
        "colors": "white cards, no shadow, subtle gray-100 images",
        "typography": "clean sans, 2 weights"
      },
      "warm": {
        "cornerRadius": "16px",
        "colors": "warm card shadows, soft rounded aesthetic",
        "typography": "friendly font, generous line height"
      },
      "bold": {
        "cornerRadius": "20px",
        "colors": "dark cards or vivid image overlays, strong CTA colors",
        "typography": "compact bold titles, high contrast"
      }
    },
    "exampleParams": {
      "name": "Screen / Card Grid",
      "width": 402,
      "height": 874,
      "layoutMode": "VERTICAL",
      "primaryAxisAlignItems": "MIN",
      "padding": 16,
      "cornerRadius": 28,
      "fill": "#FFFFFF",
      "clipsContent": true,
      "itemSpacing": 16,
      "children": [
        {
          "type": "frame",
          "name": "Header",
          "layoutMode": "HORIZONTAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "counterAxisAlignItems": "CENTER",
          "itemSpacing": 12,
          "children": [
            {
              "type": "frame",
              "name": "Filter Chips",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "HUG",
              "layoutSizingVertical": "HUG",
              "itemSpacing": 8
            }
          ]
        },
        {
          "type": "frame",
          "name": "Grid",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "FILL",
          "itemSpacing": 16,
          "children": [
            {
              "type": "frame",
              "name": "Row 1",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "HUG",
              "itemSpacing": 12,
              "children": [
                {
                  "type": "frame",
                  "name": "Card",
                  "layoutMode": "VERTICAL",
                  "layoutSizingVertical": "HUG",
                  "layoutGrow": 1,
                  "cornerRadius": 12,
                  "clipsContent": true,
                  "fill": "#FFFFFF",
                  "children": [
                    {
                      "type": "frame",
                      "name": "Image",
                      "layoutSizingHorizontal": "FILL",
                      "layoutSizingVertical": "FIXED",
                      "height": 160,
                      "fill": "#F3F4F6"
                    },
                    {
                      "type": "frame",
                      "name": "Content",
                      "layoutMode": "VERTICAL",
                      "layoutSizingHorizontal": "FILL",
                      "layoutSizingVertical": "HUG",
                      "padding": 12,
                      "itemSpacing": 4
                    }
                  ]
                },
                {
                  "type": "frame",
                  "name": "Card",
                  "layoutMode": "VERTICAL",
                  "layoutSizingVertical": "HUG",
                  "layoutGrow": 1,
                  "cornerRadius": 12,
                  "clipsContent": true,
                  "fill": "#FFFFFF",
                  "children": [
                    {
                      "type": "frame",
                      "name": "Image",
                      "layoutSizingHorizontal": "FILL",
                      "layoutSizingVertical": "FIXED",
                      "height": 160,
                      "fill": "#F3F4F6"
                    },
                    {
                      "type": "frame",
                      "name": "Content",
                      "layoutMode": "VERTICAL",
                      "layoutSizingHorizontal": "FILL",
                      "layoutSizingVertical": "HUG",
                      "padding": 12,
                      "itemSpacing": 4
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  },
  "checkout": {
    "structure": "Use Multi-Screen Flow Architecture (see get_creation_guide topic:\"multi-screen\").\n\nTypical 3-4 screens:\n\nScreen 1 — Cart Review (VERTICAL, FIXED 402×874, SPACE_BETWEEN, padding 24)\n  ├── Cart Items (VERTICAL, FILL/HUG, itemSpacing 16)\n  │     └── Item × N (HORIZONTAL, FILL/HUG, padding 12, itemSpacing 12)\n  │           ├── Thumbnail (64×64, cornerRadius 8)\n  │           ├── Details (VERTICAL, FILL/HUG) — name, variant, qty\n  │           └── Price (right-aligned, bold)\n  └── Summary + CTA (VERTICAL, FILL/HUG, itemSpacing 12)\n        ├── Subtotal / Shipping / Total rows\n        └── \"Proceed to Payment\" CTA\n\nScreen 2 — Shipping (form with address fields)\nScreen 3 — Payment (card fields + billing)\nScreen 4 — Confirmation (success icon + order summary)",
    "keyDecisions": {
      "progressBar": "Step indicator at top: Cart → Shipping → Payment → Done (HORIZONTAL dots or numbered steps)",
      "priceSummary": "Right-aligned prices, bold total, clear subtotal/tax/shipping breakdown",
      "formFields": "Reuse input structure from login/signup patterns — consistent height, stroke, cornerRadius",
      "confirmationScreen": "Large check icon (64px) + \"Order Confirmed\" heading + order number + \"Continue Shopping\" CTA",
      "security": "Lock icon near payment fields, \"Secure checkout\" label — builds trust"
    },
    "pitfalls": [
      "screen-bottom-overflow: cart with many items pushes CTA below viewport",
      "form-consistency: shipping/payment inputs inconsistent with other forms",
      "button-structure: CTA not full-width or < 48px height",
      "text-overflow: long product names overflow item row",
      "cta-width-inconsistent: different CTA widths across checkout screens",
      "mobile-dimensions: screens not matching 402×874"
    ],
    "toneVariants": {
      "minimal": {
        "cornerRadius": "8-12px",
        "colors": "white, clean lines, green for success/confirmation",
        "typography": "system font, emphasis on prices"
      },
      "elegant": {
        "cornerRadius": "12-16px",
        "colors": "warm neutrals, gold accent for premium feel",
        "typography": "serif for headings, clean numbers for prices"
      },
      "bold": {
        "cornerRadius": "16-24px",
        "colors": "branded color CTA, dark summary sections",
        "typography": "large price emphasis, strong CTA text"
      }
    },
    "exampleParams": {
      "name": "Screen / Checkout",
      "width": 402,
      "height": 874,
      "layoutMode": "VERTICAL",
      "primaryAxisAlignItems": "SPACE_BETWEEN",
      "padding": 24,
      "paddingTop": 60,
      "paddingBottom": 34,
      "cornerRadius": 28,
      "fill": "#FFFFFF",
      "clipsContent": true,
      "children": [
        {
          "type": "frame",
          "name": "Cart Items",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "itemSpacing": 16,
          "children": [
            {
              "type": "frame",
              "name": "Cart Item",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "HUG",
              "padding": 12,
              "itemSpacing": 12,
              "counterAxisAlignItems": "CENTER",
              "children": [
                {
                  "type": "frame",
                  "name": "Thumbnail",
                  "width": 64,
                  "height": 64,
                  "cornerRadius": 8,
                  "fill": "#F3F4F6"
                },
                {
                  "type": "frame",
                  "name": "Details",
                  "layoutMode": "VERTICAL",
                  "layoutSizingHorizontal": "FILL",
                  "layoutSizingVertical": "HUG",
                  "itemSpacing": 4,
                  "layoutGrow": 1
                }
              ]
            }
          ]
        },
        {
          "type": "frame",
          "name": "Summary",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "itemSpacing": 12,
          "children": [
            {
              "type": "frame",
              "name": "Row / Subtotal",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "HUG",
              "primaryAxisAlignItems": "SPACE_BETWEEN"
            },
            {
              "type": "frame",
              "name": "Row / Total",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "HUG",
              "primaryAxisAlignItems": "SPACE_BETWEEN"
            },
            {
              "type": "frame",
              "name": "Button / Checkout",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "FIXED",
              "height": 48,
              "cornerRadius": 12,
              "fill": "#111827",
              "primaryAxisAlignItems": "CENTER",
              "counterAxisAlignItems": "CENTER"
            }
          ]
        }
      ]
    }
  },
  "dashboard": {
    "structure": "Screen (VERTICAL, FIXED 402×874 mobile / 1280×800 web, padding 16-24)\n  ├── Header (HORIZONTAL, FILL/HUG, itemSpacing 12)\n  │     ├── Title (\"Dashboard\")\n  │     ├── Spacer (layoutGrow 1) or counterAxisAlignItems: MIN\n  │     └── Actions (avatar, notification bell, settings icon)\n  ├── Stats Row (HORIZONTAL, FILL/HUG, itemSpacing 12-16)\n  │     └── Stat Card × 3-4 (VERTICAL, equal width via layoutGrow, padding 16, cornerRadius 12, fill surface)\n  │           ├── Label (12-14px, muted)\n  │           ├── Value (24-32px, bold)\n  │           └── Trend (12px, green/red + arrow)\n  ├── Chart Area (VERTICAL, FILL/HUG, padding 16, cornerRadius 12, fill surface)\n  │     ├── Chart title + period selector\n  │     └── Chart placeholder (FILL/FIXED height 200-240, fill gray-100)\n  └── List / Table (VERTICAL, FILL/HUG)\n        ├── Section header (\"Recent activity\")\n        └── Row × N (HORIZONTAL, FILL/HUG, padding 12-16, itemSpacing 12)",
    "keyDecisions": {
      "density": "Mobile: stack vertically, 1 column. Web: 2-3 column grid via HORIZONTAL rows",
      "statCards": "Use layoutGrow: 1 on each card for equal width distribution in HORIZONTAL row",
      "chartPlaceholder": "Colored rectangle with \"Chart\" text inside — never empty frame",
      "scrollBehavior": "primaryAxisAlignItems: \"MIN\" (not SPACE_BETWEEN) — dashboard scrolls, doesn't stretch",
      "cardStyle": "Consistent cornerRadius, fill surface/white, optional subtle shadow or stroke"
    },
    "pitfalls": [
      "stats-row-cramped: stat cards too close together (itemSpacing < 12px)",
      "empty-container: chart placeholder frame is empty — use type:\"frame\" with centered bar-chart icon (lucide:chart-bar-increasing)",
      "overflow-parent: stat cards overflow screen width on mobile",
      "no-autolayout: stat cards not in auto-layout row (manual positioning breaks on resize)",
      "wcag-contrast: muted labels / trend text below 4.5:1",
      "default-name: cards named \"Frame 1\" instead of \"Stats Card / Revenue\"",
      "stat-value-wrap: stat values (\"$12,480\") wrap to 2 lines in narrow cards — use fontSize ≤20px or ensure card content width > text width",
      "avatar-placeholder: header avatar must be type:\"frame\" with circle-user icon, NOT type:\"rectangle\" (cannot add icon later)",
      "notification-icon: use lucide:bell icon instead of text badge only — combine icon + red dot badge for notification indicator"
    ],
    "toneVariants": {
      "minimal": {
        "cornerRadius": "8-12px",
        "colors": "white cards on gray-50 background, monochrome chart",
        "typography": "system font, compact spacing"
      },
      "elegant": {
        "cornerRadius": "12-16px",
        "colors": "subtle card shadows, accent color for trends and chart highlights",
        "typography": "medium weight numbers, light labels"
      },
      "bold": {
        "cornerRadius": "16-24px",
        "colors": "dark background, colored stat cards, vivid chart colors",
        "typography": "large stat values (32px+), strong hierarchy"
      }
    },
    "exampleParams": {
      "name": "Screen / Dashboard",
      "width": 402,
      "height": 874,
      "layoutMode": "VERTICAL",
      "primaryAxisAlignItems": "MIN",
      "padding": 16,
      "cornerRadius": 28,
      "fill": "#F9FAFB",
      "clipsContent": true,
      "itemSpacing": 16,
      "children": [
        {
          "type": "frame",
          "name": "Header",
          "layoutMode": "HORIZONTAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "counterAxisAlignItems": "CENTER",
          "itemSpacing": 12
        },
        {
          "type": "frame",
          "name": "Stats Row",
          "layoutMode": "HORIZONTAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "itemSpacing": 12,
          "children": [
            {
              "type": "frame",
              "name": "Stat Card / Revenue",
              "layoutMode": "VERTICAL",
              "layoutSizingVertical": "HUG",
              "layoutGrow": 1,
              "padding": 16,
              "cornerRadius": 12,
              "fill": "#FFFFFF",
              "itemSpacing": 4
            },
            {
              "type": "frame",
              "name": "Stat Card / Users",
              "layoutMode": "VERTICAL",
              "layoutSizingVertical": "HUG",
              "layoutGrow": 1,
              "padding": 16,
              "cornerRadius": 12,
              "fill": "#FFFFFF",
              "itemSpacing": 4
            },
            {
              "type": "frame",
              "name": "Stat Card / Orders",
              "layoutMode": "VERTICAL",
              "layoutSizingVertical": "HUG",
              "layoutGrow": 1,
              "padding": 16,
              "cornerRadius": 12,
              "fill": "#FFFFFF",
              "itemSpacing": 4
            }
          ]
        },
        {
          "type": "frame",
          "name": "Chart Area",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "padding": 16,
          "cornerRadius": 12,
          "fill": "#FFFFFF",
          "itemSpacing": 12,
          "children": [
            {
              "type": "frame",
              "name": "Chart Placeholder",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "FIXED",
              "height": 200,
              "cornerRadius": 8,
              "fill": "#F3F4F6"
            }
          ]
        },
        {
          "type": "frame",
          "name": "Recent Activity",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "itemSpacing": 0
        }
      ]
    }
  },
  "list-detail": {
    "structure": "Screen (VERTICAL, FIXED 402×874, padding 0)\n  ├── Header (HORIZONTAL, FILL/HUG, padding 16-24, itemSpacing 12)\n  │     ├── Back arrow icon (24×24)\n  │     ├── Title (\"Products\")\n  │     └── Filter/Search icon (right-aligned)\n  ├── Search Bar (HORIZONTAL, FILL/HUG, margin-h 16, padding 12, cornerRadius 8, fill gray-100)\n  │     ├── Search icon (16×16, muted)\n  │     └── Placeholder text (\"Search...\")\n  └── List (VERTICAL, FILL/FILL, padding-h 16, itemSpacing 0)\n        └── List Item × N (HORIZONTAL, FILL/HUG, padding 12-16, itemSpacing 12)\n              ├── Thumbnail (48-64px square, cornerRadius 8, fill gray-100)\n              ├── Content (VERTICAL, FILL/HUG, itemSpacing 4)\n              │     ├── Title (16px, semibold)\n              │     └── Subtitle (14px, muted)\n              └── Trailing (price, chevron, or badge)",
    "keyDecisions": {
      "listScrolling": "primaryAxisAlignItems: \"MIN\" (scrollable list, not SPACE_BETWEEN)",
      "itemSeparators": "Use itemSpacing: 0 + bottom stroke on each item, OR itemSpacing: 8 with card-style items",
      "thumbnailAspect": "Square (1:1) for products/avatars, 16:9 for articles/media",
      "emptyState": "When list is empty: centered illustration + heading + CTA button",
      "pullToRefresh": "Not applicable in Figma — design the static loaded state"
    },
    "pitfalls": [
      "overflow-parent: list items overflow screen when too many",
      "wcag-target-size: list item < 48px total height",
      "empty-container: thumbnail placeholder left empty",
      "text-overflow: long titles overflow content column",
      "no-autolayout: list items manually positioned instead of auto-layout"
    ],
    "toneVariants": {
      "minimal": {
        "cornerRadius": "8px",
        "colors": "white background, gray-100 thumbnails, subtle dividers",
        "typography": "clean sans-serif, regular/medium weights"
      },
      "warm": {
        "cornerRadius": "12px",
        "colors": "warm surface tones, soft card backgrounds",
        "typography": "friendly geometric font"
      },
      "bold": {
        "cornerRadius": "16px",
        "colors": "dark cards or colored backgrounds, vivid accent for badges",
        "typography": "strong weight for titles, condensed for metadata"
      }
    },
    "exampleParams": {
      "name": "Screen / List",
      "width": 402,
      "height": 874,
      "layoutMode": "VERTICAL",
      "primaryAxisAlignItems": "MIN",
      "cornerRadius": 28,
      "fill": "#FFFFFF",
      "clipsContent": true,
      "itemSpacing": 0,
      "children": [
        {
          "type": "frame",
          "name": "Header",
          "layoutMode": "HORIZONTAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "padding": 16,
          "counterAxisAlignItems": "CENTER",
          "itemSpacing": 12
        },
        {
          "type": "frame",
          "name": "Search Bar",
          "layoutMode": "HORIZONTAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "padding": 12,
          "marginLeft": 16,
          "marginRight": 16,
          "cornerRadius": 8,
          "fill": "#F3F4F6",
          "counterAxisAlignItems": "CENTER",
          "itemSpacing": 8
        },
        {
          "type": "frame",
          "name": "List",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "FILL",
          "paddingLeft": 16,
          "paddingRight": 16,
          "itemSpacing": 0,
          "children": [
            {
              "type": "frame",
              "name": "List Item",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "HUG",
              "padding": 12,
              "itemSpacing": 12,
              "counterAxisAlignItems": "CENTER",
              "children": [
                {
                  "type": "frame",
                  "name": "Thumbnail",
                  "width": 48,
                  "height": 48,
                  "cornerRadius": 8,
                  "fill": "#F3F4F6"
                },
                {
                  "type": "frame",
                  "name": "Content",
                  "layoutMode": "VERTICAL",
                  "layoutSizingHorizontal": "FILL",
                  "layoutSizingVertical": "HUG",
                  "itemSpacing": 4,
                  "layoutGrow": 1
                }
              ]
            }
          ]
        }
      ]
    }
  },
  "login": {
    "structure": "Screen (VERTICAL, FIXED 402×874, SPACE_BETWEEN, padding 24)\n  ├── Top Content (VERTICAL, FILL/HUG, itemSpacing 24)\n  │     ├── Logo / Brand mark (48-64px)\n  │     ├── Heading (\"Welcome back\")\n  │     └── Subheading (optional, muted color)\n  ├── Form (VERTICAL, FILL/HUG, itemSpacing 12-16)\n  │     ├── Email input (HORIZONTAL, FILL/HUG, stroke, cornerRadius 8-12, padding 16, height ≥48)\n  │     ├── Password input (same structure)\n  │     ├── Forgot password link (right-aligned text, small)\n  │     └── Primary CTA (HORIZONTAL, FILL/FIXED height ≥48, centered text, cornerRadius 8-12, fill accent)\n  └── Bottom Content (VERTICAL, FILL/HUG, itemSpacing 16)\n        ├── Divider with \"or\" label\n        ├── Social login row (HORIZONTAL, gap 12-16)\n        └── Sign up link (\"Don't have an account? Sign up\")",
    "keyDecisions": {
      "layout": "SPACE_BETWEEN distributes top brand + form + bottom links; form group centered vertically",
      "buttonHeight": "≥48px, full-width on mobile, centered text",
      "inputSpacing": "12-16px between fields, 24px between form sections",
      "padding": "horizontal 24px, top 60-80px (below status bar), bottom 34px (home indicator)",
      "inputStructure": "HORIZONTAL auto-layout frame with stroke, no standalone text — always wrapped in frame"
    },
    "pitfalls": [
      "button-structure: CTA height < 48px or missing auto-layout",
      "input-field-structure: input missing stroke or cornerRadius",
      "text-overflow: long email addresses overflow input frame",
      "screen-bottom-overflow: form + social login + links overflow viewport",
      "wcag-contrast: light gray placeholder text fails 4.5:1 ratio — use #6B7280 minimum for secondary text",
      "sizing-collapse: input/button children default to HUG width — explicitly set layoutSizingHorizontal:\"FILL\" on all inputs, buttons, and divider rows",
      "icon-placeholder: NEVER use \">\" text for chevron or \"...\" for more — call icon_search + icon_create for lucide:chevron-right, lucide:ellipsis, etc.",
      "social-login-icons: Social buttons MUST include brand icons (lucide:apple, iconoir:google) — text-only buttons look unfinished",
      "logo-as-rectangle: Logo placeholder must be type:\"frame\" with centered icon inside, NOT type:\"rectangle\" (which cannot have children)",
      "clipsContent-text: Pure text wrapper frames should use clipsContent:false to prevent text clipping when frame height is tight"
    ],
    "toneVariants": {
      "minimal": {
        "cornerRadius": "8-12px",
        "colors": "monochrome + 1 accent, white background, light gray inputs",
        "typography": "1 font weight for body, 1 for heading"
      },
      "elegant": {
        "cornerRadius": "12-16px",
        "colors": "warm neutrals + gold/copper accent",
        "typography": "serif heading + sans body"
      },
      "bold": {
        "cornerRadius": "16-24px",
        "colors": "gradient or saturated hero background + high-contrast CTA",
        "typography": "heavy weight heading, generous spacing"
      }
    },
    "exampleParams": {
      "name": "Screen / Login",
      "width": 402,
      "height": 874,
      "layoutMode": "VERTICAL",
      "primaryAxisAlignItems": "SPACE_BETWEEN",
      "padding": 24,
      "paddingTop": 60,
      "paddingBottom": 34,
      "cornerRadius": 28,
      "fill": "#FFFFFF",
      "clipsContent": true,
      "children": [
        {
          "type": "frame",
          "name": "Top Content",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "itemSpacing": 24,
          "children": [
            {
              "type": "frame",
              "name": "Logo",
              "width": 48,
              "height": 48,
              "cornerRadius": 12,
              "fill": "#F3F4F6"
            }
          ]
        },
        {
          "type": "frame",
          "name": "Form",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "itemSpacing": 16,
          "children": [
            {
              "type": "frame",
              "name": "Input / Email",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "FIXED",
              "height": 48,
              "padding": 16,
              "cornerRadius": 12,
              "strokeColor": "#D1D5DB",
              "strokeWeight": 1
            },
            {
              "type": "frame",
              "name": "Input / Password",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "FIXED",
              "height": 48,
              "padding": 16,
              "cornerRadius": 12,
              "strokeColor": "#D1D5DB",
              "strokeWeight": 1
            },
            {
              "type": "frame",
              "name": "Button / Primary",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "FIXED",
              "height": 48,
              "cornerRadius": 12,
              "fill": "#111827",
              "primaryAxisAlignItems": "CENTER",
              "counterAxisAlignItems": "CENTER"
            }
          ]
        },
        {
          "type": "frame",
          "name": "Bottom Content",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "itemSpacing": 16,
          "children": [
            {
              "type": "frame",
              "name": "Divider Row",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "HUG",
              "counterAxisAlignItems": "CENTER",
              "itemSpacing": 12
            },
            {
              "type": "frame",
              "name": "Social Login Row",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "HUG",
              "itemSpacing": 12
            }
          ]
        }
      ]
    }
  },
  "onboarding": {
    "structure": "Use Multi-Screen Flow Architecture (see get_creation_guide topic:\"multi-screen\").\n\nPer Screen (VERTICAL, FIXED 402×874, padding 24, SPACE_BETWEEN):\n  ├── Top Content (VERTICAL, FILL/HUG, itemSpacing 16-24)\n  │     ├── Illustration / Hero image (FILL/FIXED height 200-300)\n  │     ├── Heading (24-28px, max 2 lines)\n  │     └── Body text (14-16px, max 3 lines, muted)\n  └── Bottom Content (VERTICAL, FILL/HUG, itemSpacing 12)\n        ├── Progress indicator (dots or bar)\n        ├── Primary CTA (\"Next\" / \"Continue\" / \"Get Started\")\n        └── Skip link (optional, \"Skip\" text button)",
    "keyDecisions": {
      "screenCount": "3-5 screens is ideal; more loses attention",
      "illustration": "Placeholder rectangle with fill and description text inside — DO NOT leave blank",
      "progressIndicator": "Dots (HORIZONTAL row, 8px circles, 8px gap) or thin bar (FILL width, 4px height)",
      "lastScreen": "Final CTA is \"Get Started\" (not \"Next\"), no skip link, may add feature summary",
      "transitions": "Each screen is independent — no carousel/swipe in Figma, just side-by-side stages"
    },
    "pitfalls": [
      "empty-container: illustration placeholder left empty (add a colored rectangle + description)",
      "cta-width-inconsistent: \"Next\" vs \"Get Started\" buttons different widths across screens",
      "text-overflow: heading > 2 lines on some screens",
      "mobile-dimensions: screen not exactly 402×874 (iOS) or 412×915 (Android)",
      "default-name: screens named \"Frame 1\", \"Frame 2\" instead of \"Onboarding Step 1\""
    ],
    "toneVariants": {
      "minimal": {
        "cornerRadius": "8-12px",
        "colors": "white background, one accent for CTA and progress dots",
        "typography": "lightweight, generous line height"
      },
      "warm": {
        "cornerRadius": "16-20px",
        "colors": "soft gradient backgrounds, friendly illustration style",
        "typography": "rounded sans-serif, warm tones"
      },
      "bold": {
        "cornerRadius": "20-28px",
        "colors": "full-bleed colored backgrounds per screen, white text",
        "typography": "large heading (28-32px), strong hierarchy"
      }
    },
    "exampleParams": {
      "name": "Screen / Onboarding",
      "width": 402,
      "height": 874,
      "layoutMode": "VERTICAL",
      "primaryAxisAlignItems": "SPACE_BETWEEN",
      "padding": 24,
      "paddingTop": 60,
      "paddingBottom": 34,
      "cornerRadius": 28,
      "fill": "#FFFFFF",
      "clipsContent": true,
      "children": [
        {
          "type": "frame",
          "name": "Top Content",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "itemSpacing": 24,
          "children": [
            {
              "type": "frame",
              "name": "Illustration",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "FIXED",
              "height": 240,
              "cornerRadius": 16,
              "fill": "#F3F4F6"
            }
          ]
        },
        {
          "type": "frame",
          "name": "Bottom Content",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "itemSpacing": 12,
          "children": [
            {
              "type": "frame",
              "name": "Progress Dots",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "HUG",
              "layoutSizingVertical": "HUG",
              "itemSpacing": 8,
              "children": [
                {
                  "type": "ellipse",
                  "name": "Dot Active",
                  "width": 8,
                  "height": 8,
                  "fill": "#111827"
                },
                {
                  "type": "ellipse",
                  "name": "Dot",
                  "width": 8,
                  "height": 8,
                  "fill": "#D1D5DB"
                },
                {
                  "type": "ellipse",
                  "name": "Dot",
                  "width": 8,
                  "height": 8,
                  "fill": "#D1D5DB"
                }
              ]
            },
            {
              "type": "frame",
              "name": "Button / Primary",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "FIXED",
              "height": 48,
              "cornerRadius": 12,
              "fill": "#111827",
              "primaryAxisAlignItems": "CENTER",
              "counterAxisAlignItems": "CENTER"
            }
          ]
        }
      ]
    }
  },
  "profile": {
    "structure": "Screen (VERTICAL, FIXED 402×874, padding 0)\n  ├── Hero Area (VERTICAL, FILL/HUG, padding 24, counterAxisAlignItems CENTER)\n  │     ├── Avatar (80-120px circle, cornerRadius 9999, fill gray-200 placeholder)\n  │     ├── Name (20-24px, semibold, margin-top 16)\n  │     ├── Handle/bio (14px, muted, max 2 lines)\n  │     └── Action Row (HORIZONTAL, HUG/HUG, itemSpacing 12, margin-top 16)\n  │           ├── Primary CTA (\"Edit Profile\" / \"Follow\")\n  │           └── Secondary action (message icon / share)\n  ├── Stats Row (HORIZONTAL, FILL/HUG, padding 16, itemSpacing 0)\n  │     └── Stat × 3 (VERTICAL, layoutGrow 1, counterAxisAlignItems CENTER)\n  │           ├── Value (18-20px, bold)\n  │           └── Label (12px, muted)\n  └── Content Area (VERTICAL, FILL/FILL, padding 0)\n        ├── Tab bar (HORIZONTAL, FILL/HUG, itemSpacing 0) or section headers\n        └── Content list (VERTICAL, FILL/FILL)",
    "keyDecisions": {
      "avatarSize": "80px compact, 120px prominent — always circle (cornerRadius 9999)",
      "statsLayout": "layoutGrow: 1 on each stat for equal distribution, centered text",
      "heroBg": "Optional cover image behind avatar (200-240px height, clipsContent true)",
      "contentTabs": "Posts / Media / Likes — underline active tab with accent color",
      "scrollBehavior": "MIN — profile content scrolls, hero can be sticky or scroll away"
    },
    "pitfalls": [
      "stats-row-cramped: stat values too close together",
      "empty-container: avatar placeholder empty — use type:\"frame\" (circle, gray fill) with lucide:circle-user-round icon centered inside, NOT type:\"rectangle\"",
      "text-overflow: bio text > 2 lines overflows",
      "wcag-contrast: muted handle/bio text below 4.5:1 — use #6B7280 minimum",
      "button-structure: action buttons missing auto-layout or < 48px height",
      "share-button-icon: share/more button should use lucide:ellipsis or lucide:share icon, NOT \"...\" text",
      "action-row-stroke: wrapper frame around buttons may inherit default strokeWeight:1 — set strokes:[] to clear"
    ],
    "toneVariants": {
      "minimal": {
        "cornerRadius": "circle avatar, 8px buttons",
        "colors": "white background, gray avatar placeholder, minimal accent",
        "typography": "clean hierarchy, 3 size tiers"
      },
      "warm": {
        "cornerRadius": "circle avatar, 16px cards",
        "colors": "warm gradient header/cover, soft card backgrounds",
        "typography": "rounded font, generous spacing"
      },
      "bold": {
        "cornerRadius": "circle avatar, 20px cards",
        "colors": "dark header with cover image, bright accent CTA",
        "typography": "large name (24px), strong stat values"
      }
    },
    "exampleParams": {
      "name": "Screen / Profile",
      "width": 402,
      "height": 874,
      "layoutMode": "VERTICAL",
      "primaryAxisAlignItems": "MIN",
      "cornerRadius": 28,
      "fill": "#FFFFFF",
      "clipsContent": true,
      "itemSpacing": 0,
      "children": [
        {
          "type": "frame",
          "name": "Hero Area",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "padding": 24,
          "counterAxisAlignItems": "CENTER",
          "itemSpacing": 16,
          "children": [
            {
              "type": "frame",
              "name": "Avatar",
              "width": 80,
              "height": 80,
              "cornerRadius": 9999,
              "fill": "#F3F4F6"
            },
            {
              "type": "frame",
              "name": "Action Row",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "HUG",
              "layoutSizingVertical": "HUG",
              "itemSpacing": 12,
              "children": [
                {
                  "type": "frame",
                  "name": "Button / Edit Profile",
                  "layoutMode": "HORIZONTAL",
                  "layoutSizingVertical": "FIXED",
                  "height": 48,
                  "padding": 16,
                  "cornerRadius": 12,
                  "fill": "#111827",
                  "primaryAxisAlignItems": "CENTER",
                  "counterAxisAlignItems": "CENTER"
                }
              ]
            }
          ]
        },
        {
          "type": "frame",
          "name": "Stats Row",
          "layoutMode": "HORIZONTAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "padding": 16,
          "itemSpacing": 0,
          "children": [
            {
              "type": "frame",
              "name": "Stat / Posts",
              "layoutMode": "VERTICAL",
              "layoutSizingVertical": "HUG",
              "layoutGrow": 1,
              "counterAxisAlignItems": "CENTER",
              "itemSpacing": 2
            },
            {
              "type": "frame",
              "name": "Stat / Followers",
              "layoutMode": "VERTICAL",
              "layoutSizingVertical": "HUG",
              "layoutGrow": 1,
              "counterAxisAlignItems": "CENTER",
              "itemSpacing": 2
            },
            {
              "type": "frame",
              "name": "Stat / Following",
              "layoutMode": "VERTICAL",
              "layoutSizingVertical": "HUG",
              "layoutGrow": 1,
              "counterAxisAlignItems": "CENTER",
              "itemSpacing": 2
            }
          ]
        },
        {
          "type": "frame",
          "name": "Content Area",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "FILL",
          "itemSpacing": 0,
          "children": [
            {
              "type": "frame",
              "name": "Tab Bar",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "HUG",
              "itemSpacing": 0
            }
          ]
        }
      ]
    }
  },
  "settings": {
    "structure": "Screen (VERTICAL, FIXED 402×874, padding 0)\n  ├── Header (HORIZONTAL, FILL/HUG, padding 16-24)\n  │     └── Title (\"Settings\")\n  └── Sections (VERTICAL, FILL/FILL, padding-h 0, itemSpacing 24)\n        └── Section × N (VERTICAL, FILL/HUG, itemSpacing 0)\n              ├── Section Header (padding-h 16, 12px uppercase, muted, letterSpacing 1)\n              └── Row × N (HORIZONTAL, FILL/HUG, padding 16, itemSpacing 12, min-height 48)\n                    ├── Icon (24×24, optional)\n                    ├── Label (FILL/HUG, layoutGrow 1, 16px)\n                    └── Trailing (toggle switch / chevron / value text)",
    "keyDecisions": {
      "sectionGrouping": "Group related rows under section headers (Account, Preferences, About)",
      "rowTrailing": "Toggle for on/off settings, chevron (>) for drill-down, value text for display-only",
      "destructiveRow": "Red text for \"Log out\" / \"Delete account\" — always at bottom",
      "padding": "Rows full-width (padding-h 16), sections separated by 24px gap or gray divider",
      "scrollBehavior": "primaryAxisAlignItems: \"MIN\" — settings scroll vertically"
    },
    "pitfalls": [
      "wcag-target-size: toggle switch or row < 48px height — MUST set layoutSizingVertical:\"FIXED\" + height:48 on every row",
      "form-consistency: rows have inconsistent heights or padding",
      "default-name: rows named \"Frame 1\" instead of \"Settings Row / Notifications\"",
      "text-overflow: label text too long for single line",
      "nav-overcrowded: too many rows without section grouping",
      "chevron-as-text: NEVER use \">\" text for drill-down indicator — use icon_create with lucide:chevron-right (size 18)",
      "toggle-clipped: toggle switch (44×26) gets clipped if parent row has clipsContent:true and insufficient height — ensure row height ≥48px",
      "card-group-radius: grouped settings card (white bg on gray screen) should have cornerRadius 12px and paddingTop/Bottom 4px for visual separation"
    ],
    "toneVariants": {
      "minimal": {
        "cornerRadius": "0px (full-width rows)",
        "colors": "white background, gray section headers, system blue toggles",
        "typography": "system font, 16px body"
      },
      "elegant": {
        "cornerRadius": "12px (card sections)",
        "colors": "grouped card backgrounds, subtle shadows",
        "typography": "medium weight labels, light descriptions"
      },
      "bold": {
        "cornerRadius": "16px (card sections)",
        "colors": "dark background, accent-colored icons",
        "typography": "larger labels (17-18px), strong weight"
      }
    },
    "exampleParams": {
      "name": "Screen / Settings",
      "width": 402,
      "height": 874,
      "layoutMode": "VERTICAL",
      "primaryAxisAlignItems": "MIN",
      "cornerRadius": 28,
      "fill": "#F9FAFB",
      "clipsContent": true,
      "itemSpacing": 0,
      "children": [
        {
          "type": "frame",
          "name": "Header",
          "layoutMode": "HORIZONTAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "padding": 16,
          "counterAxisAlignItems": "CENTER"
        },
        {
          "type": "frame",
          "name": "Sections",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "FILL",
          "itemSpacing": 24,
          "paddingTop": 16,
          "children": [
            {
              "type": "frame",
              "name": "Section / Account",
              "layoutMode": "VERTICAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "HUG",
              "itemSpacing": 0,
              "cornerRadius": 12,
              "fill": "#FFFFFF",
              "paddingTop": 4,
              "paddingBottom": 4,
              "children": [
                {
                  "type": "frame",
                  "name": "Row / Profile",
                  "layoutMode": "HORIZONTAL",
                  "layoutSizingHorizontal": "FILL",
                  "layoutSizingVertical": "FIXED",
                  "height": 48,
                  "padding": 16,
                  "itemSpacing": 12,
                  "counterAxisAlignItems": "CENTER"
                },
                {
                  "type": "frame",
                  "name": "Row / Notifications",
                  "layoutMode": "HORIZONTAL",
                  "layoutSizingHorizontal": "FILL",
                  "layoutSizingVertical": "FIXED",
                  "height": 48,
                  "padding": 16,
                  "itemSpacing": 12,
                  "counterAxisAlignItems": "CENTER"
                },
                {
                  "type": "frame",
                  "name": "Row / Privacy",
                  "layoutMode": "HORIZONTAL",
                  "layoutSizingHorizontal": "FILL",
                  "layoutSizingVertical": "FIXED",
                  "height": 48,
                  "padding": 16,
                  "itemSpacing": 12,
                  "counterAxisAlignItems": "CENTER"
                }
              ]
            }
          ]
        }
      ]
    }
  },
  "signup": {
    "structure": "Screen (VERTICAL, FIXED 402×874, SPACE_BETWEEN, padding 24)\n  ├── Top Content (VERTICAL, FILL/HUG, itemSpacing 24)\n  │     ├── Heading (\"Create account\")\n  │     └── Subheading (\"Join 10,000+ users\")\n  ├── Form (VERTICAL, FILL/HUG, itemSpacing 12-16)\n  │     ├── Name input (full width or split first/last as HORIZONTAL row)\n  │     ├── Email input\n  │     ├── Password input (with strength indicator below)\n  │     ├── Terms checkbox row (HORIZONTAL, gap 8, \"I agree to Terms\")\n  │     └── Primary CTA (\"Create account\")\n  └── Bottom Content (VERTICAL, FILL/HUG)\n        ├── Social signup options (HORIZONTAL or VERTICAL stack)\n        └── Login link (\"Already have an account? Log in\")",
    "keyDecisions": {
      "layout": "SPACE_BETWEEN or MIN depending on field count; 3-4 fields use SPACE_BETWEEN, 5+ use MIN with scroll",
      "formDensity": "Keep above fold: if >4 fields, consider multi-step (see onboarding pattern)",
      "passwordStrength": "Small bar or dots below password input, color-coded (red→yellow→green)",
      "terms": "Checkbox + inline text link, not a separate screen"
    },
    "pitfalls": [
      "form-consistency: name fields (first/last) different heights in the same row",
      "screen-bottom-overflow: many fields push CTA below viewport",
      "wcag-target-size: terms checkbox < 44px touch target",
      "input-field-structure: password strength indicator not inside input frame",
      "text-overflow: terms text wraps awkwardly on small screens"
    ],
    "toneVariants": {
      "minimal": {
        "cornerRadius": "8-12px",
        "colors": "clean white, subtle input borders",
        "typography": "single font family, 2 weights"
      },
      "warm": {
        "cornerRadius": "12-16px",
        "colors": "soft pastels, rounded friendly aesthetic",
        "typography": "rounded or geometric sans-serif"
      },
      "bold": {
        "cornerRadius": "16-24px",
        "colors": "vibrant accent on CTA, dark or colored background",
        "typography": "strong contrast between heading and body"
      }
    },
    "exampleParams": {
      "name": "Screen / Signup",
      "width": 402,
      "height": 874,
      "layoutMode": "VERTICAL",
      "primaryAxisAlignItems": "SPACE_BETWEEN",
      "padding": 24,
      "paddingTop": 60,
      "paddingBottom": 34,
      "cornerRadius": 28,
      "fill": "#FFFFFF",
      "clipsContent": true,
      "children": [
        {
          "type": "frame",
          "name": "Top Content",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "itemSpacing": 8
        },
        {
          "type": "frame",
          "name": "Form",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "itemSpacing": 16,
          "children": [
            {
              "type": "frame",
              "name": "Input / Name",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "FIXED",
              "height": 48,
              "padding": 16,
              "cornerRadius": 12,
              "strokeColor": "#D1D5DB",
              "strokeWeight": 1
            },
            {
              "type": "frame",
              "name": "Input / Email",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "FIXED",
              "height": 48,
              "padding": 16,
              "cornerRadius": 12,
              "strokeColor": "#D1D5DB",
              "strokeWeight": 1
            },
            {
              "type": "frame",
              "name": "Input / Password",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "FIXED",
              "height": 48,
              "padding": 16,
              "cornerRadius": 12,
              "strokeColor": "#D1D5DB",
              "strokeWeight": 1
            },
            {
              "type": "frame",
              "name": "Terms Row",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "HUG",
              "itemSpacing": 8,
              "counterAxisAlignItems": "CENTER"
            },
            {
              "type": "frame",
              "name": "Button / Primary",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "FIXED",
              "height": 48,
              "cornerRadius": 12,
              "fill": "#111827",
              "primaryAxisAlignItems": "CENTER",
              "counterAxisAlignItems": "CENTER"
            }
          ]
        },
        {
          "type": "frame",
          "name": "Bottom Content",
          "layoutMode": "VERTICAL",
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "itemSpacing": 16,
          "children": [
            {
              "type": "frame",
              "name": "Social Signup Row",
              "layoutMode": "HORIZONTAL",
              "layoutSizingHorizontal": "FILL",
              "layoutSizingVertical": "HUG",
              "itemSpacing": 12
            }
          ]
        }
      ]
    }
  },
};
