// Auto-generated by scripts/compile-content.ts — DO NOT EDIT
// Source: content/harness/*.yaml

export interface RecoveryPattern {
  name: string;
  tools: string[];
  patterns: RegExp[];
  errorType: string;
  suggestion: string;
  retryHint?: Record<string, unknown>;
  doNotRetry?: boolean;
}

export const RECOVERY_PATTERNS: RecoveryPattern[] = [
  {
    name: 'connection-lost',
    tools: ['*'],
    patterns: [
      /bridge not connected/i,
      /connection closed/i,
      /connection to relay timed out/i,
      /websocket.*closed/i,
      /connection.*refused/i,
    ],
    errorType: 'connection_lost',
    suggestion:
      'STOP — FigCraft plugin is not connected. Do NOT fall back to other MCP servers (figma-desktop, figma-remote) — they lack the tools this workflow requires. Tell user: open Figma → Plugins → FigCraft → wait for connection, then retry.',
    doNotRetry: true,
  },
  {
    name: 'request-timeout',
    tools: ['*'],
    patterns: [/^request .* timed out after/i, /request timed out after .* \(progress was received\)/i],
    errorType: 'request_timeout',
    suggestion:
      'The request exceeded the 30s bridge timeout. This usually means the handler did too much work — not a connection problem. Narrow the scope: pass a specific nodeId instead of walking the whole page, tighten types/query filters, lower maxDepth, or use a more targeted endpoint (variables_ep for variables, styles_ep for styles, search_design_system for library components). Restarting the plugin will NOT help.',
  },
  {
    name: 'token-not-found',
    tools: [
      'create_frame',
      'create_text',
      'create_svg',
      'create_rectangle',
      'create_ellipse',
      'create_component',
      'create_component_set',
      'nodes',
      'variables_ep',
    ],
    patterns: [/variable.*not found/i, /token.*not found/i, /no matching.*variable/i, /cannot find.*variable/i],
    errorType: 'token_not_found',
    suggestion:
      'The requested variable/token was not found. Call search_design_system(query:"<token name>") to find available tokens, or omit the variable name to use a hardcoded value as fallback.',
    retryHint: { fillVariableName: null, strokeVariableName: null },
  },
  {
    name: 'node-deleted',
    tools: ['*'],
    patterns: [/node.*does not exist/i, /node.*not found/i, /cannot find node/i, /invalid.*node.*id/i],
    errorType: 'node_deleted',
    suggestion:
      'The referenced node no longer exists (may have been deleted or moved). Call nodes(method:"list") or get_current_page() to get current node IDs.',
  },
  {
    name: 'file-not-found',
    tools: ['sync_tokens'],
    patterns: [/ENOENT/i, /no such file/i, /file not found/i, /cannot read file/i],
    errorType: 'file_not_found',
    suggestion:
      'Token file not found. Check the file path — use an absolute path. Ensure the DTCG JSON file exists at the specified location.',
  },
  {
    name: 'parse-error',
    tools: ['sync_tokens'],
    patterns: [/json.*parse/i, /syntax.*error.*json/i, /unexpected.*token/i, /invalid.*json/i],
    errorType: 'parse_error',
    suggestion:
      'Token file contains invalid JSON. The file must be a valid DTCG JSON format with $type and $value fields.',
  },
  {
    name: 'create-frame-failure',
    tools: ['create_frame'],
    patterns: [/error/i],
    errorType: 'create_frame_failure',
    suggestion:
      'create_frame failed. Before retrying, review ALL remaining planned payloads for the same pattern — the same mistake likely affects other calls. Use dryRun:true to preview Opinion Engine inferences before committing.',
  },
  {
    name: 'response-too-large',
    tools: ['*'],
    patterns: [/too large/i, /response.*exceed/i, /context overflow/i],
    errorType: 'response_too_large',
    suggestion:
      'Response exceeded the size limit. Narrow the scope: use a specific nodeId instead of fetching the full page, reduce maxDepth, or use detail:"summary".',
  },
];

export interface NextStepsDef {
  tool: string;
  steps: string[];
}

export const NEXT_STEPS: NextStepsDef[] = [
  {
    tool: 'sync_tokens',
    steps: [
      'Run lint_fix_all to check compliance with synced tokens.',
      'Use export_image on modified screens to verify visual changes.',
      'Run verify_design for a final quality audit.',
    ],
  },
  { tool: 'set_mode', steps: ['Call get_mode to refresh workflow instructions for the new mode.'] },
  {
    tool: 'get_mode',
    steps: [
      '⛔ SKILL ROUTING: This project uses figcraft-* skills (NOT external figma-* skills). Use figcraft-generate-design for screen assembly, figcraft-generate-library for design system building, figcraft-use before use_figma calls, figcraft-implement-design for Figma-to-code, figcraft-code-connect for Code Connect, figcraft-create-design-system-rules for rules generation. Do NOT load external skills: baseline-ui, ui-ux-pro-max, web-design-guidelines.',
    ],
  },
  {
    tool: 'create_component',
    steps: [
      '⛔ SIZE VARIANTS — Create SEPARATE base components with different textStyleName values. Do NOT derive smaller variants via text.set_range on fontSize/fontName — this silently DETACHES the text style binding (Figma API behavior). If accidentally detached, rebind via nodes(method:"update", patches:[{nodeId, props:{textStyleId:"S:..."}}]).',
      '⛔ ICON COLOR BINDING — colorVariableName on stroke-based icons (lucide, tabler) is SILENTLY SKIPPED (scope mismatch: most text/* variables lack STROKE_COLOR). The ONLY reliable path: POST-CREATION bind_component_property with nodeProperty:"iconColor" and variantFilter. Group by Type; separate std vs Loading variants (different child names). Check _tokenBindingFailures — if any icon color bindings were skipped, this step is mandatory.',
      '⛔ BATCH EXPLICIT PARAMS — In items:[] batch mode, ALWAYS explicitly set itemSpacing, padding*, and cornerRadius in EVERY item. Opinion Engine inference may vary across items (different children → different layoutSizing), causing inconsistency within the same ComponentSet.',
      '⛔ FULL-WIDTH IN COMPONENT SETS — ComponentSet uses absolute positioning, so variants CANNOT use layoutSizingHorizontal:"FILL". Use explicit fixed width (e.g. width:360) on each variant. Consumers apply FILL when placing instances.',
    ],
  },
];
