// Auto-generated by scripts/compile-content.ts — DO NOT EDIT
// Source: content/harness/*.yaml

export interface RecoveryPattern {
  name: string;
  tools: string[];
  patterns: RegExp[];
  errorType: string;
  suggestion: string;
  retryHint?: Record<string, unknown>;
  doNotRetry?: boolean;
}

export const RECOVERY_PATTERNS: RecoveryPattern[] = [
  {
    name: 'connection-lost',
    tools: ['*'],
    patterns: [
      /bridge not connected/i,
      /connection closed/i,
      /connection to relay timed out/i,
      /websocket.*closed/i,
      /connection.*refused/i,
    ],
    errorType: 'connection_lost',
    suggestion:
      'Lost connection to Figma plugin. Check that the FigCraft plugin is running in Figma. Try calling ping to verify connection.',
  },
  {
    name: 'request-timeout',
    tools: ['*'],
    patterns: [/^request .* timed out after/i, /request timed out after .* \(progress was received\)/i],
    errorType: 'request_timeout',
    suggestion:
      'The request exceeded the 30s bridge timeout. This usually means the handler did too much work — not a connection problem. Narrow the scope: pass a specific nodeId instead of walking the whole page, tighten types/query filters, lower maxDepth, or use a more targeted endpoint (variables_ep for variables, styles_ep for styles, search_design_system for library components). Restarting the plugin will NOT help.',
  },
  {
    name: 'token-not-found',
    tools: [
      'create_frame',
      'create_text',
      'create_svg',
      'create_rectangle',
      'create_ellipse',
      'create_component',
      'create_component_set',
      'nodes',
      'variables_ep',
    ],
    patterns: [/variable.*not found/i, /token.*not found/i, /no matching.*variable/i, /cannot find.*variable/i],
    errorType: 'token_not_found',
    suggestion:
      'The requested variable/token was not found. Call search_design_system(query:"<token name>") to find available tokens, or omit the variable name to use a hardcoded value as fallback.',
    retryHint: { fillVariableName: null, strokeVariableName: null },
  },
  {
    name: 'node-deleted',
    tools: ['*'],
    patterns: [/node.*does not exist/i, /node.*not found/i, /cannot find node/i, /invalid.*node.*id/i],
    errorType: 'node_deleted',
    suggestion:
      'The referenced node no longer exists (may have been deleted or moved). Call nodes(method:"list") or get_current_page() to get current node IDs.',
  },
  {
    name: 'file-not-found',
    tools: ['sync_tokens'],
    patterns: [/ENOENT/i, /no such file/i, /file not found/i, /cannot read file/i],
    errorType: 'file_not_found',
    suggestion:
      'Token file not found. Check the file path — use an absolute path. Ensure the DTCG JSON file exists at the specified location.',
  },
  {
    name: 'parse-error',
    tools: ['sync_tokens'],
    patterns: [/json.*parse/i, /syntax.*error.*json/i, /unexpected.*token/i, /invalid.*json/i],
    errorType: 'parse_error',
    suggestion:
      'Token file contains invalid JSON. The file must be a valid DTCG JSON format with $type and $value fields.',
  },
  {
    name: 'create-frame-failure',
    tools: ['create_frame'],
    patterns: [/error/i],
    errorType: 'create_frame_failure',
    suggestion:
      'create_frame failed. Before retrying, review ALL remaining planned payloads for the same pattern — the same mistake likely affects other calls. Use dryRun:true to preview Opinion Engine inferences before committing.',
  },
  {
    name: 'response-too-large',
    tools: ['*'],
    patterns: [/too large/i, /response.*exceed/i, /context overflow/i],
    errorType: 'response_too_large',
    suggestion:
      'Response exceeded the size limit. Narrow the scope: use a specific nodeId instead of fetching the full page, reduce maxDepth, or use detail:"summary".',
  },
];

export interface NextStepsDef {
  tool: string;
  steps: string[];
}

export const NEXT_STEPS: NextStepsDef[] = [
  {
    tool: 'sync_tokens',
    steps: [
      'Run lint_fix_all to check compliance with synced tokens.',
      'Use export_image on modified screens to verify visual changes.',
      'Run verify_design for a final quality audit.',
    ],
  },
  { tool: 'set_mode', steps: ['Call get_mode to refresh workflow instructions for the new mode.'] },
  {
    tool: 'get_mode',
    steps: [
      '⛔ SKILL ROUTING: This project uses figcraft-* skills (NOT external figma-* skills). Use figcraft-generate-design for screen assembly, figcraft-generate-library for design system building, figcraft-use before use_figma calls, figcraft-implement-design for Figma-to-code, figcraft-code-connect for Code Connect, figcraft-create-design-system-rules for rules generation. Do NOT load external skills: baseline-ui, ui-ux-pro-max, web-design-guidelines.',
    ],
  },
  {
    tool: 'create_component',
    steps: [
      'Size variants (Large/Medium/Small buttons, etc.): create SEPARATE base components with different `textStyleName` values — do NOT try to derive a smaller variant from a larger base by using text.set_range to change fontSize. set_range on fontSize or fontName silently DETACHES the text style binding (Figma API behavior, not a bug), leaving the variant unable to inherit body-md/body-xl properly.',
      'If a text style binding was accidentally detached by prior set_range calls, re-bind via nodes(method:"update", patches:[{nodeId, props:{textStyleId:"S:..."}}]) — this is the direct rebind path and respects font preloading.',
      'For color / variable binding on a component or its children, pass strings — NEVER objects. Correct: fillVariableId:"VariableID:123:456" or fillVariableName:"button/emphasis". Wrong: fill:{variableId:"..."} or fill:{variable:"..."} — these are now rejected upfront with a self-correcting error, but the correct shape avoids the rejection entirely.',
      'P2 — BOOLEAN visibility binding is now inline in create_component. Declare the property in `properties:[]` AND reference it from the child via componentPropertyReferences. Example: properties:[{type:"BOOLEAN", propertyName:"Icon", defaultValue:false}], children:[ {type:"icon", name:"Icon", icon:"lucide:arrow-right", componentPropertyReferences:{visible:"Icon"}}]. Declaring the BOOLEAN property alone WITHOUT the child reference leaves it orphaned (create_component now warns about this); declaring the reference without the property is equally a no-op and also warned. For post-creation wiring on an existing component, call bind_component_property (core tool) — pass the `bindings` array to batch. Do NOT fall back to execute_js — that path bypasses Opinion Engine and hint aggregation.',
      'Variant matrices (≥8 variants, e.g. Button with 4 Type × 2 Size × 4 State = 32): DO NOT clone + rename loop. Use create_component\'s `items:[]` batch mode — one call creates up to 20 components with individual params, inline children (icons resolve automatically), and inline `properties:[]` arrays. Then create_component_set combines them into a variant set. For binding the same variable to many nodes after creation, use variables_ep(method:"batch_bind", bindings:[...]). The clone-and-modify path costs 3-5× more tool calls and trips Opinion Engine re-inference edge cases.',
      'Icon children in create_component work the same as in create_frame: pass {type:"icon", icon:"lucide:chevron-right", size:24, colorVariableName:"text/primary"} inline in `children`. The harness resolves them to SVG before the Plugin sees them. DO NOT call icon_create then nodes.update to splice the icon in — that\'s 2 extra calls plus manual parenting. If an icon child fails, the response\'s _warnings array reports which icon and why; the SVG placeholder keeps creation from breaking.',
      'For post-creation variable binding (e.g. binding existing node fills to variables by ID), call variables_ep(method:"batch_bind") — NOT nodes(method:"update", patches:[{props:{fillVariableId:...}}]). patch_nodes only accepts raw Figma props (fills, strokes arrays, etc.); variable binding goes through variables_ep. This is now surfaced as a self-correcting error if you try the wrong path.',
    ],
  },
];
